import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {basePreferences} from '../../src/helpers/businessListPreferences';
for(const width of [1280,390])test(`remaining badges edit their explicit business or management at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});const mutations:any[]=[];let release!:()=>void;const slow=new Promise<void>(resolve=>{release=resolve;});
 const account={id:'1',nombre:'Negocio 1',ciudad:'Colón',assignedUserEmail:'owner@example.com',tipo:'Alojamientos',subtipo:'Cabaña',archivedAt:null};
 const management={id:'11',accountId:'1',opportunityName:'Gestión propia',estado:'Cargado',assignedUserEmail:'owner@example.com',commercialProfile:'Independiente',medioContactoPreferido:'Email',origen:'Facebook',quienCargo:'Legacy',creadoPor:'Legacy'};
 const otherManagement={...management,id:'12',opportunityName:'Gestión ajena',assignedUserEmail:'other@example.com'};
 await page.addInitScript(preferences=>{localStorage.setItem('hospeda-live-mode','off');localStorage.setItem('hospeda-business-list-v1-user-3',JSON.stringify({preferences,context:{page:1,scrollY:0,scrollX:0}}));},{...basePreferences(),columns:['nombre','tipo','subtipo','commercialProfile','medioContactoPreferido','origen','quienCargo','creadoPor','actions'],pins:{actions:'right'}});
 await page.route('**/_api/**',async route=>{
  const url=new URL(route.request().url());let data:unknown={};
  if(url.pathname.endsWith('/auth/session'))data={user:{id:3,email:'owner@example.com',displayName:'Owner',role:'user'}};
  else if(url.pathname.endsWith('/business_list_defaults'))data={defaults:null};
  else if(url.pathname.endsWith('/saved_views'))data={views:[]};
  else if(url.pathname.endsWith('/settings'))data={users:[{id:3,email:'owner@example.com',displayName:'Owner',role:'user'},{id:4,email:'other@example.com',displayName:'Other',role:'user'}],cities:[{id:'1',name:'Colón'}],types:['Alojamientos','Gastronomía'],subtypes:[{id:'1',typeName:'Alojamientos',name:'Cabaña'},{id:'2',typeName:'Gastronomía',name:'Restaurante'}],contactChannels:['WhatsApp','Email'],templates:[],authorizedEmails:[],opportunityStages:[]};
  else if(url.pathname.endsWith('/commercial')){const id=url.searchParams.get('accountId');data={account:{...account,id,nombre:'Negocio '+id,assignedUserEmail:id==='2'?'other@example.com':'owner@example.com'},opportunities:id==='3'?[]:id==='2'?[{...management,id:'21',accountId:'2'}]:[management,otherManagement],contacts:[],journal:[],leadJournal:[],stages:[]};}
  else if(url.pathname.endsWith('/leads_quick')){const body=superjson.parse<any>(route.request().postData()!);mutations.push(body);if(body.field==='commercialProfile')await slow;if(body.scope==='management')Object.assign(management,{[body.field]:body.value});else Object.assign(account,{[body.field]:body.value,...(body.field==='tipo'?{subtipo:null}:{})});data={ok:true};}
  else if(url.pathname.endsWith('/leads'))data={rows:[1,2,3].map(id=>({...management,...account,id:String(id),accountId:String(id),nombre:'Negocio '+id,assignedUserEmail:id===2?'other@example.com':'owner@example.com',canModify:id!==2,opportunityCount:id===1?2:id===2?1:0,contactCount:0})),total:3,page:1,pageSize:50,filters:{ciudades:[],estados:[],tipos:[],asignados:[],suscripciones:[],origenes:['Facebook','Google Maps'],quienesCargaron:['Legacy','Owner'],mediosContacto:[],creadosPor:['Legacy','Owner']}};
  await route.fulfill({contentType:'application/json',body:superjson.stringify(data)});
 });
 await page.goto('/accounts');await page.getByRole('button',{name:'Editar vertical de Negocio 1',exact:true}).click();let popup=page.getByRole('dialog',{name:'Editar vertical',exact:true});
 await popup.getByRole('combobox').selectOption('Gastronomía');await expect(popup.getByText(/se quitará el subtipo/)).toContainText('Cabaña');await popup.getByRole('button',{name:'Cancelar',exact:true}).click();expect(mutations).toHaveLength(0);
 await page.getByRole('button',{name:'Editar vertical de Negocio 1',exact:true}).click();popup=page.getByRole('dialog',{name:'Editar vertical',exact:true});await popup.getByRole('combobox').selectOption('Gastronomía');await page.screenshot({path:`test-results/badge-classification-${width}.png`,animations:'disabled'});await popup.getByRole('button',{name:'Guardar',exact:true}).click();await expect(popup).toHaveCount(0);
 expect(mutations.at(-1)).toEqual({id:'1',accountId:'1',field:'tipo',value:'Gastronomía',expectedValue:'Alojamientos',scope:'business',expectedClassification:{tipo:'Alojamientos',subtipo:'Cabaña'}});
 await page.getByRole('button',{name:'Editar subtipo de Negocio 1',exact:true}).click();popup=page.getByRole('dialog',{name:'Editar subtipo',exact:true});await expect(popup.getByRole('option',{name:'Cabaña',exact:true})).toHaveCount(0);await popup.getByRole('combobox').selectOption('Restaurante');await popup.getByRole('button',{name:'Guardar',exact:true}).click();await expect(popup).toHaveCount(0);expect(mutations.at(-1).expectedClassification).toEqual({tipo:'Gastronomía',subtipo:null});
 for(const [field,title,value,expectedValue] of [['commercialProfile','perfil comercial','Referente','Independiente'],['medioContactoPreferido','medio preferido','WhatsApp','Email'],['origen','origen histórico','Google Maps','Facebook'],['quienCargo','quién cargó (histórico)','Owner','Legacy'],['creadoPor','creado por (histórico)','Owner','Legacy']]){
  await page.getByRole('button',{name:`Editar ${title} de Negocio 1`,exact:true}).click();popup=page.getByRole('dialog',{name:`Editar ${title}`,exact:true});await expect(popup.getByRole('button',{name:'Guardar',exact:true})).toHaveCount(0);await expect(popup.getByRole('combobox',{name:'Gestión a modificar',exact:true})).toHaveValue('');await expect(popup.getByRole('option',{name:/Gestión ajena/})).toBeDisabled();
  await popup.getByRole('combobox',{name:'Gestión a modificar',exact:true}).selectOption('11');await popup.getByRole('combobox',{name:`Nuevo valor de ${title}`,exact:true}).selectOption(value);if(field==='commercialProfile')await page.screenshot({path:`test-results/badge-management-${width}.png`,animations:'disabled'});await popup.getByRole('button',{name:'Guardar',exact:true}).click();if(field==='commercialProfile'){await expect(popup.getByRole('button',{name:'Guardando perfil comercial…',exact:true})).toBeDisabled();await expect(popup.getByRole('button',{name:'Cancelar',exact:true})).toBeDisabled();await expect.poll(()=>popup.evaluate(element=>element.scrollWidth-element.clientWidth)).toBe(0);await page.screenshot({path:`test-results/badge-management-saving-${width}.png`,animations:'disabled'});release();}await expect(popup).toHaveCount(0);expect(mutations.at(-1)).toEqual({id:'11',accountId:'1',scope:'management',field,value,expectedValue});
 }
 // Business ownership never overrides the independently assigned management owner.
 await expect(page.getByRole('button',{name:'Editar vertical de Negocio 2',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Editar perfil comercial de Negocio 2',exact:true}).click();popup=page.getByRole('dialog',{name:'Editar perfil comercial',exact:true});await expect(popup.getByRole('combobox')).toBeEnabled();await popup.getByRole('button',{name:'Cancelar',exact:true}).click();
 const count=mutations.length;await page.getByRole('button',{name:'Editar medio preferido de Negocio 3',exact:true}).click();popup=page.getByRole('dialog',{name:'Editar medio preferido',exact:true});await expect(popup.getByText(/Sin gestiones iniciadas/)).toBeVisible();await expect(popup.getByRole('button',{name:'Guardar',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');expect(mutations).toHaveLength(count);
 await page.getByRole('button',{name:'Grilla',exact:true}).click();await page.getByRole('button',{name:'Editar subtipo de Negocio 1',exact:true}).click();popup=page.getByRole('dialog',{name:'Editar subtipo',exact:true});await expect(popup.getByRole('combobox')).toHaveValue('Restaurante');await popup.getByRole('button',{name:'Cancelar',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
});
