import {test,expect} from '@playwright/test';import superjson from 'superjson';
test('audit followthrough: reviewed bulk scope, closing evidence, simple board and keyboard actions',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/\/my-day$/);
 async function api(endpoint:string,body?:unknown){const r=await page.evaluate(async({endpoint,body})=>{const r=await fetch('/_api/'+endpoint,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:{});return {status:r.status,text:await r.text()}},{endpoint,body:body?superjson.stringify(body):undefined});expect(r.status,r.text).toBe(200);return superjson.parse<any>(r.text)}
 const name='Revisión auditada '+Date.now();const accountId=(await api('commercial',{action:'account_save',nombre:name,assignedUserEmail:'admin@example.com'})).id;
 const lead=(await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Propuesta visible',estado:'Cargado'})).id;
 await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Otra propuesta del negocio',estado:'Cargado'});
 await page.goto('/accounts');await page.getByPlaceholder(/Buscar negocio/).fill(name);const row=page.getByRole('row').filter({has:page.getByText(name,{exact:true})});await expect(row).toHaveCount(1);await row.getByRole('checkbox').check();
 const bar=page.locator('section').filter({has:page.getByText('1 seleccionados',{exact:true})}).first();await bar.locator('select').first().selectOption('prioridad');await bar.locator('select').nth(1).selectOption('alta');await bar.getByRole('button',{name:'Aplicar',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Revisar cambios antes de aplicar'});await expect(dialog.getByText('2 ventas afectadas',{exact:false})).toBeVisible();await expect(dialog.getByText('Otra propuesta del negocio',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Confirmar cambios'})).toBeDisabled();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirmar cambios'}).click();await expect(dialog).toHaveCount(0);
 await page.goto('/sales/'+lead);await expect(page.getByRole('heading',{name:'Cómo avanzar con esta venta'})).toBeVisible();await page.getByText('2. Necesidad',{exact:true}).click();await expect(page.getByText(/Escuchá qué necesita/)).toBeVisible();
 await page.getByRole('button',{name:'Más acciones de la venta'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('menuitem',{name:'Enviar venta a papelera'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Más acciones de la venta'})).toBeFocused();
 const config=await api('pipeline?mode=config');await page.getByRole('button',{name:'Cambiar etapa',exact:true}).click();dialog=page.getByRole('dialog',{name:'Cambiar etapa'});await dialog.getByRole('combobox',{name:'Etapa',exact:true}).selectOption(config.stages.find((s:any)=>s.active&&s.classification==='won').name);await dialog.getByLabel('Qué se acordó',{exact:true}).fill('Publicación y acompañamiento durante enero');await dialog.getByLabel('Persona que aceptó').fill('Ana');await dialog.getByLabel('Propuesta o material acordado').fill('Propuesta versión aprobada');await dialog.getByLabel('Fecha acordada de entrega').fill('2027-01-18');await dialog.getByLabel('Revisamos qué se entrega').check();await dialog.getByRole('button',{name:'Guardar',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByText('Historial del pipeline · últimos 200 eventos',{exact:true}).click();await expect(page.getByText('Publicación y acompañamiento durante enero',{exact:true})).toBeVisible();
 await page.goto('/opportunities');await page.getByRole('button',{name:'Ver por etapas',exact:true}).click();await page.getByRole('button',{name:'Vista simple: abiertas, ganadas y perdidas'}).click();await expect(page.getByRole('heading',{name:/^Ganada/})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'test-results/audit-followthrough-mobile.png',fullPage:true});expect(errors).toEqual([]);
});
