import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {basePreferences} from '../../src/helpers/businessListPreferences';
test('team defaults initialize new preferences and personal values take priority',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/my-day$/);
 const before=superjson.parse<any>(await page.evaluate(async()=>(await fetch('/_api/business_list_defaults')).text()));
 try{
  await page.goto('/settings?section=businesses');await expect(page.getByRole('heading',{name:'Listado inicial de negocios',exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Presentación inicial',exact:true}).selectOption('grid');await page.getByRole('combobox',{name:'Cantidad inicial de resultados',exact:true}).selectOption('10');await page.getByRole('button',{name:'Guardar valores del equipo',exact:true}).click();await expect(page.getByText('Valores iniciales del equipo guardados',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();await expect(page.getByRole('button',{name:'Grilla',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('combobox',{name:'Resultados por página o lote'})).toHaveValue('10');await page.getByRole('button',{name:'Tabla',exact:true}).click();await page.getByRole('combobox',{name:'Resultados por página o lote'}).selectOption('25');
  await page.goto('/settings?section=businesses');await page.getByRole('combobox',{name:'Cantidad inicial de resultados',exact:true}).selectOption('100');await page.getByRole('button',{name:'Guardar valores del equipo',exact:true}).click();await expect(page.getByText('Valores iniciales del equipo guardados',{exact:true})).toBeVisible();await page.getByRole('link',{name:'Negocios',exact:true}).click();await expect(page.getByRole('combobox',{name:'Resultados por página o lote'})).toHaveValue('25');await expect(page.getByRole('button',{name:'Tabla',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Restablecer valores del equipo',exact:true}).click();await expect(page.getByRole('combobox',{name:'Resultados por página o lote'})).toHaveValue('100');await expect(page.getByRole('button',{name:'Grilla',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByLabel('Buscar negocios',{exact:true}).fill('Colón');await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click();await expect(page.getByLabel('Buscar negocios',{exact:true})).toHaveValue('');await expect(page.getByRole('combobox',{name:'Resultados por página o lote'})).toHaveValue('100');
 }finally{const defaults=before.defaults??{preferences:basePreferences(),presets:[],initialPresetId:null};const status=await page.evaluate(async body=>(await fetch('/_api/business_list_defaults',{method:'POST',body})).status,superjson.stringify(defaults));expect(status).toBe(200);}
});
