import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {basePreferences} from '../../src/helpers/businessListPreferences';
test('team defaults initialize new preferences and personal values take priority',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/my-day$/);
 const before=superjson.parse<any>(await page.evaluate(async()=>(await fetch('/_api/business_list_defaults')).text()));
 try{
  await page.goto('/settings?section=businesses');await expect(page.getByRole('heading',{name:'Configuraciones por defecto del listado',exact:true})).toBeVisible();await expect(page.getByRole('combobox',{name:'Forma inicial de carga'})).toHaveCount(0);await page.getByRole('textbox',{name:'Nombre de vista mine',exact:true}).fill('Mis establecimientos');await page.getByRole('checkbox',{name:'Mostrar vista today',exact:true}).uncheck();await page.getByRole('button',{name:'Subir vista mine',exact:true}).click();await page.getByRole('combobox',{name:'Presentación inicial',exact:true}).selectOption('grid');await expect(page.getByRole('combobox',{name:'Cantidad inicial de resultados',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Guardar configuraciones por defecto',exact:true}).click();await expect(page.getByText('Configuraciones por defecto guardadas',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();const systemOptions=page.getByRole('combobox',{name:'Vistas guardadas',exact:true}).locator('optgroup[label="Vistas del sistema"] option');await expect(systemOptions).toHaveCount(5);await expect(systemOptions.first()).toHaveText('Mis establecimientos');await expect(page.getByRole('button',{name:'Grilla',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('combobox',{name:'Resultados por lote'})).toHaveCount(0);await page.getByRole('button',{name:'Tabla',exact:true}).click();const saved=superjson.parse<any>(await page.evaluate(async()=>(await fetch('/_api/business_list_defaults')).text()));expect(saved.defaults.preferences.pageSize).toBe(50);
  await page.goto('/settings?section=businesses');await page.getByRole('combobox',{name:'Presentación inicial',exact:true}).selectOption('grid');await page.getByRole('button',{name:'Guardar configuraciones por defecto',exact:true}).click();await expect(page.getByText('Configuraciones por defecto guardadas',{exact:true})).toBeVisible();await page.getByRole('link',{name:'Negocios',exact:true}).click();await expect(page.getByRole('combobox',{name:'Resultados por lote'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Tabla',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Restablecer configuraciones por defecto',exact:true}).click();await expect(page.getByRole('combobox',{name:'Resultados por lote'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Grilla',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByLabel('Buscar negocios',{exact:true}).fill('Colón');await page.getByRole('button',{name:'Limpiar',exact:true}).click();await expect(page.getByLabel('Buscar negocios',{exact:true})).toHaveValue('');await expect(page.getByRole('combobox',{name:'Resultados por lote'})).toHaveCount(0);
 }finally{const defaults=before.defaults??{preferences:basePreferences(),presets:[],initialPresetId:null};const status=await page.evaluate(async body=>(await fetch('/_api/business_list_defaults',{method:'POST',body})).status,superjson.stringify(defaults));expect(status).toBe(200);}
});
