import {test,expect} from '@playwright/test';
import superjson from 'superjson';
for(const width of [1280,390])test(`business list preferences, restoration and loading at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});
 let userId=3;const rows=Array.from({length:65},(_,i)=>({id:String(-i-1),accountId:String(i+1),nombre:'Negocio '+String(i+1).padStart(2,'0'),ciudad:'Colón',assignedUserEmail:'owner@example.com',telefono:'123',email:'fixture@example.com',canModify:false,opportunityCount:0,contactCount:0,fechaProximaAccion:new Date('2026-11-01T00:00:00Z'),nextActionTitle:'Llamar'}));
 let gate:Promise<void>|null=null;let fail=false;
 await page.route('**/_api/**',async route=>{const url=new URL(route.request().url());let data:unknown={};if(url.pathname.endsWith('/auth/session'))data={user:{id:userId,email:'viewer@example.com',displayName:'Viewer',role:'user'}};
 else if(url.pathname.endsWith('/business_list_defaults'))data={defaults:null};
 else if(url.pathname.endsWith('/settings'))data={users:[],cities:[],types:[],templates:[],subtypes:[],authorizedEmails:[],opportunityStages:[]};
 else if(url.pathname.endsWith('/leads')){if(fail){await route.fulfill({status:500,body:superjson.stringify({error:'Fallo simulado'})});return;}if(gate)await gate;const page=Number(url.searchParams.get('page')??1),size=Number(url.searchParams.get('pageSize')??25);data={rows:rows.slice((page-1)*size,page*size),total:rows.length,page,pageSize:size,filters:{ciudades:['Colón'],estados:[],tipos:[],asignados:[],suscripciones:[],origenes:[],quienesCargaron:[],mediosContacto:[],creadosPor:[]}};}
 else if(url.pathname.endsWith('/saved_views'))data={views:[]};
 else if(url.pathname.endsWith('/commercial'))data={account:{id:url.searchParams.get('accountId'),nombre:'Ficha para volver',assignedUserEmail:'owner@example.com',archivedAt:null,mergedIntoId:null,commercialStatus:'prospect'},contacts:[],opportunities:[],journal:[],leadJournal:[],stages:[],users:[]};
 else if(url.pathname.endsWith('/work'))data={tasks:[],activities:[],attention:[],accounts:[],opportunities:[],types:[],users:[],followup:{stages:[],newAssignmentDays:7}};
 else if(url.pathname.endsWith('/pipeline'))data={stages:[],insights:[],events:[],objections:[],lossReasons:[],objectionTypes:[],rules:[],users:[],verticals:[]};
 else if(url.pathname.endsWith('/resources'))data={documents:[],categories:[],maxDocumentBytes:2097152};
 await route.fulfill({status:200,contentType:'application/json',body:superjson.stringify(data)});
 });
 await page.goto('/accounts');await expect(page.getByRole('button',{name:width===390?'Grilla':'Tabla',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('combobox',{name:'Resultados por página o lote'}).selectOption('10');await page.getByRole('button',{name:'Siguiente',exact:true}).click();await expect(page.getByText('Página 2 de 7')).toBeVisible();
 await page.getByRole('button',{name:'Grilla',exact:true}).click();let target=page.locator('[data-business-id="15"]');await target.scrollIntoViewIfNeeded();await expect(target.getByText(/^Llamar · 1 nov 2026$/)).toBeVisible();await target.getByRole('button',{name:'Abrir',exact:true}).click();await expect(page).toHaveURL(/accounts\/15$/);const top=await page.evaluate(()=>JSON.parse(localStorage.getItem('hospeda-business-list-v1-user-3')!).context.anchorOffset as number);
 await page.getByRole('link',{name:'← Volver al listado de negocios',exact:true}).click();target=page.locator('[data-business-id="15"]');await expect(target).toBeVisible();await expect(page.getByText('Página 2 de 7')).toBeVisible();await expect.poll(async()=>Math.abs(await target.evaluate(e=>e.getBoundingClientRect().top)-top)).toBeLessThan(10);
 await page.getByRole('button',{name:'Tabla',exact:true}).click();await page.getByText('Campos, orden y columnas fijas',{exact:true}).click();await page.getByRole('combobox',{name:'Fijar Nombre',exact:true}).selectOption('left');await page.getByText('Campos, orden y columnas fijas',{exact:true}).click();await expect(page.locator('tbody tr').first().locator('td').nth(1)).toHaveCSS('position',width===390?'static':'sticky');
 let release!:()=>void;gate=new Promise<void>(r=>release=r);await page.getByLabel('Buscar negocios',{exact:true}).fill('Colón');await expect(page.getByRole('status').filter({hasText:'Cargando negocios…'})).toBeVisible();await expect(page.locator('tbody [data-business-id]')).toHaveCount(0);await expect(page.getByRole('columnheader',{name:/Nombre/})).toBeVisible();release();gate=null;await expect(page.getByRole('status').filter({hasText:'10 de 65'})).toBeVisible();
 await page.getByRole('combobox',{name:'Forma de carga'}).selectOption('continuous');await expect(page.locator('[data-business-id="1"]')).toBeVisible();await page.getByRole('button',{name:'Cargar más',exact:true}).scrollIntoViewIfNeeded();await expect(page.locator('[data-business-id="20"]')).toBeVisible();
 target=page.locator('[data-business-id="15"]');await target.scrollIntoViewIfNeeded();await expect(target.getByText(/^Llamar · 1 nov 2026$/)).toBeVisible();await target.getByRole('button',{name:'Abrir',exact:true}).click();await page.goBack();await expect(page.locator('[data-business-id="15"]')).toBeVisible();await expect(page.getByLabel('Buscar negocios',{exact:true})).toHaveValue('Colón');target=page.locator('[data-business-id="15"]');await target.getByRole('button',{name:'Abrir',exact:true}).click();await page.getByRole('link',{name:'Negocios',exact:true}).click();await expect(page.locator('[data-business-id="15"]')).toBeVisible();
 await page.getByRole('button',{name:'Grilla',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:`test-results/business-list-${width}.png`,fullPage:true});
 fail=true;await page.getByLabel('Buscar negocios',{exact:true}).fill('Texto conservado');await expect(page.getByRole('alert').filter({hasText:'Fallo simulado'})).toBeVisible();await expect(page.getByLabel('Buscar negocios',{exact:true})).toHaveValue('Texto conservado');fail=false;await page.getByRole('button',{name:'Reintentar',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Fallo simulado'})).toHaveCount(0);
 userId=4;await page.goto('/login');await page.goto('/accounts');await expect(page.getByLabel('Buscar negocios',{exact:true})).toHaveValue('');await expect(page.getByRole('combobox',{name:'Resultados por página o lote'})).toHaveValue('25');
});
