import {test,expect} from '@playwright/test';
import superjson from 'superjson';
for(const width of [1280,390])test(`business continuity and explicit contact at ${width}px`,async({page})=>{
 test.setTimeout(180000);await page.setViewportSize({width,height:844});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/my-day$/);
 async function api(endpoint:string,body?:unknown){const result=await page.evaluate(async({endpoint,body})=>{const r=await fetch('/_api/'+endpoint,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:{});return {status:r.status,text:await r.text()}},{endpoint,body:body?superjson.stringify(body):undefined});expect(result.status,result.text).toBe(200);return superjson.parse<any>(result.text);}
 const accountId=(await api('commercial',{action:'account_save',nombre:'Contacto claro '+width+' '+Date.now(),email:'business@example.com',assignedUserEmail:'admin@example.com'})).id;
 await page.goto('/accounts/'+accountId);await expect(page.getByText('Sin próximo paso programado.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Última conversación o acción'})).toBeVisible();await expect(page.getByRole('tab',{name:'Gestiones comerciales (0)',exact:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('tab',{name:'Datos del negocio',exact:true}).click();await expect(page.getByText('business@example.com',{exact:true}).last()).toBeVisible();await expect(page.getByText('Sin próximo paso programado.',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Contactos (0)',exact:true}).click();await expect(page.getByRole('heading',{name:'Última conversación o acción'})).toBeVisible();
 await page.getByRole('button',{name:'Contactar',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByText(/Sin gestiones abiertas/)).toBeVisible();await dialog.getByRole('button',{name:'Cancelar',exact:true}).click();expect((await api('commercial?accountId='+accountId)).opportunities).toHaveLength(0);
 await page.getByRole('button',{name:'Contactar',exact:true}).click();await page.getByRole('button',{name:'Preparar gestión para contactar',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Nombre de la gestión')).toHaveValue('Presentación de Hospeda');await dialog.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByRole('button',{name:'Cancelar',exact:true}).click();expect((await api('commercial?accountId='+accountId)).opportunities).toHaveLength(0);
 await page.getByRole('button',{name:'Contactar',exact:true}).click();await page.getByRole('button',{name:'Preparar gestión para contactar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('Presentación de Hospeda',{exact:true})).toBeVisible();const detail=await api('commercial?accountId='+accountId);expect(detail.opportunities).toHaveLength(1);expect(detail.contacts).toHaveLength(0);const leadId=detail.opportunities[0].id;
 await dialog.getByRole('combobox',{name:'Canal',exact:true}).selectOption('email');await dialog.getByRole('button',{name:'Continuar con el mensaje',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'Destinatario',exact:true})).toHaveValue('');await expect(dialog.getByText('business@example.com',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Escribir un mensaje nuevo',exact:true}).click();await expect(dialog.getByRole('textbox',{name:'Asunto final'})).toBeVisible();expect((await api('communication?leadId='+leadId)).messages[0].recipient).toBe('business@example.com');await dialog.getByRole('button',{name:'Cerrar',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();
 await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Otra propuesta',estado:'Cargado'});const config=await api('pipeline?mode=config');const closed=config.stages.find((stage:any)=>stage.active&&stage.classification==='lost');expect(closed).toBeTruthy();const closedFixture=await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Gestión cerrada conservada',estado:'Cargado'});const pipeline=await api('pipeline?leadId='+closedFixture.id);const reason=pipeline.lossReasons.find((item:any)=>item.active);expect(reason).toBeTruthy();await api('pipeline',{action:'transition',leadId:closedFixture.id,revision:pipeline.insights[0].pipelineRevision,stage:closed.name,reasonId:reason.id,comment:'Fixture de gestión cerrada',recontactDate:null});await page.reload();await page.getByRole('button',{name:'Contactar',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'Gestión abierta',exact:true})).toHaveValue('');await dialog.getByRole('combobox',{name:'Gestión abierta',exact:true}).click();await expect(dialog.getByRole('listbox',{name:'Gestión abierta',exact:true}).getByRole('option')).toHaveCount(2);await expect(dialog.getByRole('listbox',{name:'Gestión abierta',exact:true}).getByRole('option',{name:/Gestión cerrada conservada/})).toHaveCount(0);await page.keyboard.press('Escape');await expect(dialog.getByRole('button',{name:'Continuar con el mensaje',exact:true})).toBeDisabled();await dialog.getByRole('combobox',{name:'Gestión abierta',exact:true}).click();await dialog.getByRole('listbox',{name:'Gestión abierta',exact:true}).getByRole('option',{name:/^Presentación de Hospeda/}).click();await dialog.getByRole('combobox',{name:'Canal',exact:true}).selectOption('whatsapp');await dialog.getByRole('button',{name:'Continuar con el mensaje',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Agregar teléfono o email',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Escribir un mensaje nuevo',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Cerrar',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:`test-results/business-contact-${width}.png`,fullPage:true});expect(errors).toEqual([]);
});
