import {test, expect} from '@playwright/test';

test('Classification catalogs stay focused and commercial settings have their own section', async ({page}) => {
  await page.addInitScript(() => localStorage.setItem('hospeda-live-mode', 'off'));
  await page.setViewportSize({width: 1440, height: 1000});
  await page.goto('/login');
  await page.getByLabel('Email', {exact: true}).fill('admin@example.com');
  await page.getByLabel('Contraseña', {exact: true}).fill('test-password-123');
  await page.getByRole('button', {name: 'Ingresar', exact: true}).click();
  await expect(page).toHaveURL(/\/my-day$/);
  await page.goto('/settings?section=classifications');
  await expect(page.getByRole('heading', {name: 'Clasificaciones de negocios'})).toBeVisible();
  await expect(page.getByRole('heading', {name: 'Tipos de tareas y actividades'})).toHaveCount(0);
  await expect(page.getByRole('heading', {name: 'Etapas y resultados de gestión'})).toHaveCount(0);
  const name = 'Subtipo prueba ' + Date.now();
  await page.getByLabel('Nuevo subtipo', {exact: true}).fill(name);
  await page.getByRole('button', {name: 'Agregar subtipo', exact: true}).click();
  await expect(page.getByRole('button', {name: 'Editar ' + name, exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'Editar ' + name, exact: true}).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nombre del subtipo').fill(name + ' editado');
  await dialog.getByRole('button', {name: 'Guardar cambios'}).click();
  await expect(dialog).toHaveCount(0);
  await page.getByLabel(/^Buscar en /).fill(name + ' editado');
  await expect(page.getByRole('button', {name: 'Editar ' + name + ' editado', exact: true})).toBeVisible();
  await page.screenshot({path: 'test-results/classifications-populated.png', fullPage: true});
  await page.getByRole('button', {name: 'Eliminar ' + name + ' editado', exact: true}).click();
  await dialog.getByRole('button', {name: 'Cancelar'}).click();
  await expect(page.getByRole('button', {name: 'Editar ' + name + ' editado', exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'Eliminar ' + name + ' editado', exact: true}).click();
  await dialog.getByRole('button', {name: 'Eliminar subtipo', exact: true}).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('button', {name: 'Editar ' + name + ' editado', exact: true})).toHaveCount(0);
  await page.getByLabel(/^Buscar en /).fill('');
  await page.screenshot({path: 'test-results/classifications-desktop.png', fullPage: true});
  await page.getByRole('tab', {name: 'Ciudades', exact: true}).click();
  const city = 'Ciudad prueba ' + Date.now();
  await page.getByLabel('Nueva ciudad', {exact: true}).fill(city);
  await page.getByRole('button', {name: 'Agregar ciudad'}).click();
  await expect(page.getByRole('tabpanel').getByText(city, {exact: true})).toBeVisible();
  await page.getByLabel('Buscar ciudad').fill('no existe esta localidad');
  await expect(page.getByText('No hay ciudades que coincidan con la búsqueda.')).toBeVisible();
  await page.getByLabel('Buscar ciudad').fill('');
  await page.getByRole('tab', {name: 'Verticales y subtipos'}).click();
  await page.setViewportSize({width: 390, height: 844});
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path: 'test-results/classifications-mobile.png', fullPage: true});
  await page.addStyleTag({content: '*,*::before,*::after{transition:none!important}'});
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await expect.poll(() => page.getByLabel('Nuevo subtipo', {exact: true}).evaluate(el => parseInt(getComputedStyle(el).backgroundColor.match(/[\d.]+/)![0]))).toBeLessThan(50);
  await page.screenshot({path: 'test-results/classifications-dark-mobile.png', fullPage: true});
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await page.getByRole('combobox', {name: 'Sección de configuración', exact: true}).selectOption('process');
  await expect(page).toHaveURL(/section=process/);
  await expect(page.getByRole('heading', {name: 'Etapas y resultados de gestión'})).toBeVisible();
  await expect(page.getByRole('heading', {name: 'Tipos de tareas y actividades'})).toHaveCount(0);
  await page.getByRole('tab', {name: 'Tareas y seguimiento'}).click();
  await expect(page.getByRole('heading', {name: 'Tipos de tareas y actividades'})).toBeVisible();
  await expect(page.getByRole('heading', {name: 'Etapas y resultados de gestión'})).toHaveCount(0);
});
