import {test,expect} from '@playwright/test';

test('account with two contacts and independent opportunities preserves lead and communication flows',async({page})=>{
  test.setTimeout(180000);
  await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
  await page.goto('/login');
  await page.getByLabel('Email',{exact:true}).fill('admin@example.com');
  await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');
  await page.getByRole('button',{name:'Ingresar',exact:true}).click();
  await expect(page).toHaveURL(/\/my-day$/);await page.goto("/accounts");
  await expect(page.getByRole('heading',{name:'Negocios',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Negocios',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await page.getByRole('button',{name:'Nuevo negocio',exact:true}).click();
  await page.getByLabel('Negocio',{exact:true}).fill('Negocio E2E');
  await page.getByText('Teléfono, email y enlaces (opcional)',{exact:true}).click();await page.getByLabel('Email genérico').fill('negocio@example.com');
  await page.getByLabel('Ciudad',{exact:true}).fill('Colón');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Negocio E2E',exact:true})).toBeVisible();
  const accountUrl=page.url();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await expect(page.getByRole('row').filter({has:page.getByRole('button',{name:'Negocio E2E',exact:true})})).toHaveCount(1);
  await page.getByRole('button',{name:'Negocio E2E',exact:true}).click();
  await page.getByRole('tab',{name:'Contactos (0)',exact:true}).click();
  for(const person of ['Ana','Luis']){
    await page.getByRole('button',{name:'Agregar contacto',exact:true}).click();
    await page.getByLabel('Nombre de la persona').fill(person);
    await page.getByRole('combobox',{name:'Cargo',exact:true}).selectOption({label:'Propietario/a'});
    await page.getByRole('combobox',{name:'Canal preferido',exact:true}).selectOption({label:'WhatsApp'});
    await page.getByLabel('Email',{exact:true}).fill(person.toLowerCase()+'@example.com');
    await page.getByLabel('Teléfono',{exact:true}).fill(person==='Ana'?'5493442000001':'5493442000002');
    if(person==='Luis')await page.getByLabel('Principal del negocio').check();
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Personas de contacto (2)',exact:true})).toBeVisible();
  await expect(page.getByText('Luis · Principal',{exact:true})).toBeVisible();
  await page.locator('article').filter({has:page.getByText('Ana',{exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Cargo',exact:true})).toHaveValue('Propietario/a');
  await expect(page.getByRole('combobox',{name:'Canal preferido',exact:true})).toHaveValue('WhatsApp');
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  await expect(page.getByText('Ana · Principal',{exact:true})).toHaveCount(0);
  await page.getByRole('tab',{name:/^Gestiones comerciales/}).click();
  for(const [name,stage,person] of [['Primera gestión','Cargado','Ana'],['Segunda gestión','En tratativas','Luis']]){
    await page.getByRole('button',{name:'Iniciar gestión',exact:true}).click();
    await page.getByLabel('Nombre de la gestión').fill(name);
    await page.getByLabel('Cierre estimado',{exact:true}).fill('2027-01-15');
    await page.getByRole('combobox',{name:'Tipo de negocio',exact:true}).selectOption({label:'Alojamiento'});
    await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:stage});
    await page.getByRole('combobox',{name:'Contacto principal de gestión',exact:true}).selectOption({label:person});
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Gestiones comerciales (2)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Más acciones del negocio',exact:true}).click();await page.getByRole('menuitem',{name:'Convertir a cliente',exact:true}).click();
  await page.getByLabel('Motivo de conversión').fill('Acuerdo comercial E2E');
  await page.getByRole('dialog').getByRole('button',{name:'Convertir a cliente',exact:true}).click();
  await expect(page.getByText(/· Cliente ·/)).toBeVisible();
  await page.getByRole('tab',{name:'Historial',exact:true}).click();
  await page.getByRole('button',{name:'Auditoría de cambios de datos',exact:true}).click();
  await expect(page.getByText(/Conversión a cliente/)).toBeVisible();
  await page.getByRole('tab',{name:/^Gestiones comerciales/}).click();
  await page.screenshot({path:'test-results/commercial-light.png',fullPage:true});
  await page.getByRole('button',{name:'Admin Test',exact:true}).click();
  await page.getByRole('menuitem',{name:'Tema oscuro'}).click();
  await page.screenshot({path:'test-results/commercial-dark.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'test-results/commercial-mobile.png',fullPage:true});
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('link',{name:'Primera gestión',exact:true}).click();
  const lead=page.locator('main');
  await expect(lead.getByRole('button',{name:'Editar negocio',exact:true})).not.toBeVisible();
  await lead.getByText('Negocio, personas y otras gestiones',{exact:true}).click();
  await expect(lead.getByRole('button',{name:'Editar negocio',exact:true})).toBeVisible();
  await lead.getByText('Contactos del negocio (2)',{exact:true}).click();
  await lead.getByText('Gestiones comerciales de este negocio (2)',{exact:true}).click();
  await expect(lead.getByRole('heading',{name:'Contacto',exact:true})).toHaveCount(0);
  await expect(lead.getByText('La gestión abierta está marcada como Actual.',{exact:false})).toBeVisible();
  await page.screenshot({path:'test-results/lead-commercial-detail.png',fullPage:true,animations:'disabled'});
  await expect(lead.getByRole('heading',{name:'Primera gestión',exact:true})).toBeVisible();
  await expect(lead.getByText('Cargado',{exact:true}).first()).toBeVisible();
  await lead.getByText('Otras acciones',{exact:true}).click();await lead.getByRole('button',{name:'Contactar ahora',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Preparar email con un mensaje modelo',exact:true}).click();
  const communication=page.getByRole('dialog').last();
  await expect(communication.getByRole('combobox',{name:'Destinatario',exact:true})).toHaveValue(/\d+/);
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByLabel('Asunto final')).toHaveValue('Hola Luis');
  await communication.getByRole('button',{name:'Cambiar destinatario o modelo'}).click();
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Canal general del negocio'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByLabel('Asunto final')).toHaveValue('Hola');
  await communication.getByRole('button',{name:'Cerrar',exact:true}).first().click();
  // Capture WhatsApp intent locally: this test never opens or sends a real message.
  await page.evaluate(()=>{window.open=(url)=>{(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl=String(url);return null}});
  await page.getByRole('dialog').getByRole('button',{name:'Preparar WhatsApp con un mensaje modelo',exact:true}).click();
  const whatsapp=page.getByRole('dialog').last();
  await whatsapp.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await whatsapp.getByRole('button',{name:/CRM WhatsApp template/}).click();
  await whatsapp.getByRole('button',{name:'Guardar y ver contenido final'}).click();
  await whatsapp.getByLabel('Revisé destinatario y contenido final').check();
  await whatsapp.getByRole('button',{name:'Abrir WhatsApp con este mensaje'}).click();
  await expect(whatsapp.getByRole('button',{name:'Confirmar envío manual'})).toBeVisible();
  const intent=await page.evaluate(()=>(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl);
  const whatsappUrl=new URL(intent);
  expect(whatsappUrl.pathname).toBe('/5493442000002');
  expect(whatsappUrl.searchParams.get('text')).toContain('Hola Luis luis@example.com');
  await whatsapp.getByRole('button',{name:'Confirmar envío manual',exact:true}).click();
  await expect(whatsapp.getByText('Envío confirmado manualmente',{exact:true})).toBeVisible();
  await whatsapp.getByRole('button',{name:'Cerrar',exact:true}).first().click();
  await page.getByRole('dialog').getByRole('button',{name:'Volver',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  await lead.getByRole('button',{name:'Editar datos de gestión',exact:true}).first().click();
  await expect(page.getByLabel('Nombre / razón social',{exact:true})).toHaveCount(0);
  await expect(page.getByLabel('Teléfono genérico',{exact:true})).toHaveCount(0);
  await page.getByLabel('Nombre de gestión',{exact:true}).fill('Primera gestión actualizada');
  await page.getByRole('button',{name:'Guardar gestión',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto(accountUrl);await page.getByRole('tab',{name:/^Gestiones comerciales/}).click();
  const row=page.locator('article').filter({has:page.getByRole('link',{name:'Primera gestión actualizada',exact:true})});
  await row.getByRole('button',{name:'Editar datos de gestión',exact:true}).click();
  await expect(page.getByLabel('Cierre estimado',{exact:true})).toHaveValue('2027-01-15');
  await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:'1er contacto'});
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(row.getByText(/1er contacto/)).toBeVisible();
  await expect(page.locator('article').filter({has:page.getByRole('link',{name:'Segunda gestión',exact:true})}).getByText(/En tratativas/)).toBeVisible();
  await page.getByRole('tab',{name:/^Contactos/}).click();
  const contact=page.locator('article').filter({has:page.getByText('Ana',{exact:true})});
  await contact.getByRole('button',{name:'Dar de baja',exact:true}).click();
  await page.getByRole('button',{name:'Confirmar baja',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Personas de contacto (1)',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Historial',exact:true}).click();
  await page.getByRole('button',{name:'Auditoría de cambios de datos',exact:true}).click();
  await expect(page.getByText(/Contacto dado de baja/)).toBeVisible();
  await page.getByText('Ayuda sobre negocios y gestiones',{exact:true}).click();await page.getByText('Cómo usar negocios, contactos y gestiones',{exact:true}).click();
  await expect(page.getByText(/Su etapa indica cómo avanza esa gestión/)).toBeVisible();
  await page.getByRole('link',{name:'Gestiones comerciales',exact:true}).click();
  await page.getByRole('button',{name:'Iniciar gestión',exact:true}).click();
  await page.getByLabel('Buscar negocio',{exact:true}).fill('Negocio E2E');
  await page.getByRole('button',{name:/Negocio E2E.*Elegir/}).click();
  await page.getByLabel('Nombre de la gestión',{exact:true}).fill('Tercera gestión');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Tercera gestión',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'← Volver a Gestiones comerciales',exact:true}).click();
  await page.goto(accountUrl);await page.getByRole('tab',{name:/^Gestiones comerciales/}).click();
  await expect(page.getByRole('heading',{name:'Gestiones comerciales (3)',exact:true})).toBeVisible();
  const legacyOpportunityUrl=(await page.getByRole('link',{name:'Tercera gestión',exact:true}).getAttribute('href'))!.replace(/^\/sales\/(\d+)$/, '/?leadId=$1');
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  const businessRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Negocio E2E',exact:true})});
  await expect(businessRow).toHaveCount(1);
  await expect(businessRow.getByText(/3 gestiones/)).toBeVisible();
  await expect(page.getByRole('button',{name:'Filtrar negocios',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Pantalla completa',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Vista avanzada',exact:true})).toHaveCount(0);
  await page.getByRole('textbox',{name:'Buscar negocios',exact:true}).fill('Negocio E2E');
  await expect(page.getByRole('row').filter({has:page.getByRole('button',{name:'Negocio E2E',exact:true})})).toHaveCount(1);
  await page.getByRole('button',{name:'Guardar como vista',exact:true}).click();
  await page.getByLabel('Nombre de la vista',{exact:true}).fill('Negocios E2E guardados');
  await page.getByRole('dialog').getByRole('button',{name:'Guardar vista',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Aplicar vista personal Negocios E2E guardados',exact:true})).toHaveCount(1);await page.getByRole('button',{name:'Aplicar vista personal Negocios E2E guardados',exact:true}).click();
  await page.screenshot({path:'test-results/business-first-list.png',fullPage:true,animations:'disabled'});
  await page.goto(legacyOpportunityUrl);
  await expect(page.getByRole('heading',{name:'Tercera gestión',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'← Volver a Gestiones comerciales',exact:true}).click();
  await page.goto('/?quick=all');
  await expect(page).toHaveURL(/\/accounts/);
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await page.getByRole('link',{name:'Gestiones comerciales',exact:true}).click();
  await page.getByRole('button',{name:'Iniciar gestión',exact:true}).click();
  await page.getByRole('button',{name:'Crear negocio nuevo',exact:true}).click();
  await page.getByLabel('Negocio',{exact:true}).fill('Otro negocio guiado');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await page.getByLabel('Nombre de la gestión',{exact:true}).fill('Primera gestión guiada');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Primera gestión guiada',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Otro negocio guiado',exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/opportunity-guided-detail.png',fullPage:true,animations:'disabled'});

});
