import {test,expect} from '@playwright/test';

test('account with two contacts and independent opportunities preserves lead and communication flows',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
  await page.goto('/login');
  await page.getByLabel('Email',{exact:true}).fill('admin@example.com');
  await page.getByLabel('Password',{exact:true}).fill('test-password-123');
  await page.getByRole('button',{name:'Log In',exact:true}).click();
  await expect(page.getByRole('link',{name:'Cuentas',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Cuentas',exact:true}).click();
  await page.getByRole('button',{name:'Nueva cuenta',exact:true}).click();
  await page.getByLabel('Negocio',{exact:true}).fill('Negocio E2E');
  await page.getByLabel('Email genérico').fill('negocio@example.com');
  await page.getByLabel('Ciudad',{exact:true}).fill('Colón');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Negocio E2E',exact:true})).toBeVisible();
  const accountUrl=page.url();
  for(const person of ['Ana','Luis']){
    await page.getByRole('button',{name:'Agregar contacto',exact:true}).click();
    await page.getByLabel('Nombre de la persona').fill(person);
    await page.getByLabel('Email',{exact:true}).fill(person.toLowerCase()+'@example.com');
    await page.getByLabel('Teléfono',{exact:true}).fill(person==='Ana'?'5493442000001':'5493442000002');
    if(person==='Luis')await page.getByLabel('Principal de la cuenta').check();
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Personas de contacto (2)',exact:true})).toBeVisible();
  await expect(page.getByText('Luis · Principal',{exact:true})).toBeVisible();
  await expect(page.getByText('Ana · Principal',{exact:true})).toHaveCount(0);
  for(const [name,stage,person] of [['Primera venta','Cargado','Ana'],['Segunda venta','En tratativas','Luis']]){
    await page.getByRole('button',{name:'Nueva oportunidad',exact:true}).click();
    await page.getByLabel('Nombre de oportunidad').fill(name);
    await page.getByRole('combobox',{name:'Vertical',exact:true}).selectOption({label:'Alojamiento'});
    await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:stage});
    await page.getByRole('combobox',{name:'Contacto principal de oportunidad',exact:true}).selectOption({label:person});
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Oportunidades (2)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Convertir a cliente',exact:true}).click();
  await page.getByLabel('Motivo de conversión').fill('Acuerdo comercial E2E');
  await page.getByRole('dialog').getByRole('button',{name:'Convertir a cliente',exact:true}).click();
  await expect(page.getByText(/Cliente comercial · no acredita pago/)).toBeVisible();
  await expect(page.getByText(/Convertida a cliente/)).toBeVisible();
  await page.screenshot({path:'test-results/commercial-light.png',fullPage:true});
  await page.getByRole('button',{name:'Admin Test',exact:true}).click();
  await page.getByRole('menuitem',{name:'Tema oscuro'}).click();
  await page.screenshot({path:'test-results/commercial-dark.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/commercial-mobile.png',fullPage:true});
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('link',{name:/Primera venta · #/}).click();
  const lead=page.getByRole('dialog').last();
  await expect(lead.getByRole('heading',{name:'Primera venta',exact:true})).toBeVisible();
  await expect(lead.getByText('Cargado',{exact:true}).first()).toBeVisible();
  await lead.getByRole('button',{name:'Email',exact:true}).click();
  const communication=page.getByRole('dialog').last();
  await expect(communication.getByRole('combobox',{name:'Destinatario',exact:true})).toHaveValue(/\d+/);
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByText('Hola Luis',{exact:true}).first()).toBeVisible();
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Datos genéricos / históricos del negocio'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByText('Hola',{exact:true}).first()).toBeVisible();
  await communication.getByRole('button',{name:'Cancelar',exact:true}).click();
  // Capture WhatsApp intent locally: this test never opens or sends a real message.
  await page.evaluate(()=>{window.open=(url)=>{(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl=String(url);return null}});
  await lead.getByRole('button',{name:'WhatsApp',exact:true}).click();
  const whatsapp=page.getByRole('dialog').last();
  await whatsapp.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await whatsapp.getByRole('button',{name:/CRM WhatsApp template/}).click();
  const intent=await page.evaluate(()=>(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl);
  const whatsappUrl=new URL(intent);
  expect(whatsappUrl.pathname).toBe('/5493442000002');
  expect(whatsappUrl.searchParams.get('text')).toContain('Hola Luis luis@example.com');
  await whatsapp.getByRole('button',{name:'Registrar resultado y cerrar',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(1);
  await lead.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.goto(accountUrl);
  const row=page.locator('article').filter({has:page.getByRole('link',{name:/Primera venta · #/})});
  await row.getByRole('button',{name:'Editar oportunidad',exact:true}).click();
  await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:'1er contacto'});
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(row.getByText(/1er contacto/)).toBeVisible();
  await expect(page.locator('article').filter({has:page.getByRole('link',{name:/Segunda venta · #/})}).getByText(/En tratativas/)).toBeVisible();
  const contact=page.locator('article').filter({has:page.getByText('Ana',{exact:true})});
  await contact.getByRole('button',{name:'Dar de baja',exact:true}).click();
  await page.getByRole('button',{name:'Confirmar baja',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Personas de contacto (1)',exact:true})).toBeVisible();
  await expect(page.getByText(/Contacto dado de baja/)).toBeVisible();
});
