import {test,expect} from '@playwright/test';
test('reviewed WhatsApp, assisted sequence, restriction and persistent resource approval',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Password',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Log In',exact:true}).click();await expect(page).toHaveURL(/accounts$/);
 const mutate=async(path:string,body:any)=>page.evaluate(async({path,body})=>{const serialized=JSON.stringify({json:body});const r=await fetch('/_api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:serialized});const d=await r.json();if(!r.ok)throw new Error(JSON.stringify(d));return d.json??d;},{path,body});
 // SuperJSON primitive-only envelopes; no real provider or WhatsApp is contacted.
 const stamp=Date.now(),name='Fase5 E2E '+stamp;const accountId=(await mutate('commercial',{action:'account_save',nombre:name,ciudad:'Colón',email:'fixture@example.com',telefono:'5493442000003',assignedUserEmail:'admin@example.com'})).id;
 const leadId=(await mutate('commercial',{action:'opportunity_save',accountId,opportunityName:'Seguimiento fase5',estado:'Cargado',assignedUserEmail:'admin@example.com'})).id;
 await page.addInitScript(()=>{window.open=(url)=>{(window as any).phase5WhatsApp=String(url);return null}});
 const m=await mutate('communication',{action:'prepare',id:crypto.randomUUID(),leadId,contactId:null,channel:'whatsapp',templateId:null});
 await page.goto('/opportunities?leadId='+leadId);let dialog=page.getByRole('dialog');await dialog.getByRole('tab',{name:'Comunicación',exact:true}).click();await dialog.getByText('Borrador · whatsapp',{exact:false}).click();await dialog.getByLabel('Mensaje final').fill('Hola mensaje revisado');await dialog.getByLabel('Mensaje final').press('ControlOrMeta+a');await dialog.getByRole('button',{name:'Negrita',exact:true}).click();await expect(dialog.getByLabel('Mensaje final').locator('strong')).toHaveText('Hola mensaje revisado');await expect(dialog.getByText('Insertar variable:')).toHaveCount(0);await page.screenshot({path:'test-results/whatsapp-tiptap-editor.png',fullPage:true});await dialog.getByRole('button',{name:'Guardar y ver contenido final'}).click();await expect(dialog.getByRole('button',{name:'Abrir WhatsApp con este mensaje'})).toBeDisabled();await expect(dialog.getByRole('heading',{name:'Revisá el contenido final'})).toBeVisible();await page.screenshot({path:'test-results/message-review.png',fullPage:true});const viewport=page.viewportSize()!;await page.evaluate(()=>document.body.classList.add('dark'));await page.screenshot({path:'test-results/message-review-dark.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:'test-results/message-review-mobile.png',fullPage:true});await page.setViewportSize(viewport);await page.evaluate(()=>document.body.classList.remove('dark'));await dialog.getByRole('button',{name:'Volver a editar'}).click();await expect(dialog.getByLabel('Mensaje final').locator('strong')).toHaveText('Hola mensaje revisado');await dialog.getByRole('button',{name:'Guardar y ver contenido final'}).click();await dialog.getByLabel('Revisé destinatario y contenido final').check();await dialog.getByRole('button',{name:'Abrir WhatsApp con este mensaje'}).click();await expect(dialog.getByRole('button',{name:'Confirmar envío manual'})).toBeVisible();expect(await page.evaluate(()=>new URL((window as any).phase5WhatsApp).searchParams.get('text'))).toBe('*Hola mensaje revisado*');await dialog.getByRole('button',{name:'Confirmar envío manual'}).click();await expect(dialog.getByText('Envío confirmado manualmente',{exact:true})).toBeVisible();
 await dialog.getByRole('tab',{name:'Resumen',exact:true}).click();await dialog.getByRole('button',{name:'Email',exact:true}).click();const emailDialog=page.getByRole('dialog').last();await expect(emailDialog.getByRole('status')).toContainText('whatsapp');await expect(emailDialog.getByRole('status')).toContainText('admin@example.com');await emailDialog.getByLabel('Buscar template').fill('sin-coincidencia-'+stamp);await expect(emailDialog.getByText('No hay templates que coincidan con la búsqueda.')).toBeVisible();await emailDialog.getByLabel('Buscar template').fill('');await page.screenshot({path:'test-results/message-template-selector.png',fullPage:true});await emailDialog.getByRole('button',{name:'Preparar sin template',exact:true}).click();await expect(emailDialog.getByText('Insertar variable:')).toHaveCount(0);await emailDialog.getByRole('button',{name:'Cambiar destinatario o template'}).click();await emailDialog.getByRole('button',{name:'Cerrar',exact:true}).click();await dialog.getByRole('tab',{name:'Comunicación',exact:true}).click();
 await dialog.getByText('Configurar secuencia',{exact:true}).click();await dialog.getByLabel('Nombre de secuencia').fill('Secuencia E2E '+stamp);await dialog.getByLabel('Alcance y uso previsto').fill('Seguimiento manual de fixture');await dialog.getByLabel('Canal del paso',{exact:true}).selectOption('whatsapp');await dialog.getByLabel('Template del paso',{exact:true}).selectOption({label:'CRM WhatsApp template'});await dialog.getByRole('button',{name:'Guardar secuencia'}).click();await expect(dialog.getByText('Secuencia E2E '+stamp+' · Activa',{exact:false})).toBeVisible();
 await dialog.getByText('Iniciar secuencia',{exact:true}).click();await dialog.getByLabel('Secuencia',{exact:true}).selectOption({label:'Secuencia E2E '+stamp});await dialog.getByLabel('Confirmo la generación de tareas y borradores').check();await dialog.getByRole('button',{name:'Iniciar seguimiento asistido'}).click();await expect(dialog.getByText('Secuencia E2E '+stamp+' · Activa',{exact:true})).toBeVisible();
 await dialog.getByText('Restricciones de contacto',{exact:true}).click();await dialog.getByLabel('Motivo de restricción').fill('Solicitud explícita fixture');await dialog.getByRole('button',{name:'Bloquear contacto/canal'}).click();await expect(dialog.getByText('all · No contactar',{exact:true})).toBeVisible();await expect(dialog.getByText('Secuencia E2E '+stamp+' · Detenida',{exact:true})).toBeVisible();
 await dialog.getByRole('tab',{name:'Documentos',exact:true}).click();await dialog.getByText('Agregar documento o recurso',{exact:true}).click();await dialog.getByLabel('Título del documento').fill('Propuesta '+stamp);await dialog.getByLabel('Vínculo HTTP(S)').fill('https://example.com/propuesta.pdf');await dialog.getByRole('button',{name:'Guardar documento',exact:true}).click();await expect(dialog.getByText('Propuesta '+stamp+' · Borrador',{exact:true})).toBeVisible();await page.goto('/settings?section=library');await page.getByText('Agregar documento o recurso',{exact:true}).click();await page.getByLabel('Título del documento').fill('Biblioteca '+stamp);await page.getByLabel('Vínculo HTTP(S)').fill('https://example.com/recurso.pdf');await page.getByRole('button',{name:'Guardar documento',exact:true}).click();await page.getByRole('article').filter({hasText:'Biblioteca '+stamp}).getByRole('button',{name:'Aprobar versión'}).click();
 await page.goto('/opportunities?leadId='+leadId);await page.getByRole('dialog').getByRole('tab',{name:'Documentos',exact:true}).click();await expect(page.getByRole('button',{name:'Vincular documento al negocio'})).toBeDisabled();await page.getByRole('combobox',{name:'Documento de biblioteca'}).click();await page.getByLabel('Buscar documento en biblioteca').fill('sin-documento-'+stamp);await expect(page.getByText('No hay documentos que coincidan.')).toBeVisible();await page.getByLabel('Buscar documento en biblioteca').fill('Biblioteca '+stamp);await page.getByRole('option',{name:new RegExp('Biblioteca '+stamp)}).click();await page.getByRole('button',{name:'Vincular documento al negocio'}).click();await expect(page.getByRole('dialog').getByText('Biblioteca '+stamp+' · Aprobado',{exact:true})).toBeVisible();await page.goto('/library');await page.getByLabel('Buscar recurso').fill('Biblioteca '+stamp);await expect(page.getByText('Biblioteca '+stamp+' · Aprobado',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/communication-resources-light.png',fullPage:true});await page.reload();await page.getByLabel('Buscar recurso').fill('Biblioteca '+stamp);await expect(page.getByText('Agregar documento o recurso',{exact:true})).toHaveCount(0);await page.screenshot({path:'test-results/communication-resources-dark.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/communication-resources-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
