import {test,expect} from '@playwright/test';

test('account with two contacts and independent opportunities preserves lead and communication flows',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
  await page.goto('/login');
  await page.getByLabel('Email',{exact:true}).fill('admin@example.com');
  await page.getByLabel('Password',{exact:true}).fill('test-password-123');
  await page.getByRole('button',{name:'Log In',exact:true}).click();
  await expect(page).toHaveURL(/\/accounts$/);
  await expect(page.getByRole('heading',{name:'Negocios',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Negocios',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await page.getByRole('button',{name:'Nuevo negocio',exact:true}).click();
  await page.getByLabel('Negocio',{exact:true}).fill('Negocio E2E');
  await page.getByLabel('Email genérico').fill('negocio@example.com');
  await page.getByLabel('Ciudad',{exact:true}).fill('Colón');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Negocio E2E',exact:true})).toBeVisible();
  const accountUrl=page.url();
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await expect(page.getByRole('row').filter({has:page.getByRole('button',{name:/Negocio E2E/})})).toHaveCount(1);
  await page.getByRole('button',{name:/Negocio E2E/}).click();
  await page.getByRole('tab',{name:'Contactos (0)',exact:true}).click();
  for(const person of ['Ana','Luis']){
    await page.getByRole('button',{name:'Agregar contacto',exact:true}).click();
    await page.getByLabel('Nombre de la persona').fill(person);
    await page.getByRole('combobox',{name:'Cargo',exact:true}).selectOption({label:'Propietario/a'});
    await page.getByRole('combobox',{name:'Canal preferido',exact:true}).selectOption({label:'WhatsApp'});
    await page.getByLabel('Email',{exact:true}).fill(person.toLowerCase()+'@example.com');
    await page.getByLabel('Teléfono',{exact:true}).fill(person==='Ana'?'5493442000001':'5493442000002');
    if(person==='Luis')await page.getByLabel('Principal del negocio').check();
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Personas de contacto (2)',exact:true})).toBeVisible();
  await expect(page.getByText('Luis · Principal',{exact:true})).toBeVisible();
  await page.locator('article').filter({has:page.getByText('Ana',{exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Cargo',exact:true})).toHaveValue('Propietario/a');
  await expect(page.getByRole('combobox',{name:'Canal preferido',exact:true})).toHaveValue('WhatsApp');
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  await expect(page.getByText('Ana · Principal',{exact:true})).toHaveCount(0);
  await page.getByRole('tab',{name:/^Oportunidades/}).click();
  for(const [name,stage,person] of [['Primera venta','Cargado','Ana'],['Segunda venta','En tratativas','Luis']]){
    await page.getByRole('button',{name:'Nueva oportunidad',exact:true}).click();
    await page.getByLabel('Nombre de oportunidad').fill(name);
    await page.getByLabel('Cierre estimado',{exact:true}).fill('2027-01-15');
    await page.getByRole('combobox',{name:'Vertical',exact:true}).selectOption({label:'Alojamiento'});
    await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:stage});
    await page.getByRole('combobox',{name:'Contacto principal de oportunidad',exact:true}).selectOption({label:person});
    await page.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  await expect(page.getByRole('heading',{name:'Oportunidades (2)',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Convertir a cliente',exact:true}).click();
  await page.getByLabel('Motivo de conversión').fill('Acuerdo comercial E2E');
  await page.getByRole('dialog').getByRole('button',{name:'Convertir a cliente',exact:true}).click();
  await expect(page.getByText(/Cliente comercial · no acredita pago/)).toBeVisible();
  await page.getByRole('tab',{name:'Historial',exact:true}).click();
  await expect(page.getByText(/Conversión a cliente/)).toBeVisible();
  await page.getByRole('tab',{name:/^Oportunidades/}).click();
  await page.screenshot({path:'test-results/commercial-light.png',fullPage:true});
  await page.getByRole('button',{name:'Admin Test',exact:true}).click();
  await page.getByRole('menuitem',{name:'Tema oscuro'}).click();
  await page.screenshot({path:'test-results/commercial-dark.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'test-results/commercial-mobile.png',fullPage:true});
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('link',{name:/Primera venta · #/}).click();
  const lead=page.getByRole('dialog').last();
  await expect(lead.getByRole('button',{name:'Editar negocio',exact:true})).toHaveCount(0);
  await lead.getByRole('tab',{name:'Negocio y contactos',exact:true}).click();
  await expect(lead.getByRole('button',{name:'Editar negocio',exact:true})).toBeVisible();
  await lead.getByText('Contactos del negocio (2)',{exact:true}).click();
  await lead.getByText('Ventas de este negocio (2)',{exact:true}).click();
  await expect(lead.getByRole('heading',{name:'Contacto',exact:true})).toHaveCount(0);
  await expect(lead.getByText('La oportunidad abierta está marcada como Actual.',{exact:false})).toBeVisible();
  await page.screenshot({path:'test-results/lead-commercial-detail.png',fullPage:true,animations:'disabled'});
  await expect(lead.getByRole('heading',{name:'Primera venta',exact:true})).toBeVisible();
  await expect(lead.getByText('Cargado',{exact:true}).first()).toBeVisible();
  await lead.getByRole('button',{name:'Email',exact:true}).click();
  const communication=page.getByRole('dialog').last();
  await expect(communication.getByRole('combobox',{name:'Destinatario',exact:true})).toHaveValue(/\d+/);
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByLabel('Asunto final')).toHaveValue('Hola Luis');
  await communication.getByRole('button',{name:'Cambiar destinatario o template'}).click();
  await communication.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Contacto original de la oportunidad'});
  await communication.getByRole('button',{name:/CRM template/}).first().click();
  await expect(communication.getByLabel('Asunto final')).toHaveValue('Hola');
  await communication.getByRole('button',{name:'Cerrar',exact:true}).click();
  // Capture WhatsApp intent locally: this test never opens or sends a real message.
  await page.evaluate(()=>{window.open=(url)=>{(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl=String(url);return null}});
  await lead.getByRole('button',{name:'WhatsApp',exact:true}).click();
  const whatsapp=page.getByRole('dialog').last();
  await whatsapp.getByRole('combobox',{name:'Destinatario',exact:true}).selectOption({label:'Luis · Principal'});
  await whatsapp.getByRole('button',{name:/CRM WhatsApp template/}).click();
  await whatsapp.getByRole('button',{name:'Guardar y ver contenido final'}).click();
  await whatsapp.getByLabel('Revisé destinatario y contenido final').check();
  await whatsapp.getByRole('button',{name:'Abrir WhatsApp con este mensaje'}).click();
  await expect(whatsapp.getByRole('button',{name:'Confirmar envío manual'})).toBeVisible();
  const intent=await page.evaluate(()=>(window as unknown as {crmWhatsAppUrl:string}).crmWhatsAppUrl);
  const whatsappUrl=new URL(intent);
  expect(whatsappUrl.pathname).toBe('/5493442000002');
  expect(whatsappUrl.searchParams.get('text')).toContain('Hola Luis luis@example.com');
  await whatsapp.getByRole('button',{name:'Confirmar envío manual',exact:true}).click();
  await expect(whatsapp.getByText('Envío confirmado manualmente',{exact:true})).toBeVisible();
  await whatsapp.getByRole('button',{name:'Cerrar',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(1);
  await lead.getByRole('button',{name:'Editar oportunidad',exact:true}).click();
  await expect(page.getByLabel('Nombre / razón social',{exact:true})).toHaveCount(0);
  await expect(page.getByLabel('Teléfono genérico',{exact:true})).toHaveCount(0);
  await page.getByLabel('Nombre de oportunidad',{exact:true}).fill('Primera venta actualizada');
  await page.getByRole('button',{name:'Guardar oportunidad',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto(accountUrl);
  const row=page.locator('article').filter({has:page.getByRole('link',{name:/Primera venta actualizada · #/})});
  await row.getByRole('button',{name:'Editar datos de venta',exact:true}).click();
  await expect(page.getByLabel('Cierre estimado',{exact:true})).toHaveValue('2027-01-15');
  await page.getByRole('combobox',{name:'Estado / etapa',exact:true}).selectOption({label:'1er contacto'});
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(row.getByText(/1er contacto/)).toBeVisible();
  await expect(page.locator('article').filter({has:page.getByRole('link',{name:/Segunda venta · #/})}).getByText(/En tratativas/)).toBeVisible();
  await page.getByRole('tab',{name:/^Contactos/}).click();
  const contact=page.locator('article').filter({has:page.getByText('Ana',{exact:true})});
  await contact.getByRole('button',{name:'Dar de baja',exact:true}).click();
  await page.getByRole('button',{name:'Confirmar baja',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Personas de contacto (1)',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Historial',exact:true}).click();
  await expect(page.getByText(/Contacto dado de baja/)).toBeVisible();
  await page.getByText('Cómo usar negocios, contactos y oportunidades',{exact:true}).click();
  await expect(page.getByText(/Su etapa indica cómo avanza esa venta/)).toBeVisible();
  await page.getByRole('link',{name:'Seguimiento',exact:true}).click();
  await page.getByRole('button',{name:'Nueva oportunidad',exact:true}).click();
  await page.getByLabel('Buscar negocio',{exact:true}).fill('Negocio E2E');
  await page.getByRole('button',{name:/Negocio E2E.*Elegir/}).click();
  await page.getByLabel('Nombre de oportunidad',{exact:true}).fill('Tercera venta');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Tercera venta',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.goto(accountUrl);
  await expect(page.getByRole('heading',{name:'Oportunidades (3)',exact:true})).toBeVisible();
  const legacyOpportunityUrl=(await page.getByRole('link',{name:/Tercera venta · #/}).getAttribute('href'))!.replace('/opportunities?','/?');
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  const businessRow=page.getByRole('row').filter({has:page.getByRole('button',{name:/Negocio E2E/})});
  await expect(businessRow).toHaveCount(1);
  await expect(businessRow.getByRole('button',{name:/3 oportunidades/})).toBeVisible();
  await expect(page.getByRole('button',{name:'Guardar vista',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:/^Filtrar/})).toBeVisible();
  await expect(page.getByRole('button',{name:'Pantalla completa',exact:true})).toBeVisible();
  await expect(businessRow.getByRole('button',{name:/1er contacto.*En tratativas/})).toBeVisible();
  await page.getByRole('button',{name:'Todos',exact:true}).click();
  await page.getByPlaceholder('Buscar negocios, oportunidades y notas…').fill('Negocio E2E');
  await expect(page.getByRole('row').filter({has:page.getByRole('button',{name:/Negocio E2E/})})).toHaveCount(1);
  await page.getByRole('button',{name:'Guardar vista',exact:true}).click();
  await page.getByPlaceholder('Ej: Alojamientos de Colón sin contactar').fill('Negocios E2E guardados');
  await page.getByRole('dialog').getByRole('button',{name:'Guardar vista',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Negocios E2E guardados',exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/business-first-list.png',fullPage:true,animations:'disabled'});
  await page.goto(legacyOpportunityUrl);
  await expect(page.getByRole('heading',{name:'Tercera venta',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.goto('/?quick=all');
  await expect(page).toHaveURL(/\/accounts/);
  await page.getByRole('link',{name:'Negocios',exact:true}).click();
  await page.getByRole('link',{name:'Seguimiento',exact:true}).click();
  await page.getByRole('button',{name:'Nueva oportunidad',exact:true}).click();
  await page.getByRole('button',{name:'Crear negocio nuevo',exact:true}).click();
  await page.getByLabel('Negocio',{exact:true}).fill('Otro negocio guiado');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await page.getByLabel('Nombre de oportunidad',{exact:true}).fill('Primera venta guiada');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Primera venta guiada',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Otro negocio guiado',exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/opportunity-guided-detail.png',fullPage:true,animations:'disabled'});

});
