import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {localDay} from '../../src/helpers/workDates';

test('contextual care: available channels, factual result, explicit continuation and editable won agreement',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/\/my-day$/);
 async function api(endpoint:string,body?:unknown){const r=await page.evaluate(async({endpoint,body})=>{const r=await fetch('/_api/'+endpoint,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:{});return {status:r.status,text:await r.text()}},{endpoint,body:body?superjson.stringify(body):undefined});expect(r.status,r.text).toBe(200);return superjson.parse<any>(r.text)}
 const name='Acompañamiento claro '+Date.now();const accountId=(await api('commercial',{action:'account_save',nombre:name,assignedUserEmail:'admin@example.com'})).id;
 await page.goto('/accounts/'+accountId);await expect(page.getByRole('button',{name:'Agregar persona de contacto',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Contactar',exact:true})).toHaveCount(0);
 const person=(await api('commercial',{action:'contact_save',accountId,name:'Ana',email:'ana@example.com',isPrimary:true})).id;
 const sale=(await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Publicación confirmada',estado:'Cargado',primaryContactId:person})).id;
 const config=await api('pipeline?mode=config');const won=config.stages.find((s:any)=>s.active&&s.classification==='won');
 await api('pipeline',{action:'transition',leadId:sale,revision:0,stage:won.name,convertClient:true,closing:{agreement:'Publicación mensual',person:'Ana',material:'Propuesta 1',responsible:'Equipo',deliveryDate:localDay(),reviewed:false},onboarding:{title:'Consultar cómo le fue a Ana',dueDate:localDay()}});
 await page.goto('/sales/'+sale);await expect(page.getByText('Consultar cómo le fue a Ana',{exact:true})).toBeVisible();await expect(page.getByText('Cómo avanzar con esta gestión',{exact:true})).toHaveCount(0);await expect(page.getByText('Esta tarea acompaña al negocio en general.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Revisar acuerdo y entrega',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByRole('textbox',{name:'Qué se acordó',exact:true})).toHaveValue('Publicación mensual');await dialog.getByRole('textbox',{name:'Qué se acordó',exact:true}).fill('Publicación mensual con asistencia');await dialog.getByRole('button',{name:'Guardar',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByText('Publicación mensual con asistencia',{exact:true}).first()).toBeVisible();expect((await api('pipeline?leadId='+sale)).insights[0].estado).toBe(won.name);
 const task=page.locator('article').filter({has:page.getByText('Consultar cómo le fue a Ana',{exact:true})});await task.getByRole('button',{name:'Contactar',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('link',{name:'Email',exact:true})).toBeVisible();await expect(dialog.getByRole('link',{name:'WhatsApp',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Registrar qué pasó',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'¿Qué pasó?',exact:true})).toBeFocused();await expect(dialog.getByRole('combobox',{name:'Propósito',exact:true})).toHaveValue('care');await expect(dialog.getByRole('combobox',{name:'¿Qué pasó?',exact:true}).locator('option[value="interested"]')).toHaveCount(0);await dialog.getByRole('combobox',{name:'¿Qué pasó?',exact:true}).selectOption('care_completed');await dialog.getByRole('combobox',{name:'Cómo sigue',exact:true}).selectOption('done');await dialog.getByRole('button',{name:'Guardar resultado',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('heading',{name:'Por ahora no hay otro paso',exact:true})).toBeVisible();
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/contextual-won-desktop.png',fullPage:true});await page.getByRole('button',{name:'Admin Test',exact:true}).click();await page.getByRole('menuitem',{name:'Tema oscuro'}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/contextual-won-dark.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/contextual-won-mobile.png',fullPage:true});
 await page.goto('/accounts');await page.getByRole('button',{name:'Tabla',exact:true}).click();await page.getByPlaceholder(/Buscar negocios/).fill(name);const row=page.getByRole('row').filter({has:page.getByText(name,{exact:true})});await expect(row.getByText(/Cliente/)).toBeVisible();await page.getByRole('button',{name:'Grilla',exact:true}).click();await expect(page.getByRole('button',{name:'Tabla',exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
