import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {basePreferences} from '../../src/helpers/businessListPreferences';
for(const role of ['user','admin'])for(const width of [1280,390])for(const presentation of ['table','grid'] as const)test(`inline business badges respect ${role} permissions in ${presentation} at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});let city='Colón',fail=true;const mutations:any[]=[];let release!:()=>void;const slow=new Promise<void>(resolve=>{release=resolve;});
 await page.addInitScript(preferences=>{localStorage.setItem('hospeda-live-mode','off');localStorage.setItem('hospeda-business-list-v1-user-3',JSON.stringify({preferences,context:{page:1,scrollY:0,scrollX:0}}));},{...basePreferences(),presentation,columns:['nombre','ciudad','assignedUserEmail','actions'],pins:{actions:'right'}});
 await page.route('**/_api/**',async route=>{
  const url=new URL(route.request().url());let data:unknown={},status=200;
  if(url.pathname.endsWith('/auth/session'))data={user:{id:3,email:'owner@example.com',displayName:'Owner',role}};
  else if(url.pathname.endsWith('/business_list_defaults'))data={defaults:null};
  else if(url.pathname.endsWith('/saved_views'))data={views:[]};
  else if(url.pathname.endsWith('/settings'))data={users:[{id:3,email:'owner@example.com',displayName:'Owner',role:'user'},{id:4,email:'other@example.com',displayName:'Other',role:'user'}],cities:[{id:'1',name:'Colón'},{id:'2',name:'Concordia'}],types:[],subtypes:[],templates:[],authorizedEmails:[],opportunityStages:[]};
  else if(url.pathname.endsWith('/commercial')){const id=url.searchParams.get('accountId');data={account:{id,nombre:'Negocio '+id,ciudad:city,assignedUserEmail:id==='2'?'other@example.com':'owner@example.com',archivedAt:null},contacts:[],opportunities:[],journal:[],leadJournal:[],stages:[]};}
  else if(url.pathname.endsWith('/leads_quick')){const body=superjson.parse<any>(route.request().postData()!);mutations.push(body);if(fail){fail=false;status=409;data={error:'Este dato cambió mientras lo editabas. Recargá los datos y revisá el nuevo valor.'};}else{if(body.field==='ciudad'){await slow;city=body.value;}data={ok:true};}}
  else if(url.pathname.endsWith('/leads'))data={rows:[1,2].map(id=>({id:String(id),accountId:String(id),nombre:'Negocio '+id,ciudad:city,assignedUserEmail:id===2?'other@example.com':'owner@example.com',canModify:id===1||role==='admin',opportunityCount:0,contactCount:0})),total:2,page:1,pageSize:50,filters:{ciudades:[],estados:[],tipos:[],asignados:[],suscripciones:[],origenes:[],quienesCargaron:[],mediosContacto:[],creadosPor:[]}};
  await route.fulfill({status,contentType:'application/json',body:superjson.stringify(data)});
 });
 await page.goto('/accounts');const cityButton=page.getByRole('button',{name:'Editar ciudad de Negocio 1',exact:true});await expect(cityButton).toBeVisible();
 if(role==='user'){await expect(page.getByRole('button',{name:'Editar ciudad de Negocio 2',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:/Editar responsable de/})).toHaveCount(0);}
 await cityButton.click();let popup=page.getByRole('dialog',{name:'Editar ciudad',exact:true});const select=popup.getByRole('combobox',{name:'Nuevo valor de ciudad',exact:true});await expect(select).toHaveValue('Colón');await select.selectOption('Concordia');await popup.getByRole('button',{name:'Cancelar',exact:true}).click();expect(mutations).toHaveLength(0);await expect(cityButton).toBeFocused();
 await cityButton.click();popup=page.getByRole('dialog',{name:'Editar ciudad',exact:true});await popup.getByRole('combobox').selectOption('Concordia');await popup.getByRole('button',{name:'Guardar',exact:true}).click();await expect(popup.getByRole('alert')).toContainText('Este dato cambió');await expect(popup.getByRole('combobox')).toHaveValue('Concordia');
 await popup.getByRole('button',{name:'Recargar datos',exact:true}).click();await expect(popup.getByRole('combobox')).toHaveValue('Colón');await popup.getByRole('combobox').selectOption('Concordia');await popup.getByRole('button',{name:'Guardar',exact:true}).click();await expect(popup.getByRole('button',{name:'Guardando ciudad…',exact:true})).toBeDisabled();await expect(popup.getByRole('button',{name:'Cancelar',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(popup).toBeVisible();release();await expect(popup).toHaveCount(0);await expect(cityButton).toContainText('Concordia');expect(mutations[1]).toEqual({id:'1',accountId:'1',field:'ciudad',value:'Concordia',expectedValue:'Colón'});
 if(role==='admin'){const button=page.getByRole('button',{name:'Editar responsable de Negocio 1',exact:true});await button.click();popup=page.getByRole('dialog',{name:'Editar responsable',exact:true});await expect(popup.getByRole('combobox')).toHaveValue('owner@example.com');await page.screenshot({path:`test-results/inline-badge-admin-${presentation}-${width}.png`,animations:'disabled'});await popup.getByRole('combobox').selectOption('other@example.com');await popup.getByRole('button',{name:'Guardar',exact:true}).click();await expect(popup).toHaveCount(0);expect(mutations.at(-1)).toEqual({id:'1',accountId:'1',field:'assignedUserEmail',value:'other@example.com',expectedValue:'owner@example.com'});}
 else {await cityButton.click();await expect(page.getByRole('dialog',{name:'Editar ciudad',exact:true}).getByRole('combobox')).toHaveValue('Concordia');await page.screenshot({path:`test-results/inline-badge-user-${presentation}-${width}.png`,animations:'disabled'});await page.keyboard.press('Escape');}
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
});
