import {test,expect} from '@playwright/test';
import superjson from 'superjson';
const imageData='iVBORw0KGgoAAAANSUhEUgAAAZAAAADICAIAAABJdyC1AAACrElEQVR4nO3UQQ3AIADAwDFZGEYTbrDAjzS5U9BXx1z7Ayj4XwcA3DIsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsIAMwwIyDAvIMCwgw7CADMMCMgwLyDAsIMOwgAzDAjIMC8gwLCDDsICMAzjgA0q9E7akAAAAAElFTkSuQmCC';
for(const width of [1280,390])test(`selected material preview, retry and image zoom at ${width}px`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:844});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/my-day$/);
 async function api(endpoint:string,body?:unknown){const result=await page.evaluate(async({endpoint,body})=>{const r=await fetch('/_api/'+endpoint,body?{method:'POST',headers:{'Content-Type':'application/json'},body}:{});return {status:r.status,text:await r.text()}},{endpoint,body:body?superjson.stringify(body):undefined});expect(result.status,result.text).toBe(200);return superjson.parse<any>(result.text);}
 const stamp=width+' '+Date.now();const accountId=(await api('commercial',{action:'account_save',nombre:'Materiales '+stamp,assignedUserEmail:'admin@example.com'})).id;
 const leadId=(await api('commercial',{action:'opportunity_save',accountId,opportunityName:'Propuesta con material '+stamp})).id;
 async function material(title:string,version:unknown){const id=crypto.randomUUID();await api('resources',{action:'create',id,title,type:'propuesta',accountId:null,leadId:null,activityId:null,library:true,categoryId:null,version});await api('resources',{action:'status',id,status:'approved',revision:1});return (await api('resources')).documents.find((d:any)=>d.id===id);}
 const picture=await material('Imagen '+stamp,{fileData:imageData,fileName:'imagen.png',mimeType:'image/png'});
 const text=await material('Texto '+stamp,{fileData:Buffer.from('Contenido seguro <script>no ejecutar</script>').toString('base64'),fileName:'contenido.txt',mimeType:'text/plain'});
 const external=await material('Enlace '+stamp,{url:'https://example.com/material.pdf'});
 await page.goto('/sales/'+leadId);await page.getByRole('tab',{name:'Documentos',exact:true}).click();
 async function select(title:string){await page.getByRole('combobox',{name:'Documento de biblioteca',exact:true}).click();await page.getByLabel('Buscar documento en biblioteca',{exact:true}).fill(title);await page.getByRole('option',{name:new RegExp(title)}).click();}
 await select(picture.title);
 const download='**/_api/resources/download?versionId='+picture.versions[0].id;let attempts=0;
 await page.route(download,async route=>{attempts++;if(attempts===1)await route.fulfill({status:500,body:'Error de prueba'});else{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();}});
 await page.getByRole('button',{name:'Previsualizar material seleccionado',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByRole('alert')).toContainText('No se pudo cargar');
 await dialog.getByRole('button',{name:'Reintentar vista previa',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('Cargando vista previa…');await expect(dialog.getByRole('img',{name:'Vista previa de imagen.png'})).toBeVisible();
 await expect.poll(()=>dialog.getByRole('img',{name:'Vista previa de imagen.png',exact:true}).evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth===400)).toBe(true);
 await dialog.getByRole('button',{name:'Ampliar imagen',exact:true}).click();await expect(dialog.getByRole('button',{name:'Ajustar imagen',exact:true})).toHaveAttribute('aria-pressed','true');await expect.poll(()=>dialog.getByRole('img',{name:'Vista previa de imagen.png',exact:true}).evaluate(el=>el.getBoundingClientRect().width>el.parentElement!.clientWidth)).toBe(true);
 await dialog.getByRole('region',{name:'Imagen del material',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>dialog.getByRole('region',{name:'Imagen del material',exact:true}).evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
 await page.screenshot({path:`test-results/material-preview-${width}.png`});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
 await dialog.getByRole('button',{name:'Ajustar imagen',exact:true}).click();await expect(dialog.getByRole('button',{name:'Ampliar imagen',exact:true})).toHaveAttribute('aria-pressed','false');await dialog.getByRole('button',{name:'Cerrar vista previa',exact:true}).click();await expect(page.getByRole('combobox',{name:'Documento de biblioteca',exact:true})).toContainText(picture.title);expect((await api('resources?accountId='+accountId)).documents).toHaveLength(0);expect(attempts).toBe(2);
 await select(text.title);await page.getByRole('button',{name:'Previsualizar material seleccionado',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('Contenido seguro <script>no ejecutar</script>',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Cerrar vista previa',exact:true}).click();
 await select(external.title);await expect(page.getByRole('button',{name:'Previsualizar material seleccionado',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Abrir material seleccionado',exact:true})).toHaveAttribute('href','/_api/resources/download?versionId='+external.versions[0].id);
 expect((await api('resources?accountId='+accountId)).documents).toHaveLength(0);await select(picture.title);await page.getByRole('button',{name:'Vincular documento al negocio',exact:true}).click();await expect(page.getByRole('heading',{name:picture.title+' · Aprobado',exact:true})).toBeVisible();expect((await api('resources?accountId='+accountId)).documents).toHaveLength(1);expect(errors).toEqual([]);
});
