import {test,expect} from '@playwright/test';
import superjson from 'superjson';
import {localDay} from '../../src/helpers/workDates';
import type {PipelineData} from '../../src/endpoints/pipeline.schema';
test('Pipeline loss, objections, reactivation and explained manual priority with compact dark/mobile UI',async({page})=>{
 test.setTimeout(120000);
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/\/my-day$/);await page.goto("/accounts");
 async function mutate(endpoint:string,body:unknown){const r=await page.evaluate(async({endpoint,body})=>{const response=await fetch('/_api/'+endpoint,{method:'POST',body,headers:{'Content-Type':'application/json'}});return {status:response.status,text:await response.text()};},{endpoint,body:superjson.stringify(body)});expect(r.status,r.text).toBe(200);return superjson.parse<{id:string}>(r.text).id;}
 const name='Pipeline E2E '+Date.now();const accountId=await mutate('commercial',{action:'account_save',nombre:name,ciudad:'Colón',assignedUserEmail:'admin@example.com'});
 const leadId=await mutate('commercial',{action:'opportunity_save',accountId,opportunityName:'Publicación anual E2E',estado:'Cargado',assignedUserEmail:'admin@example.com'});
 await mutate('leads_quick',{id:leadId,field:'prioridad',value:'baja'});
 await page.goto('/opportunities?leadId='+leadId);let detail=page.locator('main');await detail.getByRole('tab',{name:'Resumen',exact:true}).click();await expect(detail.getByText('Sin seguimiento pendiente',{exact:true})).toHaveCount(0);
 await detail.getByText('Etapa y prioridad',{exact:true}).first().click();await detail.getByText(/^Dudas y objeciones/).click();await expect(detail.getByText('Prioridad manual:')).toContainText('baja');await expect(detail.getByText('Sugerencia:')).toContainText('media');await expect(detail.getByText('Sin seguimiento pendiente → media')).toBeVisible();
 await detail.getByRole('button',{name:'Agregar objeción',exact:true}).click();let editor=page.getByRole('dialog').last();await editor.getByRole('combobox',{name:'Objeción',exact:true}).selectOption({label:'Precio'});await editor.getByLabel('Notas / resolución').fill('Debe consultar con su socio');await editor.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(detail.getByText('Debe consultar con su socio',{exact:true})).toBeVisible();
 await detail.getByRole('button',{name:'Cambiar etapa',exact:true}).click();editor=page.getByRole('dialog').last();await editor.getByRole('combobox',{name:'Etapa',exact:true}).selectOption('Perdida');await editor.getByRole('combobox',{name:'Motivo de pérdida',exact:true}).selectOption({label:'No es el momento'});await editor.getByLabel('Comentario',{exact:true}).fill('Revisar próxima temporada');await editor.getByLabel('Definir fecha para retomar').check();await editor.getByLabel('Fecha de recontacto').fill(localDay());await editor.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(detail.getByText('Sugerencia:')).toContainText('Sin sugerencia');
 await page.screenshot({path:'test-results/pipeline-detail-light.png',fullPage:true});
 await page.goto('/reactivation');const row=page.locator('article').filter({has:page.getByText(name,{exact:true})});await expect(row.getByText('Revisar próxima temporada')).toBeVisible();await row.getByRole('button',{name:'Planificar',exact:true}).click();editor=page.getByRole('dialog');await editor.getByRole('combobox',{name:'Acción',exact:true}).selectOption('reopen');await editor.getByRole('combobox',{name:'Etapa abierta',exact:true}).selectOption('En tratativas');await editor.getByLabel('Seguimiento',{exact:true}).fill('Llamar próxima temporada E2E');await editor.getByRole('button',{name:'Guardar',exact:true}).click();await expect(editor).toHaveCount(0);await expect(row).toHaveCount(0);
 const body=await page.evaluate(async id=>(await fetch('/_api/pipeline?leadId='+id)).text(),leadId);const d=superjson.parse<PipelineData>(body);expect(d.events.some(e=>e.reasonId&&e.comment==='Revisar próxima temporada')).toBe(true);expect(d.events.some(e=>e.action==='reactivation')).toBe(true);expect(d.insights[0].manualPriority).toBe('baja');
 await page.goto('/opportunities');await page.getByRole('button',{name:'Tabla',exact:true}).click();await page.getByPlaceholder(/Buscar/).first().fill(name);const tableRow=page.getByRole('row').filter({hasText:name});await expect(tableRow).toBeVisible();await expect(tableRow.getByRole('button',{name:'En tratativas',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tablero comercial',exact:true}).click();await page.getByRole('button',{name:'Ver etapas del equipo',exact:true}).click();const card=page.locator('article').filter({has:page.getByText('Publicación anual E2E',{exact:true})});await expect(card).toBeVisible();await expect(card.getByText('Prioridad manual:')).toContainText('baja');const column=page.locator('section').filter({has:card}).last();await expect(column.getByRole('heading',{name:/En tratativas/})).toBeVisible();
 await page.screenshot({path:'test-results/pipeline-kanban-light.png',fullPage:true});await page.getByRole('button',{name:'Admin Test',exact:true}).click();await page.getByRole('menuitem',{name:'Tema oscuro'}).click();await page.screenshot({path:'test-results/pipeline-kanban-dark.png',fullPage:true});await page.setViewportSize({width:390,height:844});await card.scrollIntoViewIfNeeded();await expect(card).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'test-results/pipeline-kanban-mobile.png',fullPage:true});
 // Another writer changes the opportunity while Live Mode refreshes the open stage form.
 await page.setViewportSize({width:1280,height:900});const baseline=page.waitForResponse(r=>r.url().includes('/_api/live_version'));await page.getByRole('button',{name:'Opciones de actualización',exact:true}).click();await page.getByRole('menuitemcheckbox',{name:'Actualizar automáticamente',exact:true}).click();await baseline;
 await card.getByRole('button',{name:'Cambiar etapa',exact:true}).click();editor=page.getByRole('dialog');await editor.getByRole('combobox',{name:'Etapa',exact:true}).selectOption('Filtrado');const refreshed=page.waitForResponse(r=>r.url().includes('/_api/pipeline?ids=')&&r.status()===200);await mutate('leads_quick',{id:leadId,field:'prioridad',value:'alta'});await refreshed;await expect(card.getByText('Prioridad manual:')).toContainText('alta');await editor.getByRole('button',{name:'Guardar',exact:true}).click();await expect(editor.getByRole('alert')).toContainText('La gestión cambió');await editor.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByRole('button',{name:'Descartar cambios y salir',exact:true}).click();await expect(column.getByRole('heading',{name:/En tratativas/})).toBeVisible();
 await page.goto('/my-day');await expect(page.getByText('Llamar próxima temporada E2E',{exact:true})).toBeVisible();
});
