import {test,expect} from '@playwright/test';import superjson from 'superjson';import {localDay} from '../../src/helpers/workDates';
test('beginner journey: minimal business, contact, task result, won sale, care and another sale',async({page})=>{
 test.setTimeout(240000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('hospeda-live-mode','off'));
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Contraseña',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page).toHaveURL(/\/my-day$/);
 await page.getByRole('link',{name:'Negocios',exact:true}).click();await page.getByRole('button',{name:'Nuevo negocio',exact:true}).click();await page.getByLabel('Negocio',{exact:true}).fill('Cabañas Camino Claro');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('heading',{name:'Cabañas Camino Claro',exact:true})).toBeVisible();const accountUrl=page.url();
 await page.getByRole('button',{name:'Agregar persona de contacto',exact:true}).click();await page.getByLabel('Nombre de la persona').fill('Ana');await page.getByLabel('Email',{exact:true}).fill('ana@example.com');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Volver al próximo paso',exact:true}).click();
 await page.getByRole('button',{name:'Crear una venta',exact:true}).click();await page.getByLabel('Qué querés vender').fill('Publicación de cabañas');await expect(page.getByRole('combobox',{name:'Contacto principal de oportunidad'})).not.toHaveValue('');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Planificar próximo paso',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Título',{exact:true}).fill('Consultar necesidades con Ana');await dialog.getByLabel('Fecha de vencimiento').fill(localDay());await dialog.getByRole('button',{name:'Guardar próximo paso',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.getByRole('link',{name:'Mi día',exact:true}).click();const row=page.locator('article').filter({has:page.getByText('Consultar necesidades con Ana',{exact:true})});await row.getByRole('button',{name:'Contactar',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('link',{name:'Email',exact:true})).toBeVisible();await expect(dialog.getByRole('link',{name:'WhatsApp',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Registrar qué pasó',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('¿Qué pasó?').selectOption('interested');await dialog.getByRole('combobox',{name:'Cómo sigue',exact:true}).selectOption('task');await dialog.getByLabel('Qué hay que hacer').fill('Revisar la propuesta con Ana');await dialog.getByRole('button',{name:'Guardar y programar próximo paso',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByText('Consultar necesidades con Ana',{exact:true})).toHaveCount(0);await expect(page.getByText('Revisar la propuesta con Ana',{exact:true})).toBeVisible();
 await page.goto(accountUrl);await page.getByRole('link',{name:'Publicación de cabañas',exact:true}).click();await expect(page).toHaveURL(/\/sales\/\d+$/);await expect(page.getByRole('tablist',{name:'Secciones de la oportunidad'}).getByRole('tab')).toHaveCount(5);await expect(page.getByRole('dialog')).toHaveCount(0);
 const configResponse=await page.evaluate(async()=>{const r=await fetch('/_api/pipeline?mode=config');return {status:r.status,body:await r.text()}});expect(configResponse.status,configResponse.body).toBe(200);const pipeline=superjson.parse<any>(configResponse.body);const won=pipeline.stages.find((s:any)=>s.active&&s.classification==='won');expect(won).toBeTruthy();await page.getByText('Etapa y prioridad',{exact:true}).first().click();await page.getByRole('button',{name:'Cambiar etapa',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:'Etapa',exact:true}).selectOption(won.name);await dialog.getByLabel('Marcar este negocio como cliente').check();await dialog.getByLabel('Crear una tarea de acompañamiento').check();await dialog.getByRole('button',{name:'Guardar',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.goto(accountUrl);await expect(page.getByText(/· Cliente ·/).first()).toBeVisible();await page.getByText('Otros próximos pasos (1)',{exact:true}).click();await expect(page.getByText('Acompañar el inicio y revisar lo acordado',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Ofrecer otra venta',exact:true}).click();await page.getByLabel('Qué querés vender').fill('Campaña de temporada');await page.getByRole('button',{name:'Guardar',exact:true}).click();await expect(page.getByRole('link',{name:'Campaña de temporada',exact:true})).toBeVisible();
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/usability-business-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/usability-business-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.zoom='2');await expect(page.getByRole('button',{name:'Contactar',exact:true}).first()).toBeVisible();await page.screenshot({path:'test-results/usability-business-zoom.png',fullPage:true});await page.evaluate(()=>document.documentElement.style.zoom='1');
 // Escape must preserve edits until the explicit discard action.
 await page.getByRole('button',{name:'Editar negocio',exact:true}).click();await page.getByLabel('Negocio',{exact:true}).fill('No perder este cambio');await page.keyboard.press('Escape');await expect(page.getByRole('heading',{name:'Tenés cambios sin guardar'})).toBeVisible();await page.getByRole('button',{name:'Seguir editando',exact:true}).click();await expect(page.getByLabel('Negocio',{exact:true})).toHaveValue('No perder este cambio');await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByRole('button',{name:'Descartar cambios y salir',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 expect(errors).toEqual([]);await page.goto('/guide');await expect(page.getByRole('heading',{name:'Usar Hospeda, paso a paso'})).toBeVisible();
});
