import {describe,it,expect,beforeEach} from 'vitest';
import {availableListPreferences,basePreferences,effectivePins,initialPreferences,listPreferencesSchema,readPersonalPreferences,savePersonalPreferences,teamDefaultsSchema,preferencesFromSavedView,legacyFilterLabels} from './businessListPreferences';
describe('business list preferences',()=>{
 beforeEach(()=>localStorage.clear());
 it('isolates browser preferences and complete return context by user',()=>{const p={...basePreferences(),presentation:'grid' as const,query:'Colón',loadMode:'continuous' as const};savePersonalPreferences(1,p,{page:4,scrollY:650,scrollX:80,anchorId:'44',anchorOffset:50});expect(readPersonalPreferences(2)).toBeNull();expect(readPersonalPreferences(1)?.context).toEqual({page:4,scrollY:650,scrollX:80,anchorId:'44',anchorOffset:50});expect(readPersonalPreferences(1)?.preferences).toEqual(p);});
 it('uses continuous loading without dropping legacy pagination data or other preferences',()=>{const legacy={...basePreferences(),loadMode:'pages' as const,query:'Colón',pageSize:10};expect(listPreferencesSchema.parse(legacy).loadMode).toBe('pages');expect(availableListPreferences(legacy)).toEqual({...legacy,loadMode:'continuous',pageSize:50});expect(basePreferences().loadMode).toBe('continuous');const saved=preferencesFromSavedView(basePreferences(),{preferences:legacy})!;expect(availableListPreferences(saved)).toEqual({...legacy,loadMode:'continuous',pageSize:50});savePersonalPreferences(1,legacy,{page:3,scrollY:800,scrollX:60,anchorId:'21'});const personal=readPersonalPreferences(1)!;expect(availableListPreferences(personal.preferences).loadMode).toBe('continuous');expect(personal.context.page).toBe(3);expect(initialPreferences({preferences:legacy,presets:[],initialPresetId:null},false).query).toBe('Colón');});
 it('rejects corrupt, missing mandatory name and unknown stored fields',()=>{expect(listPreferencesSchema.safeParse({...basePreferences(),columns:['email']}).success).toBe(false);expect(listPreferencesSchema.safeParse({...basePreferences(),columns:['nombre','password']}).success).toBe(false);localStorage.setItem('hospeda-business-list-v1-user-1','broken');expect(readPersonalPreferences(1)).toBeNull();});
 it('keeps available presets separate from the initial active filter',()=>{const filter=[{rules:[{field:'ciudad' as const,operator:'eq' as const,value:'Colón'}]}];const team={preferences:basePreferences(),presets:[{id:'colon',name:'Colón',filters:filter}],initialPresetId:null};expect(initialPreferences(team,false).filters).toEqual([]);expect(initialPreferences({...team,initialPresetId:'colon'},false).filters).toEqual(filter);expect(initialPreferences(team,true).presentation).toBe('grid');expect(teamDefaultsSchema.safeParse({...team,initialPresetId:'missing'}).success).toBe(false);});
 it('preserves filters and ordering from legacy saved views',()=>{const p=preferencesFromSavedView(basePreferences(),{entity:'business',query:'hotel',sortBy:'ciudad',sortDir:'desc',inline:{cityFilter:{include:['Colón'],exclude:[]},textFilters:{email:{mode:'not_empty',value:''}},nextAction:'overdue'}})!;expect(p.query).toBe('hotel');expect(p.sortBy).toBe('ciudad');expect(p.legacyFilters?.ciudades).toEqual(['Colón']);expect(p.legacyFilters?.nextAction).toBe('overdue');expect(legacyFilterLabels(p.legacyFilters!)).toContain('Ciudad: Colón');});
 it('reserves half the width for scrolling and never pins on mobile',()=>{const p={...basePreferences(),pins:{nombre:'left' as const,email:'right' as const,telefono:'left' as const}};const pins=effectivePins(p,900);expect(Object.values(pins).length).toBe(2);expect(effectivePins(p,390)).toEqual({});expect(p.pins.email).toBe('right');const right=effectivePins({...p,columns:['nombre','email','telefono'],widths:{nombre:100,email:100,telefono:100},pins:{email:'right',telefono:'right'}},900);expect(right.telefono.offset).toBe(0);expect(right.email.offset).toBe(100);});
});
