import {describe,it,expect} from 'vitest';
import {applyBusinessSystemView,defaultSystemViews,systemViewsSchema} from './businessSystemViews';
import {basePreferences,teamDefaultsSchema} from './businessListPreferences';
describe('business system views',()=>{
 it('recovers the six original views without requiring stored configuration',()=>{expect(defaultSystemViews().map(v=>v.id)).toEqual(['all','mine','today','overdue','unassigned','noNext']);expect(teamDefaultsSchema.parse({preferences:basePreferences(),presets:[],initialPresetId:null}).systemViews).toBeUndefined();});
 it('uses the applying user and the current Argentina calendar day',()=>{const current={...basePreferences(),query:'hotel',legacyFilters:{ciudades:['Colón']} as any};const now=new Date('2026-10-08T01:00:00Z');expect(applyBusinessSystemView(current,'mine','seller@example.com',now).filters).toEqual([{rules:[{field:'assignedUserEmail',operator:'eq',value:'seller@example.com'}]}]);expect(applyBusinessSystemView(current,'today','seller@example.com',now).filters[0].rules[0]).toEqual({field:'fechaProximaAccion',operator:'on',value:'2026-10-07'});expect(applyBusinessSystemView(current,'overdue','seller@example.com',now).filters[0].rules[0].operator).toBe('before');const all=applyBusinessSystemView(current,'all','seller@example.com');expect(all.query).toBe('');expect(all.filters).toEqual([]);expect(all.legacyFilters).toBeUndefined();expect(all.columns).toEqual(current.columns);expect(all.pins).toEqual(current.pins);});
 it('keeps absence criteria separate from commercial stage rules',()=>{expect(applyBusinessSystemView(basePreferences(),'unassigned','u').filters[0].rules[0]).toEqual({field:'assignedUserEmail',operator:'empty'});expect(applyBusinessSystemView(basePreferences(),'noNext','u').filters[0].rules[0]).toEqual({field:'fechaProximaAccion',operator:'empty'});});
 it('accepts admin visibility, names and ordering but rejects duplicate and unknown criteria',()=>{const custom=defaultSystemViews().reverse().map(v=>({...v,name:'Equipo '+v.name,enabled:v.id!=='today'}));expect(systemViewsSchema.parse(custom)).toEqual(custom);expect(systemViewsSchema.safeParse([custom[0],custom[0]]).success).toBe(false);expect(systemViewsSchema.safeParse([{id:'won',name:'Venta',enabled:true}]).success).toBe(false);expect(systemViewsSchema.safeParse([{id:'all',name:' ',enabled:true}]).success).toBe(false);});
});
