/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadPriority = "alta" | "baja" | "media";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface AppSettings {
  key: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface AuthorizedEmails {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  email: string;
  id: Generated<Int8>;
}

export interface CrmCities {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
}

export interface CrmSubtypes {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  typeName: string | null;
}

export interface CrmVerticals {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  sortOrder: Generated<number>;
}

export interface EmailOutbox {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  htmlBody: string;
  id: Generated<Int8>;
  lastError: string | null;
  leadId: Int8 | null;
  messageId: string | null;
  recipientEmail: string;
  recipientName: string | null;
  replyToEmail: string | null;
  replyToName: string | null;
  requestedByEmail: string | null;
  requestedByName: string | null;
  requestedByUserId: number | null;
  senderEmail: string;
  senderName: string;
  sentAt: Timestamp | null;
  status: Generated<string>;
  subject: string;
  templateId: Int8 | null;
  textBody: string;
  updatedAt: Generated<Timestamp>;
}

export interface LeadJournal {
  accountId: Int8 | null;
  action: string;
  actorEmail: string | null;
  actorName: string;
  actorUserId: number | null;
  createdAt: Generated<Timestamp>;
  fieldName: string | null;
  id: Generated<Int8>;
  leadCity: string | null;
  leadId: Int8 | null;
  leadName: string;
  leadType: string | null;
  metadata: Json | null;
  newValue: string | null;
  oldValue: string | null;
}

export interface LeadNotes {
  author: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  leadId: Int8;
  note: string;
}

export interface Leads {
  stageSince: Timestamp | null;
  pipelineRevision: Generated<number>;
  reactivatedFromId: Int8 | null;
  assignedAt:Timestamp|null;
  contactBaselineDate:Timestamp|null;
  contactBaselineResult:string|null;
  accountId: Generated<Int8>;
  opportunityName: string | null;
  primaryContactId: Int8 | null;
  serviceInterest: string | null;
  estimatedCloseDate: Timestamp | null;
  archivoAdjunto: string | null;
  asignadoA: string | null;
  assignedUserEmail: string | null;
  ciudad: string | null;
  clientePotencialRecurrente: Generated<boolean>;
  commercialProfile: string | null;
  contactName: string | null;
  creadoPor: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  deletedByEmail: string | null;
  deletedByName: string | null;
  deletedByUserId: number | null;
  email: string | null;
  estado: string | null;
  fechaCreacion: Timestamp | null;
  fechaProximaAccion: Timestamp | null;
  fechaUltimoContacto: Timestamp | null;
  fuenteReferencia: string | null;
  id: Generated<Int8>;
  medioContactoPreferido: string | null;
  nombre: string;
  notas: string | null;
  origen: string | null;
  perfilAirbnb: string | null;
  perfilBooking: string | null;
  perfilFacebook: string | null;
  perfilInstagram: string | null;
  perfilTurismoEntreRios: string | null;
  prioridad: LeadPriority | null;
  quienCargo: string | null;
  resultadoUltimoContacto: string | null;
  sitioWeb: string | null;
  subtipo: string | null;
  suscripcion: string | null;
  telefono: string | null;
  tipo: string | null;
  updatedAt: Generated<Timestamp>;
  urlGmap: string | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface MessageTemplates {
  active: Generated<boolean>;
  body: string;
  channel: string;
  commercialProfile: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  subject: string | null;
  updatedAt: Generated<Timestamp>;
  vertical: string | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  fullName: string | null;
  id: Generated<number>;
  phone: string | null;
  role: Generated<UserRole>;
  senderEmail: string | null;
  sex: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface CrmAccounts {
  archivedAt: Generated<Timestamp | null>;
  mergedIntoId: Int8 | null;
  mergedAt: Timestamp | null;
  doNotContact: Generated<boolean>;
  id: Generated<Int8>;
  sourceLeadId: Int8 | null;
  nombre: string;
  ciudad: string | null;
  telefono: string | null;
  email: string | null;
  sitioWeb: string | null;
  urlGmap: string | null;
  perfilInstagram: string | null;
  perfilFacebook: string | null;
  perfilAirbnb: string | null;
  perfilBooking: string | null;
  perfilTurismoEntreRios: string | null;
  assignedUserEmail: string | null;
  commercialStatus: Generated<"prospect" | "client">;
  clientSince: Timestamp | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}
export interface CrmContacts {
  id: Generated<Int8>;
  accountId: Int8;
  sourceLeadId: Int8 | null;
  name: string;
  position: string | null;
  phone: string | null;
  email: string | null;
  preferredChannel: string | null;
  isPrimary: Generated<boolean>;
  notes: string | null;
  deletedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}
export interface CrmCommercialJournal {
  id: Generated<Int8>;
  accountId: Int8;
  contactId: Int8 | null;
  action: string;
  actorEmail: string | null;
  actorName: string;
  metadata: Generated<Json>;
  createdAt: Generated<Timestamp>;
}
export interface CrmWorkTypes { id:string; name:string; agenda:Generated<boolean>; active:Generated<boolean>; }
export interface CrmTasks {
 id:Generated<Int8>; accountId:Int8; leadId:Int8|null; title:string; description:string|null;
 participants:Generated<string>; contactIds:Generated<Json>; typeId:string; assignedUserEmail:string|null; dueDate:ColumnType<Date,string,string>; dueAt:Timestamp|null;
 priority:Generated<"alta"|"media"|"baja">; status:Generated<"pending"|"completed"|"cancelled">;
 outcome:Generated<string|null>; result:string|null; completedAt:Timestamp|null; legacy:Generated<boolean>; deletedAt:Timestamp|null;
 createdAt:Generated<Timestamp>; updatedAt:Generated<Timestamp>;
}
export interface CrmActivities {
 id:Generated<Int8>; accountId:Int8; leadId:Int8|null; taskId:Int8|null; typeId:string; title:string;
 occurredAt:Timestamp; participants:Generated<string>; contactIds:Generated<Json>; channel:string|null;
 outcome:Generated<string|null>; result:string|null; notes:string|null; actorEmail:string|null; deletedAt:Timestamp|null;
 createdAt:Generated<Timestamp>; updatedAt:Generated<Timestamp>;
}
export interface CrmWorkJournal {
 id:Generated<Int8>; accountId:Int8; entity:string; entityId:Int8; actorEmail:string|null;
 action:string; beforeValue:Json|null; afterValue:Json|null; createdAt:Generated<Timestamp>;
}
export interface CrmImportBatches {
 id:string; fingerprint:string; ownerEmail:string; source:string; sourceUrl:string|null; obtainedAt:Timestamp|null;
 rows:Json; status:Generated<'review'|'completed'>; result:Json|null; decisions:Json|null; createdAt:Generated<Timestamp>; completedAt:Timestamp|null;
}
export interface CrmDataEvidence {
 id:Generated<Int8>; accountId:Int8; originalAccountId:Int8; contactId:Int8|null; leadId:Int8|null;
 field:string; originalValue:string|null; normalizedValue:string|null; source:string; sourceUrl:string|null;
 obtainedAt:Timestamp|null; verifiedAt:Timestamp|null; validity:string; observations:Generated<string>;
 batchId:string|null; actorEmail:string; createdAt:Generated<Timestamp>;
}
export interface CrmAccountMerges {
 id:Generated<Int8>; sourceId:Int8; destinationId:Int8; actorEmail:string; reason:string;
 snapshot:Json; selections:Json; createdAt:Generated<Timestamp>;
}
export interface DB {
 crmImportBatches:CrmImportBatches;
 crmDataEvidence:CrmDataEvidence;
 crmAccountMerges:CrmAccountMerges;
  crmWorkTypes:CrmWorkTypes;
  crmTasks:CrmTasks;
  crmActivities:CrmActivities;
  crmWorkJournal:CrmWorkJournal;
  crmAccounts: CrmAccounts;
  crmContacts: CrmContacts;
  crmCommercialJournal: CrmCommercialJournal;
  appSettings: AppSettings;
  authorizedEmails: AuthorizedEmails;
  crmCities: CrmCities;
  crmSubtypes: CrmSubtypes;
  crmVerticals: CrmVerticals;
  emailOutbox: EmailOutbox;
  leadJournal: LeadJournal;
  leadNotes: LeadNotes;
  leads: Leads;
  loginAttempts: LoginAttempts;
  messageTemplates: MessageTemplates;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const LeadPriorityArrayValues: [LeadPriority, ...LeadPriority[]] = ["alta","baja","media"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.