/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadPriority = "alta" | "baja" | "media";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface AppSettings {
  key: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface AuthorizedEmails {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  email: string;
  id: Generated<Int8>;
}

export interface CrmCities {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
}

export interface CrmSubtypes {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  typeName: string | null;
}

export interface CrmVerticals {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  sortOrder: Generated<number>;
}

export interface EmailOutbox {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  htmlBody: string;
  id: Generated<Int8>;
  lastError: string | null;
  leadId: Int8 | null;
  messageId: string | null;
  recipientEmail: string;
  recipientName: string | null;
  replyToEmail: string | null;
  replyToName: string | null;
  requestedByEmail: string | null;
  requestedByName: string | null;
  requestedByUserId: number | null;
  senderEmail: string;
  senderName: string;
  sentAt: Timestamp | null;
  status: Generated<string>;
  subject: string;
  templateId: Int8 | null;
  textBody: string;
  updatedAt: Generated<Timestamp>;
}

export interface LeadJournal {
  action: string;
  actorEmail: string | null;
  actorName: string;
  actorUserId: number | null;
  createdAt: Generated<Timestamp>;
  fieldName: string | null;
  id: Generated<Int8>;
  leadCity: string | null;
  leadId: Int8 | null;
  leadName: string;
  leadType: string | null;
  metadata: Json | null;
  newValue: string | null;
  oldValue: string | null;
}

export interface LeadNotes {
  author: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  leadId: Int8;
  note: string;
}

export interface Leads {
  archivoAdjunto: string | null;
  asignadoA: string | null;
  assignedUserEmail: string | null;
  ciudad: string | null;
  clientePotencialRecurrente: Generated<boolean>;
  commercialProfile: string | null;
  contactName: string | null;
  creadoPor: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  deletedByEmail: string | null;
  deletedByName: string | null;
  deletedByUserId: number | null;
  email: string | null;
  estado: string | null;
  fechaCreacion: Timestamp | null;
  fechaProximaAccion: Timestamp | null;
  fechaUltimoContacto: Timestamp | null;
  fuenteReferencia: string | null;
  id: Generated<Int8>;
  medioContactoPreferido: string | null;
  nombre: string;
  notas: string | null;
  origen: string | null;
  perfilAirbnb: string | null;
  perfilBooking: string | null;
  perfilFacebook: string | null;
  perfilInstagram: string | null;
  perfilTurismoEntreRios: string | null;
  prioridad: LeadPriority | null;
  quienCargo: string | null;
  resultadoUltimoContacto: string | null;
  sitioWeb: string | null;
  subtipo: string | null;
  suscripcion: string | null;
  telefono: string | null;
  tipo: string | null;
  updatedAt: Generated<Timestamp>;
  urlGmap: string | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface MessageTemplates {
  active: Generated<boolean>;
  body: string;
  channel: string;
  commercialProfile: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  subject: string | null;
  updatedAt: Generated<Timestamp>;
  vertical: string | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  appSettings: AppSettings;
  authorizedEmails: AuthorizedEmails;
  crmCities: CrmCities;
  crmSubtypes: CrmSubtypes;
  crmVerticals: CrmVerticals;
  emailOutbox: EmailOutbox;
  leadJournal: LeadJournal;
  leadNotes: LeadNotes;
  leads: Leads;
  loginAttempts: LoginAttempts;
  messageTemplates: MessageTemplates;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const LeadPriorityArrayValues: [LeadPriority, ...LeadPriority[]] = ["alta","baja","media"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.