import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import {useNavigate} from 'react-router-dom';
import {AppHeader} from '../components/AppHeader';
import {Button} from '../components/Button';
import {Skeleton} from '../components/Skeleton';
import {CommercialEditor} from '../components/CommercialEditor';
import {DataImportDialog} from '../components/DataImportDialog';
import {FilterBuilderDialog,FilterLegend,type FilterFieldDefinition} from '../components/FilterBuilderDialog';
import {BusinessListTools} from '../components/BusinessListTools';
import {BusinessListOptions} from '../components/BusinessListOptions';
import {getLeads,type OutputType} from '../endpoints/leads_GET.schema';
import {getSettings} from '../endpoints/settings_GET.schema';
import {getBusinessListDefaults} from '../endpoints/business_list_defaults.schema';
import {useAuth} from '../helpers/useAuth';
import {formatDate} from '../helpers/crmDates';
import {useDebounce} from '../helpers/useDebounce';
import {BUSINESS_COLUMNS,BUSINESS_FILTER_COLUMNS,legacyFilterLabels,effectivePins,initialPreferences,readPersonalPreferences,savePersonalPreferences,type ListPreferences,type ListContext} from '../helpers/businessListPreferences';
import {toast} from 'sonner';
import styles from './business-list.module.css';
export default function BusinessListPage(){const {authState}=useAuth();const defaults=useQuery({queryKey:['business-list-defaults'],queryFn:getBusinessListDefaults,refetchOnWindowFocus:false});const [ready,setReady]=useState(false);useEffect(()=>{if(defaults.isSuccess&&!defaults.isFetching)setReady(true);},[defaults.isSuccess,defaults.isFetching]);if(authState.type!=='authenticated')return null;
 return <><AppHeader/>{defaults.isPending||!ready&&!defaults.error?<main className={styles.shell} aria-busy="true"><h1>Negocios</h1><p>Cargando preferencias del equipo…</p><Skeleton className={styles.skeleton}/></main>:defaults.error?<main className={styles.shell}><p role="alert">No pude cargar los valores del equipo: {defaults.error.message}</p><Button onClick={()=>defaults.refetch()}>Reintentar</Button></main>:<BusinessList key={authState.user.id} userId={authState.user.id} admin={authState.user.role==='admin'} defaults={defaults.data!}/>}</>;
}
function BusinessList({userId,admin,defaults}:{userId:number;admin:boolean;defaults:Awaited<ReturnType<typeof getBusinessListDefaults>>}){
 const navigate=useNavigate(),qc=useQueryClient();
 const [initial]=useState(()=>{const personal=readPersonalPreferences(userId);return personal??{preferences:initialPreferences(defaults.defaults??undefined,window.innerWidth<768),context:{page:1,scrollY:0,scrollX:0} as ListContext};});
 const [prefs,setPrefs]=useState(initial.preferences),[page,setPage]=useState(initial.context.page),[viewport,setViewport]=useState(window.innerWidth),[containerWidth,setContainerWidth]=useState(window.innerWidth);
 const [editor,setEditor]=useState(false),[importOpen,setImportOpen]=useState(false),[filterOpen,setFilterOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[fullscreen,setFullscreen]=useState(false),[storageError,setStorageError]=useState(false);
 const scroll=useRef<HTMLDivElement>(null),sentinel=useRef<HTMLDivElement>(null),restore=useRef<ListContext|null>(initial.context),lastAnchor=useRef(initial.context.anchorId),lastContext=useRef(initial.context);
 const state=useRef({prefs,page});state.current={prefs,page};
 useEffect(()=>{if(!fullscreen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setFullscreen(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[fullscreen]);
 const query=useDebounce(prefs.query,300);
 const request={...prefs.legacyFilters,entity:'business' as const,q:query,filterGroups:prefs.filters,sortBy:prefs.sortBy,sortDir:prefs.sortDir,pageSize:prefs.pageSize};
 const results=useInfiniteQuery({queryKey:['leads','business-list',userId,request,prefs.loadMode,prefs.loadMode==='pages'?page:0],initialPageParam:prefs.loadMode==='pages'?page:1,queryFn:({pageParam})=>getLeads({...request,page:pageParam,anchorAccountId:prefs.loadMode==='pages'||pageParam===1?restore.current?.anchorId:undefined,alignAnchorPage:prefs.loadMode==='pages'&&!!restore.current?.anchorId}),getNextPageParam:(last)=>last.page*last.pageSize<last.total?last.page+1:undefined});
 const settings=useQuery({queryKey:['settings'],queryFn:getSettings});
 const rows=results.data?.pages.flatMap(p=>p.rows)??[],total=results.data?.pages[0]?.total??0;
 const busy=results.isFetching&&!results.isFetchingNextPage||query!==prefs.query;
 const capture=()=>{const {prefs,page}=state.current;const anchors=Array.from(document.querySelectorAll<HTMLElement>('[data-business-id]'));const anchor=anchors.find(e=>e.getBoundingClientRect().bottom>0);if(!anchors.length){const ok=savePersonalPreferences(userId,prefs,{...lastContext.current,page});setStorageError(!ok);return ok;}const context={page,scrollY:window.scrollY,scrollX:scroll.current?.scrollLeft??0,anchorId:lastAnchor.current??anchor?.dataset.businessId,anchorOffset:lastAnchor.current?document.querySelector<HTMLElement>(`[data-business-id="${lastAnchor.current}"]`)?.getBoundingClientRect().top:anchor?.getBoundingClientRect().top};lastContext.current=context;const ok=savePersonalPreferences(userId,prefs,context);setStorageError(!ok);return ok;};
 useEffect(()=>{const resize=()=>setViewport(window.innerWidth);window.addEventListener('resize',resize);window.addEventListener('pagehide',capture);let frame=0;const onScroll=()=>{if(!restore.current&&!frame)frame=requestAnimationFrame(()=>{frame=0;capture();});};window.addEventListener('scroll',onScroll,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',onScroll);capture();window.removeEventListener('resize',resize);window.removeEventListener('pagehide',capture);};},[userId]);
 useEffect(()=>{if(!restore.current)capture();},[prefs,page]);
 useLayoutEffect(()=>{
  if(prefs.loadMode!=='pages'||busy||results.error||!results.data)return;
  const lastPage=Math.min(results.data.pages[0].page,Math.max(1,Math.ceil(total/prefs.pageSize)));
  if(page!==lastPage){if(restore.current)restore.current={...restore.current,page:lastPage};setPage(lastPage);}
 },[prefs.loadMode,prefs.pageSize,busy,results.error,results.data,page,total]);
 useLayoutEffect(()=>{
  const target=restore.current;if(!target||busy||!results.data)return;
  if(prefs.loadMode==='pages'&&(page!==target.page||results.data.pages[0].page!==target.page))return;
  if(prefs.loadMode==='continuous'&&results.data.pages[0].anchorPage)target.page=results.data.pages[0].anchorPage;
  if(prefs.loadMode==='continuous'&&results.data.pages.at(-1)!.page<target.page&&results.hasNextPage){if(!results.isFetchingNextPage)void results.fetchNextPage();return;}
  const anchor=target.anchorId?document.querySelector<HTMLElement>(`[data-business-id="${target.anchorId}"]`):null;
  window.scrollTo(0,anchor?window.scrollY+anchor.getBoundingClientRect().top-(target.anchorOffset??0):target.scrollY);if(scroll.current)scroll.current.scrollLeft=target.scrollX;
  if(anchor)Array.from(anchor.querySelectorAll<HTMLButtonElement>('button')).find(button=>button.textContent==='Abrir')?.focus({preventScroll:true});
  restore.current=null;
 },[busy,results.data,results.isFetchingNextPage,prefs.loadMode]);
 useEffect(()=>{if(prefs.loadMode!=='continuous'||busy||restore.current||results.error||!results.hasNextPage)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&!results.isFetchingNextPage)void results.fetchNextPage();},{rootMargin:'150px'});if(sentinel.current)observer.observe(sentinel.current);return()=>observer.disconnect();},[prefs.loadMode,busy,results.hasNextPage,results.isFetchingNextPage,results.data,results.error]);
 useEffect(()=>{if(prefs.loadMode==='continuous'&&results.data&&!restore.current)setPage(results.data.pages.at(-1)!.page);},[results.data,prefs.loadMode]);
 const change=(next:ListPreferences,reset=false)=>{restore.current=null;lastAnchor.current=undefined;setPrefs(next);if(reset){setSelected([]);lastContext.current={page:1,scrollY:0,scrollX:0};setPage(1);}};
 const open=(row:OutputType['rows'][number])=>{lastAnchor.current=String(row.accountId);capture();navigate('/accounts/'+row.accountId);};
 const fields:FilterFieldDefinition[]=BUSINESS_FILTER_COLUMNS.map(c=>({key:c.key as FilterFieldDefinition['key'],label:c.label,kind:['fechaCreacion','fechaUltimoContacto','fechaProximaAccion','createdAt','updatedAt'].includes(c.key)?'date':c.key==='id'?'number':c.key==='clientePotencialRecurrente'?'boolean':c.key==='notes'?'notes':'text'}));
 for(const field of fields){if(field.key==='assignedUserEmail'){field.kind='category';field.options=settings.data?.users.map(u=>({value:u.email,label:u.displayName||u.email}))??[];}if(field.key==='ciudad'){field.kind='category';field.options=settings.data?.cities.map(c=>({value:c.name,label:c.name}))??[];}}
 for(const field of fields){const choices=field.key==='tipo'?settings.data?.types:field.key==='subtipo'?settings.data?.subtypes.map(v=>v.name):field.key==='estado'?settings.data?.opportunityStages:field.key==='commercialProfile'?['Independiente','Consolidado','Referente']:field.key==='prioridad'?['alta','media','baja']:undefined;if(choices){field.kind='category';field.options=choices.map(v=>({value:v,label:v}));}}
 useLayoutEffect(()=>{const node=scroll.current;if(!node)return;const observer=new ResizeObserver(()=>setContainerWidth(node.clientWidth));observer.observe(node);return()=>observer.disconnect();},[prefs.presentation]);
 const pins=effectivePins(prefs,Math.min(viewport,containerWidth));const pinnedStyle=(key:string):React.CSSProperties=>pins[key]?{[pins[key].side]:pins[key].offset}:{};
 const value=(row:OutputType['rows'][number],key:string)=>{if(key==='assignedUserEmail')return settings.data?.users.find(u=>u.email===row.assignedUserEmail)?.displayName||row.assignedUserEmail||'Sin responsable';if(key==='fechaProximaAccion')return row.fechaProximaAccion?`${row.nextActionTitle||'Próximo paso'} · ${formatDate(row.fechaProximaAccion)}`:'Sin próximo paso';if(row.opportunityCount!==1&&!['nombre','contactName','tipo','subtipo','ciudad','assignedUserEmail','email','telefono','sitioWeb','urlGmap','perfilInstagram','perfilFacebook','perfilAirbnb','perfilBooking','perfilTurismoEntreRios','createdAt','updatedAt','fechaUltimoContacto'].includes(key)&&row.opportunityValues?.[key])return row.opportunityValues[key].join(' · ')||'—';const v=row[key as keyof typeof row];if(key==='nombre')return <><Button variant="ghost" size="sm" onClick={()=>open(row)}>{row.nombre}</Button><small style={{display:'block'}}>{row.opportunityCount??0} gestiones · {row.contactCount??0} contactos · {row.commercialStatus==='client'?'Cliente':'Potencial cliente'}</small></>;if(v instanceof Date)return v.toLocaleDateString('es-AR');return v===true?'Sí':v===false?'No':String(v??'—');};
 const hasFilters=Boolean(prefs.query.trim()||prefs.filters.length||(prefs.legacyFilters&&legacyFilterLabels(prefs.legacyFilters).length));
 const renderRows=busy?[]:rows;
 const skeletons=Array.from({length:prefs.pageSize},(_,i)=>i);
 return <main className={styles.shell} style={fullscreen?{position:'fixed',inset:0,zIndex:60,overflow:'auto',background:'var(--background)',maxWidth:'none'}:undefined}>
 <div className={styles.heading}><div><h1>Negocios</h1><p>Establecimientos y sus datos. Abrí un negocio para consultar qué pasó y cómo continuar.</p></div><Button onClick={()=>setEditor(true)}>Nuevo negocio</Button></div>
 {storageError&&<p role="alert">No pude guardar las preferencias en este navegador. Podés seguir trabajando, pero al volver podrían perderse.</p>}
 <section className={styles.panel}><div className={styles.toolbar}>
 <label className={styles.search}>Buscar negocios<input value={prefs.query} onChange={e=>change({...prefs,query:e.target.value},true)} placeholder="Buscar negocios, gestiones y notas…"/></label>
 <Button variant="outline" onClick={()=>setFilterOpen(true)}>Filtrar negocios</Button>
 <label>Ordenar por<select value={prefs.sortBy} onChange={e=>change({...prefs,sortBy:e.target.value as ListPreferences['sortBy']},true)}>{BUSINESS_FILTER_COLUMNS.filter(c=>c.key!=='notes').map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label>
 <label>Dirección<select value={prefs.sortDir} onChange={e=>change({...prefs,sortDir:e.target.value as 'asc'|'desc'},true)}><option value="asc">Ascendente</option><option value="desc">Descendente</option></select></label>
 </div><div className={styles.toolbar}>
 <div><Button variant={prefs.presentation==='table'?'primary':'outline'} aria-pressed={prefs.presentation==='table'} onClick={()=>change({...prefs,presentation:'table'})}>Tabla</Button> <Button variant={prefs.presentation==='grid'?'primary':'outline'} aria-pressed={prefs.presentation==='grid'} onClick={()=>change({...prefs,presentation:'grid'})}>Grilla</Button></div>
 <label>Resultados por página o lote<select value={prefs.pageSize} onChange={e=>change({...prefs,pageSize:Number(e.target.value)},true)}>{Array.from(new Set([10,25,50,100,prefs.pageSize])).sort((a,b)=>a-b).map(n=><option key={n} value={n}>{n}</option>)}</select></label>
 <label>Forma de carga<select value={prefs.loadMode} onChange={e=>change({...prefs,loadMode:e.target.value as ListPreferences['loadMode']},true)}><option value="pages">Paginación</option><option value="continuous">Carga continua</option></select></label>
 <Button variant="outline" onClick={()=>change({...prefs,query:'',filters:[],legacyFilters:undefined},true)}>Limpiar filtros</Button>
 <Button variant="outline" onClick={()=>change(initialPreferences(defaults.defaults??undefined,viewport<768),true)}>Restablecer valores del equipo</Button>
 <Button variant="outline" onClick={()=>setFullscreen(v=>!v)}>{fullscreen?'Salir de pantalla completa':'Pantalla completa'}</Button>
 </div>
 {(defaults.defaults?.presets.length??0)>0&&<label>Filtros preestablecidos<select value="" onChange={e=>{const preset=defaults.defaults!.presets.find(p=>p.id===e.target.value);if(preset)change({...prefs,filters:preset.filters,query:preset.query??'',legacyFilters:undefined},true);}}><option value="">Elegir un filtro…</option>{defaults.defaults!.presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 <FilterLegend groups={prefs.filters} search={prefs.query} fields={fields} onEdit={()=>setFilterOpen(true)} onClear={()=>change({...prefs,query:'',filters:[],legacyFilters:undefined},true)}/>

 {prefs.legacyFilters&&<details><summary>Filtros adicionales de la vista guardada</summary><p>Esta vista conserva los filtros de su versión anterior. Limpiar filtros o aplicar nuevos filtros permite reemplazarlos.</p>{legacyFilterLabels(prefs.legacyFilters).map((label,i)=><p key={i}>{label}</p>)}</details>}
 <BusinessListOptions value={prefs} onChange={v=>change(v)}/></section>
 <BusinessListTools userId={userId} admin={admin} prefs={prefs} onChange={p=>change(p,true)} onImport={()=>setImportOpen(true)} selected={selected} onClear={()=>setSelected([])}/>
 <p role="status" aria-live="polite" className={styles.status}>{busy?'Cargando negocios…':`${results.isFetchingNextPage?'Cargando más negocios… · ':''}${rows.length} de ${total} negocios cargados`}{!busy&&prefs.loadMode==='continuous'&&!results.hasNextPage&&' · No hay más resultados'}</p>
 {results.error&&<div className={styles.error} role="alert">No pude cargar los negocios: {results.error.message} <Button disabled={results.isFetching} onClick={()=>results.isFetchNextPageError?results.fetchNextPage():results.refetch()}>Reintentar</Button></div>}
 <section aria-label="Resultados de negocios" aria-busy={busy||results.isFetchingNextPage}>
 {prefs.presentation==='grid'?<div className={styles.grid}>{(busy?skeletons:renderRows).map((row,i)=>typeof row==='number'?<article className={styles.card} key={i}>{prefs.columns.map(k=><Skeleton key={k} className={styles.skeleton}/>)}</article>:<article id={'business-'+row.accountId} data-business-id={row.accountId} key={row.accountId} className={styles.card+' '+(lastAnchor.current===String(row.accountId)?styles.active:'')}><h2>{row.nombre}</h2><label><input type="checkbox" aria-label={'Seleccionar '+row.nombre} disabled={row.canModify===false} checked={selected.includes(String(row.accountId))} onChange={()=>setSelected(v=>v.includes(String(row.accountId))?v.filter(id=>id!==String(row.accountId)):[...v,String(row.accountId)])}/>Seleccionar</label><dl>{prefs.columns.filter(k=>k!=='nombre').map(k=><div key={k}><dt>{BUSINESS_COLUMNS.find(c=>c.key===k)!.label}</dt><dd>{value(row,k)}</dd></div>)}</dl><Button variant="outline" onClick={()=>open(row)}>Abrir</Button></article>)}{results.isFetchingNextPage&&skeletons.map(i=><article className={styles.card} key={'next'+i}><Skeleton className={styles.skeleton}/><Skeleton className={styles.skeleton}/></article>)}</div>:<div ref={scroll} className={styles.scroll} onScroll={()=>capture()}><table className={styles.table} style={{width:'100%',minWidth:prefs.columns.reduce((sum,k)=>sum+(prefs.widths[k]??160),154)}}><colgroup><col style={{width:44}}/>{prefs.columns.map(k=><col key={k} style={{width:prefs.widths[k]??160}}/>)}<col style={{width:110}}/></colgroup><thead><tr><th scope="col">Elegir</th>{prefs.columns.map(k=><th key={k} className={pins[k]?styles.pinned:''} style={pinnedStyle(k)} scope="col"><Button size="sm" variant="ghost" onClick={()=>change({...prefs,sortBy:k as ListPreferences['sortBy'],sortDir:prefs.sortBy===k&&prefs.sortDir==='asc'?'desc':'asc'},true)}>{BUSINESS_COLUMNS.find(c=>c.key===k)!.label}{prefs.sortBy===k?(prefs.sortDir==='asc'?' ↑':' ↓'):''}</Button></th>)}<th scope="col">Acción</th></tr></thead><tbody>{busy?skeletons.map(i=><tr key={i}>{['select',...prefs.columns,'action'].map(k=><td key={k}><Skeleton className={styles.skeleton}/></td>)}</tr>):renderRows.map(row=><tr data-business-id={row.accountId} key={row.accountId} className={lastAnchor.current===String(row.accountId)?styles.active:''}><td><input type="checkbox" aria-label={'Seleccionar '+row.nombre} disabled={row.canModify===false} checked={selected.includes(String(row.accountId))} onChange={()=>setSelected(v=>v.includes(String(row.accountId))?v.filter(id=>id!==String(row.accountId)):[...v,String(row.accountId)])}/></td>{prefs.columns.map(k=><td key={k} className={pins[k]?styles.pinned:''} style={pinnedStyle(k)}>{value(row,k)}</td>)}<td><Button size="sm" variant="outline" onClick={()=>open(row)}>Abrir</Button></td></tr>)}{results.isFetchingNextPage&&skeletons.map(i=><tr key={'next'+i}>{['select',...prefs.columns,'action'].map(k=><td key={k}><Skeleton className={styles.skeleton}/></td>)}</tr>)}</tbody></table></div>}
 </section>
 {!busy&&!results.error&&rows.length===0&&<section className={styles.panel}><h2>{hasFilters?'Sin resultados por los filtros actuales':'Sin negocios cargados'}</h2><p>{hasFilters?'Revisá la búsqueda y los filtros.':'Cargá un establecimiento para comenzar.'}</p><Button onClick={()=>hasFilters?change({...prefs,query:'',filters:[],legacyFilters:undefined},true):setEditor(true)}>{hasFilters?'Limpiar filtros':'Nuevo negocio'}</Button></section>}
 {prefs.loadMode==='pages'?<nav aria-label="Paginación de negocios" className={styles.pagination}><Button variant="outline" disabled={page<=1||busy} onClick={()=>{lastAnchor.current=undefined;setPage(p=>p-1);}}>Anterior</Button><span>Página {page} de {Math.max(1,Math.ceil(total/prefs.pageSize))}</span><Button variant="outline" disabled={page*prefs.pageSize>=total||busy} onClick={()=>{lastAnchor.current=undefined;setPage(p=>p+1);}}>Siguiente</Button></nav>:<div ref={sentinel} className={styles.pagination}><Button variant="outline" disabled={!results.hasNextPage||results.isFetchingNextPage||busy} onClick={()=>results.fetchNextPage()}>{results.isFetchingNextPage?'Cargando más negocios…':'Cargar más'}</Button></div>}
 <FilterBuilderDialog open={filterOpen} onOpenChange={setFilterOpen} fields={fields} value={prefs.filters} search={prefs.query} title="Filtrar negocios" onApply={(filters,query)=>change({...prefs,filters,query,legacyFilters:undefined},true)}/>
 {editor&&<CommercialEditor target={{kind:'account'}} onClose={()=>setEditor(false)} onSaved={id=>{void qc.invalidateQueries({queryKey:['leads']});toast.success('Negocio guardado');capture();navigate('/accounts/'+id);}}/>}
 {importOpen&&<DataImportDialog onClose={()=>setImportOpen(false)}/>}
 </main>;
}
