import React from 'react';
import {Link} from 'react-router-dom';
import {AppHeader} from '../components/AppHeader';
import styles from '../components/Commercial.module.css';
const steps=[
 ['1. Agregá el negocio','Entrá en Negocios y elegí Nuevo negocio. Escribí el nombre; la ciudad y los demás datos se pueden completar después. Guardá. Buscá primero si ya existe para evitar duplicados.','/accounts','Ir a Negocios'],
 ['2. Agregá con quién vas a hablar','Abrí el negocio. En Contactos, elegí Agregar contacto y escribí el nombre, teléfono o email. Principal significa que esa persona es la referencia habitual. No hace falta conocer su cargo para empezar.','/accounts','Buscar un negocio'],
 ['3. Prepará una venta','En el resumen del negocio, elegí Crear una venta. Poné un nombre concreto, por ejemplo Publicación de cabañas. Una venta es una propuesta que queremos concretar; un negocio puede tener varias. Elegí su persona de contacto.','/opportunities','Ver las ventas'],
 ['4. Dejá el próximo paso con fecha','Elegí Planificar próximo paso. Escribí algo concreto: Llamar a Ana para conocer sus necesidades. Elegí fecha y guardá. La tarea aparecerá en Mi día cuando corresponda. Si aún no conocés a la persona, el primer paso puede ser averiguar quién decide.','/my-day','Abrir Mi día'],
 ['5. Contactá y escuchá','En la tarea, elegí Contactar. Revisá la persona y el canal: llamada, WhatsApp o email. Preguntá qué necesita y si quiere recibir una propuesta. Los mensajes modelo son una ayuda: revisá destinatario y contenido antes de enviarlos. Abrir WhatsApp no significa que el mensaje se haya enviado.','/my-day','Ver mis tareas'],
 ['6. Registrá qué pasó','Después de hablar, elegí Registrar qué pasó en la tarea. Seleccioná el resultado y escribí las notas útiles. Podés planificar el próximo paso en el mismo formulario. Si no respondió, acordá cuándo intentar de nuevo. Si pidió no recibir más contactos, elegí Pidió que no lo contactemos.','/my-day','Registrar una acción'],
 ['7. Acompañá la decisión','Abrí la venta y consultá Cómo avanzar con esta venta: Contacto, Necesidad, Propuesta y Decisión. Es una guía; abrir un paso no cambia la etapa. Revisá su etapa. Una etapa indica en qué punto está: contacto, propuesta, decisión o cierre. Los nombres pueden variar según la configuración de Hospeda. Prepará materiales en Documentos y acordá siempre una próxima acción. Las secuencias son listas de tareas y borradores; no envían mensajes automáticamente.','/opportunities','Abrir una venta'],
 ['8. Cerrá con el resultado real','Si aceptó la propuesta, elegí una etapa Ganada. En Acuerdo y entrega anotá qué se acordó, quién aceptó, el material, el responsable y la fecha conocida. Lo desconocido queda por confirmar. Podés marcar al negocio como cliente y dejar una tarea de acompañamiento. Ganada y Cliente no prueban que haya pagado: registrá o verificá el pago por el procedimiento del equipo. Si no acepta, usá una etapa Perdida, anotá el motivo y, si corresponde, una fecha para retomarla.','/opportunities','Revisar ventas'],
 ['9. Seguí acompañando al cliente','Desde el resumen del negocio, planificá una tarea para comprobar que recibió lo acordado y preguntar cómo le está yendo. Registrá cada conversación. No abras otra venta para hacer seguimiento de lo que ya se vendió: usá una tarea general o vinculada a esa venta.','/accounts','Abrir un cliente'],
 ['10. Ofrecé algo más cuando tenga sentido','En el mismo negocio elegí Ofrecer otra venta. Describí la nueva propuesta y elegí su contacto. La venta anterior conserva su cierre y su historial. Ser cliente no impide gestionar otra venta. Antes de contactar, revisá lo último que habló el equipo y respetá las restricciones.','/accounts','Preparar otra venta'],
];
export default function GuidePage(){return <><AppHeader/><main className={styles.shell}><h1>Usar Hospeda, paso a paso</h1><p>No necesitás experiencia con ventas ni con un CRM. Esta herramienta sirve para recordar con quién hablaste, qué acordaron y qué hay que hacer después.</p><section className={styles.panel}><h2>Para empezar hoy</h2><p>Entrá en Mi día. Primero revisá las tareas vencidas, después las de hoy. Abrí una tarea, contactá a la persona y registrá el resultado. Al terminar, dejá el próximo paso con fecha.</p><Link to="/my-day">Ir a Mi día →</Link></section><nav aria-label="Pasos de la guía"><ol>{steps.map(([title],i)=><li key={title}><a href={'#step-'+i}>{title.slice(3)}</a></li>)}</ol></nav>{steps.map(([title,text,url,label],i)=><section id={'step-'+i} key={title} className={styles.panel}><h2>{title}</h2><p>{text}</p><Link to={url}>{label} →</Link></section>)}<section className={styles.panel}><h2>Si algo te frena</h2><ul><li><strong>No hay teléfono o email:</strong> abrí el negocio y agregá el canal de la persona o del negocio.</li><li><strong>No aparece una tarea:</strong> revisá su fecha, el responsable y los filtros. Agenda muestra las acciones que el equipo configuró para el calendario.</li><li><strong>No podés editar:</strong> puede ser una venta o tarea asignada a otra persona. Consultá al responsable o administrador.</li><li><strong>Los datos parecen viejos:</strong> elegí Actualizar. En la flecha de al lado podés activar Actualizar automáticamente para ver los cambios del equipo.</li><li><strong>Hay cambios sin guardar:</strong> seguí editando y guardá antes de salir. Descartar elimina solo los cambios que aún no guardaste.</li><li><strong>El email tiene resultado incierto:</strong> revisá el historial con el administrador antes de reenviarlo para evitar duplicarlo.</li><li><strong>Hay dos negocios iguales:</strong> pedí al administrador que revise los duplicados y conserve el historial.</li></ul></section><section className={styles.panel}><h2>Revisar antes de modificar varios registros</h2><p>Al aplicar un cambio masivo se abre una lista completa de los registros afectados. Revisala antes de confirmar: al seleccionar negocios se pueden modificar ventas que el filtro no mostraba. Si los datos cambiaron, volvé a revisar. Cancelar no modifica datos.</p></section><section className={styles.panel}><h2>Palabras que vas a encontrar</h2><dl><dt>Negocio</dt><dd>La empresa o establecimiento con el que nos relacionamos.</dd><dt>Contacto</dt><dd>Una persona de ese negocio.</dd><dt>Venta u oportunidad</dt><dd>Una propuesta concreta que queremos que acepte.</dd><dt>Tarea</dt><dd>Algo que falta hacer, con una fecha.</dd><dt>Actividad</dt><dd>Algo que ya hicimos y dejamos registrado.</dd><dt>Responsable</dt><dd>La persona del equipo encargada de esa relación, venta o tarea.</dd><dt>Historial</dt><dd>El registro de lo ocurrido, que se conserva aunque otra venta empiece.</dd></dl></section></main></>}
