import React,{useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Bookmark,Trash2} from 'lucide-react';
import viewStyles from './BusinessListTools.module.css';
import {Button} from './Button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './Dialog';
import {getLeadDuplicates} from '../endpoints/leads_duplicates_GET.schema';
import {AccountMergeDialog} from './AccountMergeDialog';
import {BulkChangeReview} from './BulkChangeReview';
import {postLeadsBulk,type InputType} from '../endpoints/leads_bulk_POST.schema';
import {postLeadsBulkDelete} from '../endpoints/leads_bulk_delete_POST.schema';
import {getSavedLeadViews} from '../endpoints/saved_views_GET.schema';
import {postSavedLeadView} from '../endpoints/saved_views_POST.schema';
import {getSettings} from '../endpoints/settings_GET.schema';
import {preferencesFromSavedView,type ListPreferences} from '../helpers/businessListPreferences';
import {toast} from 'sonner';
import styles from '../pages/business-list.module.css';
export function BusinessListTools({saveDialog,onSaveDialogChange:setSaveDialog,userId,admin,prefs,onChange,selected,onClear,duplicatesOpen:duplicates,onDuplicatesOpenChange:setDuplicates}:{saveDialog:boolean;onSaveDialogChange:(open:boolean)=>void;userId:number;admin:boolean;prefs:ListPreferences;onChange:(p:ListPreferences)=>void;selected:string[];onClear:()=>void;duplicatesOpen:boolean;onDuplicatesOpenChange:(open:boolean)=>void}){
 const qc=useQueryClient();const [pair,setPair]=useState<{sourceId:string;destinationId:string}|null>(null),[viewName,setViewName]=useState(''),[field,setField]=useState('ciudad'),[value,setValue]=useState(''),[review,setReview]=useState<InputType|null>(null),[remove,setRemove]=useState(false);
 const viewLatch=useRef(false);const latch=useRef(false);const dup=useQuery({queryKey:['lead-duplicates'],queryFn:getLeadDuplicates,enabled:admin&&duplicates});const settings=useQuery({queryKey:['settings'],queryFn:getSettings});const views=useQuery({queryKey:['business-saved-views',userId],queryFn:getSavedLeadViews});
 const save=useMutation({mutationFn:postSavedLeadView,onSuccess:()=>qc.invalidateQueries({queryKey:['business-saved-views',userId]})});const bulk=useMutation({mutationFn:postLeadsBulk});const deletion=useMutation({mutationFn:postLeadsBulkDelete});
 const options=field==='ciudad'?settings.data?.cities.map(c=>({value:c.name,label:c.name})):field==='assignedUserEmail'?settings.data?.users.map(u=>({value:u.email,label:u.displayName||u.email})):field==='estado'?settings.data?.opportunityStages.map(v=>({value:v,label:v})):field==='tipo'?settings.data?.types.map(v=>({value:v,label:v})):(field==='prioridad'?['alta','media','baja']:['Independiente','Consolidado','Referente']).map(v=>({value:v,label:v}));
 async function apply(fingerprint:string){if(latch.current)return;latch.current=true;try{await bulk.mutateAsync({...review!,expectedFingerprint:fingerprint});setReview(null);onClear();await qc.invalidateQueries({queryKey:['leads']});toast.success('Cambios guardados');}catch(e){toast.error((e as Error).message);}finally{latch.current=false;}}
 async function trash(){if(latch.current)return;latch.current=true;try{await deletion.mutateAsync({entity:'business',ids:selected});setRemove(false);onClear();await qc.invalidateQueries({queryKey:['leads']});toast.success('Gestiones enviadas a papelera');}catch(e){toast.error((e as Error).message);}finally{latch.current=false;}}
 return <>
 <div className={viewStyles.views}>
  <Bookmark size={16} aria-hidden="true"/><label className={viewStyles.viewLabel}><span>Vistas</span><select aria-label="Vistas guardadas" value="" disabled={views.isPending||!!views.error} onChange={e=>{const view=views.data?.views.find(v=>v.name===e.target.value);if(!view)return;const parsed=preferencesFromSavedView(prefs,view.config);if(parsed)onChange(parsed);else toast.error('No pude recuperar los filtros de esta vista. Revisala antes de usarla.');}}><option value="">{views.isPending?'Cargando vistas…':'Aplicar vista guardada…'}</option>{views.data?.views.filter(v=>!v.config.entity||v.config.entity==='business').map(v=><option key={v.name} value={v.name}>{v.name}</option>)}</select></label>
  {views.error&&<span role="alert">No pude cargar las vistas. <Button size="sm" variant="ghost" onClick={()=>views.refetch()}>Reintentar</Button></span>}
 </div>
 <Dialog open={saveDialog} onOpenChange={open=>{if(!viewLatch.current)setSaveDialog(open);}}><DialogContent><DialogTitle>Vistas guardadas</DialogTitle><DialogDescription>Guardá la búsqueda, los filtros y la presentación actuales para volver a usarlos.</DialogDescription>
  <form className={viewStyles.saveForm} onSubmit={async e=>{e.preventDefault();if(!viewName.trim()||viewLatch.current)return;viewLatch.current=true;try{await save.mutateAsync({action:'save',view:{name:viewName.trim(),config:{entity:'business',preferences:prefs}}});setViewName('');setSaveDialog(false);toast.success('Vista guardada');}catch{/* The mutation error remains visible in the dialog. */}finally{viewLatch.current=false;}}}>
   <label>Nombre de la vista<input autoFocus value={viewName} maxLength={80} disabled={save.isPending} onChange={e=>setViewName(e.target.value)}/></label>{save.error&&<p role="alert">{save.error.message}</p>}<div className={viewStyles.actions}><Button type="button" variant="outline" disabled={save.isPending} onClick={()=>setSaveDialog(false)}>Cancelar</Button><Button type="submit" disabled={!viewName.trim()||save.isPending}>{save.isPending?'Guardando vista…':'Guardar vista'}</Button></div>
  </form>
  {(views.data?.views.length??0)>0&&<section className={viewStyles.savedList} aria-label="Administrar vistas guardadas"><h3>Tus vistas</h3>{views.data!.views.filter(v=>!v.config.entity||v.config.entity==='business').map(v=><div key={v.name}><span>{v.name}</span><Button variant="ghost" size="icon-sm" aria-label={'Eliminar vista '+v.name} disabled={save.isPending} onClick={async()=>{if(viewLatch.current)return;viewLatch.current=true;try{await save.mutateAsync({action:'delete',name:v.name});toast.success('Vista eliminada');}catch{/* Keep the error beside the form. */}finally{viewLatch.current=false;}}}><Trash2 size={16} aria-hidden="true"/></Button></div>)}</section>}
 </DialogContent></Dialog>
 {selected.length>0&&<section aria-label="Modificar negocios seleccionados" className={styles.panel}><strong>{selected.length} seleccionados</strong><div className={styles.toolbar}><select aria-label="Campo a modificar" value={field} onChange={e=>{setField(e.target.value);setValue('');}}><option value="ciudad">Ciudad</option>{admin&&<option value="assignedUserEmail">Responsable</option>}<option value="estado">Etapa de las gestiones</option><option value="prioridad">Prioridad</option><option value="tipo">Vertical</option><option value="commercialProfile">Perfil comercial</option><option value="fechaProximaAccion">Próxima acción</option></select>
 {field==='fechaProximaAccion'?<input aria-label="Nueva fecha" type="date" value={value} onChange={e=>setValue(e.target.value)}/>:<select aria-label="Nuevo valor" value={value} onChange={e=>setValue(e.target.value)}><option value="">Elegir valor…</option>{['prioridad','commercialProfile','assignedUserEmail'].includes(field)&&<option value="__CLEAR__">Sin valor</option>}{options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}
 <p>{['ciudad','assignedUserEmail'].includes(field)?'Modifica los datos del negocio.':'Modifica todas las gestiones activas de los negocios seleccionados, incluso las que no coincidan con el filtro.'}</p>
 <Button disabled={!value||bulk.isPending} onClick={()=>{bulk.reset();setReview({entity:'business',ids:selected,changes:{[field]:value==='__CLEAR__'?null:value}});}}>Aplicar</Button><Button variant="outline" onClick={()=>setRemove(true)}>Enviar a papelera</Button><Button variant="outline" onClick={onClear}>Cancelar selección</Button></div></section>}
 {review&&<BulkChangeReview input={review} onClose={()=>setReview(null)} onConfirm={apply} pending={bulk.isPending} error={bulk.error?.message}/>}
 <Dialog open={remove} onOpenChange={v=>!deletion.isPending&&setRemove(v)}><DialogContent><DialogTitle>Enviar gestiones a papelera</DialogTitle><DialogDescription>Se retirarán todas las gestiones activas de los negocios seleccionados, aunque no coincidan con el filtro. Los negocios, personas y asignaciones se conservan.</DialogDescription>{deletion.error&&<p role="alert">{deletion.error.message}</p>}<Button disabled={deletion.isPending} onClick={trash}>{deletion.isPending?'Enviando a papelera…':'Confirmar'}</Button><Button disabled={deletion.isPending} onClick={()=>setRemove(false)}>Cancelar</Button></DialogContent></Dialog>
 <Dialog open={duplicates} onOpenChange={setDuplicates}><DialogContent><DialogTitle>Duplicados potenciales</DialogTitle><DialogDescription>Revisá si son el mismo establecimiento antes de fusionar.</DialogDescription>{dup.isFetching?<p>Cargando duplicados…</p>:dup.error?<p role="alert">{dup.error.message}</p>:dup.data?.groups.map((g,i)=><section key={i}><h3>{g.reason}</h3>{g.leads.map(l=><div key={l.accountId}><strong>{l.nombre}</strong><p>{l.email} · {l.telefono}</p>{admin&&g.leads.some(x=>x.accountId!==l.accountId)&&<Button onClick={()=>{setDuplicates(false);setPair({sourceId:l.accountId,destinationId:g.leads.find(x=>x.accountId!==l.accountId)!.accountId});}}>Revisar fusión</Button>}<Button variant="outline" onClick={()=>{setDuplicates(false);onChange({...prefs,query:l.nombre,filters:[]});}}>Ver en listado</Button></div>)}</section>)}{dup.data?.groups.length===0&&<p>No encontré duplicados.</p>}</DialogContent></Dialog>
 {pair&&<AccountMergeDialog {...pair} onClose={()=>setPair(null)}/>}
 </>;
}
