import {CrmDateInput} from './ui/CrmDateInput';
import {QueryErrorNotice} from './QueryErrorNotice';
import {QueryLoadingNotice} from './QueryLoadingNotice';
import {useGuardedMutation} from '../helpers/useGuardedMutation';
import {LiftRestrictionDialog,type RestrictionTarget} from './LiftRestrictionDialog';
import { Disclosure, DisclosureSummary } from './Disclosure';
import { NativeSelect } from './NativeSelect';
import { Input } from './Input';
import { Checkbox } from './Checkbox';
import {localDay} from '../helpers/workDates';
import React,{useState} from 'react';import {useQuery,useQueryClient} from '@tanstack/react-query';
import {getCommunication,postCommunication} from '../endpoints/communication.schema';import {getCommercialDetail} from '../endpoints/commercial.schema';import {useAuth} from '../helpers/useAuth';import {Button} from './Button';import {MessageComposer,messageLabels} from './MessageComposer';import styles from './Communication.module.css';
const runLabels:Record<string,string>={active:'Activa',paused:'Pausada',cancelled:'Cancelada',stopped:'Detenida',completed:'Completada'};
export function CommunicationPanel({leadId}:{leadId:string}){
 const {authState}=useAuth(),qc=useQueryClient();const q=useQuery({queryKey:['communication',leadId],queryFn:()=>getCommunication(leadId)});const detail=useQuery({queryKey:['commercial-detail','',leadId],queryFn:()=>getCommercialDetail(undefined,leadId)});
 const [liftTarget,setLiftTarget]=useState<RestrictionTarget|null>(null),[liftedNotice,setLiftedNotice]=useState<{id:string;text:string}|null>(null);
 const [person,setPerson]=useState(''),[channel,setChannel]=useState<'all'|'email'|'whatsapp'>('all'),[reason,setReason]=useState(''),[seq,setSeq]=useState(''),[confirm,setConfirm]=useState(false);
 const [control,setControl]=useState<{id:string;state:'paused'|'active'|'cancelled'}|null>(null),[controlReason,setControlReason]=useState(''),[resumeDate,setResumeDate]=useState(localDay());
 const m=useGuardedMutation({mutationFn:postCommunication,onSuccess:()=>{void qc.invalidateQueries({queryKey:['communication']});void qc.invalidateQueries({queryKey:['work']});setConfirm(false);setControl(null);setControlReason('')}});const admin=authState.type==='authenticated'&&authState.user.role==='admin';const userEmail=authState.type==='authenticated'?authState.user.email:'';const opp=detail.data?.opportunities.find(o=>String(o.id)===leadId);const canWrite=admin||opp?.assignedUserEmail===userEmail||detail.data?.account.assignedUserEmail===userEmail;
 if(!q.data&&q.isPending)return <QueryLoadingNotice>Cargando comunicación…</QueryLoadingNotice>;if(!q.data)return <QueryErrorNotice error={q.error!} onRetry={q.refetch} busy={q.isFetching}/>;
 return <section className={styles.panel}>{q.error&&<QueryErrorNotice error={q.error} onRetry={q.refetch} busy={q.isFetching}/>}<h3>Mensajes y seguimiento asistido</h3><p className={styles.muted}>Los seguimientos asistidos preparan tareas y borradores. Vos revisás cada mensaje y decidís cuándo enviarlo.</p>
 <Disclosure><DisclosureSummary>Restricciones de contacto</DisclosureSummary><div className={styles.panel}>{canWrite&&<><label>Persona<NativeSelect value={person} onChange={e=>setPerson(e.target.value)}><option value="">Contacto original de esta gestión</option>{detail.data?.contacts.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><label>Canal<NativeSelect aria-label="Canal de restricción" value={channel} onChange={e=>setChannel(e.target.value as any)}><option value="all">Todos</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option></NativeSelect></label><label>Motivo de restricción<Input value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={reason.trim().length<3||m.isPending} onClick={()=>m.mutate({action:'restrict',leadId,contactId:person||null,channel,reason})}>Bloquear contacto/canal</Button></>}
 {q.data.restrictions.map(r=><article key={r.id}><strong>{r.channel} · {r.liftedAt?'Levantada':'No contactar'}</strong><p>{r.contactId?detail.data?.contacts.find(c=>String(c.id)===String(r.contactId))?.name:'Contacto original #'+r.leadId} · {r.reason} · {r.actorEmail} · {new Date(r.createdAt).toLocaleString('es-AR')}</p>{r.liftedAt?<p>{r.liftReason} · {r.liftedBy} · {new Date(r.liftedAt).toLocaleString('es-AR')}</p>:admin&&<Button variant="outline" disabled={m.isPending} onClick={()=>{setLiftedNotice(null);setLiftTarget({id:String(r.id),channel:r.channel,reason:r.reason,contact:r.contactId?detail.data?.contacts.find(c=>String(c.id)===String(r.contactId))?.name||'Contacto #'+r.contactId:'Contacto original de esta gestión'})}}>Levantar restricción</Button>}</article>)}</div></Disclosure>
 <Disclosure><DisclosureSummary>Iniciar secuencia</DisclosureSummary><div className={styles.panel}>{canWrite&&<><label>Persona<NativeSelect value={person} onChange={e=>setPerson(e.target.value)}><option value="">Contacto original de esta gestión</option>{detail.data?.contacts.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label><label>Secuencia<NativeSelect aria-label="Secuencia" value={seq} onChange={e=>setSeq(e.target.value)}><option value="">Elegir</option>{q.data.sequences.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</NativeSelect></label>{q.data.sequences.filter(s=>String(s.id)===seq).map(s=><p key={s.id}>{s.scope} · {s.steps.map((p:any,i:number)=>`Paso ${i+1}: esperar ${p.waitDays} días, ${p.channel}`).join(' / ')}</p>)}<label className={styles.check}><Checkbox  checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Confirmo la generación de tareas y borradores</label><Button disabled={!seq||!confirm||m.isPending} onClick={()=>m.mutate({action:'sequence_start',id:crypto.randomUUID(),sequenceId:seq,leadId,contactId:person||null,confirm:true})}>Iniciar seguimiento asistido</Button></>}
 {q.data.runs.map(r=><article key={r.id}><strong>{r.snapshot.name} · {runLabels[r.status]}</strong><p>{r.reason} · {r.ownerEmail} · {new Date(r.createdAt).toLocaleString('es-AR')}</p>{canWrite&&['active','paused'].includes(r.status)&&<div className={styles.actions}>{['paused','active','cancelled'].filter(s=>s!==r.status).map(s=><Button key={s} variant="outline" disabled={m.isPending} onClick={()=>{setControl({id:r.id,state:s as 'paused'|'active'|'cancelled'});setResumeDate(localDay());setControlReason('')}}>{s==='paused'?'Pausar':s==='active'?'Reanudar':'Cancelar'}</Button>)}</div>}</article>)}</div></Disclosure>
 {admin&&<p><a href="/settings?section=communication">Configurar los seguimientos del equipo</a></p>}
 {control&&<form className={styles.panel} onSubmit={e=>{e.preventDefault();m.mutate({action:'sequence_control',...control,reason:controlReason,...(control.state==='active'?{resumeDate}:{})})}}><h4>{control.state==='active'?'Reanudar seguimiento':control.state==='paused'?'Pausar seguimiento':'Cancelar seguimiento'}</h4><label>Motivo<Input required minLength={3} maxLength={1000} value={controlReason} onChange={e=>setControlReason(e.target.value)}/></label>{control.state==='active'&&<><label>Fecha del próximo paso<CrmDateInput required  min={localDay()} value={resumeDate} onValueChange={e=>setResumeDate(e)}/></label><p>Las tareas restantes se reprograman desde esta fecha, respetando los intervalos entre pasos. No se envían mensajes.</p></>}<div className={styles.actions}><Button type="submit" disabled={m.isPending}>Guardar cambio</Button><Button variant="outline" onClick={()=>setControl(null)}>Volver</Button></div></form>}
 {liftedNotice&&<p role="status" tabIndex={-1} data-lifted-restriction={liftedNotice.id}>{liftedNotice.text}</p>}
 {admin&&liftTarget&&<LiftRestrictionDialog key={liftTarget.id} target={liftTarget} onClose={()=>setLiftTarget(null)} onLifted={()=>{setLiftedNotice({id:liftTarget.id,text:'Restricción levantada. No se enviaron mensajes ni se reanudaron seguimientos.'});setLiftTarget(null)}}/>}
 <h4>Mensajes y borradores ({q.data.messages.length})</h4>{q.data.messages.map(msg=><Disclosure key={msg.id}><DisclosureSummary>{messageLabels[msg.status]??msg.status} · {msg.channel} · {msg.recipient} · {new Date(msg.createdAt).toLocaleString('es-AR')}</DisclosureSummary>{canWrite&&(admin||msg.ownerEmail===userEmail)?<MessageComposer key={msg.id} initial={msg}/>:<p>{msg.subject} · {msg.textBody||msg.body}</p>}</Disclosure>)}{m.error&&<p role="alert">{m.error.message}</p>}
 </section>;
}
