import superjson from 'superjson';
import React,{useState} from 'react';import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {getCommunication,postCommunication} from '../endpoints/communication.schema';import {getCommercialDetail} from '../endpoints/commercial.schema';import {useAuth} from '../helpers/useAuth';import {Button} from './Button';import {MessageComposer,messageLabels} from './MessageComposer';import styles from './Communication.module.css';
const runLabels:Record<string,string>={active:'Activa',paused:'Pausada',cancelled:'Cancelada',stopped:'Detenida',completed:'Completada'};
export function CommunicationPanel({leadId}:{leadId:string}){
 const {authState}=useAuth(),qc=useQueryClient();const q=useQuery({queryKey:['communication',leadId],queryFn:()=>getCommunication(leadId)});const detail=useQuery({queryKey:['commercial-detail','',leadId],queryFn:()=>getCommercialDetail(undefined,leadId)});
 const [person,setPerson]=useState(''),[channel,setChannel]=useState<'all'|'email'|'whatsapp'>('all'),[reason,setReason]=useState(''),[seq,setSeq]=useState(''),[confirm,setConfirm]=useState(false);
 const [editingSequence,setEditingSequence]=useState<string|undefined>();
 const [name,setName]=useState(''),[scope,setScope]=useState(''),[steps,setSteps]=useState<{waitDays:number;channel:'email'|'whatsapp';templateId:string}[]>([{waitDays:0,channel:'email',templateId:''}]);
 const templates=useQuery({queryKey:['sequence-templates'],queryFn:async()=>{const r=await fetch('/_api/settings');const d=superjson.parse<any>(await r.text());return d.templates??d.messageTemplates??[];},enabled:authState.type==='authenticated'&&authState.user.role==='admin'});
 const m=useMutation({mutationFn:postCommunication,onSuccess:()=>{void qc.invalidateQueries({queryKey:['communication']});void qc.invalidateQueries({queryKey:['work']});setConfirm(false)}});const admin=authState.type==='authenticated'&&authState.user.role==='admin';const userEmail=authState.type==='authenticated'?authState.user.email:'';const opp=detail.data?.opportunities.find(o=>String(o.id)===leadId);const canWrite=admin||opp?.assignedUserEmail===userEmail||detail.data?.account.assignedUserEmail===userEmail;
 if(q.isPending)return <p>Cargando comunicación…</p>;if(q.error)return <p role="alert">{q.error.message}</p>;
 return <section className={styles.panel}><h3>Comunicación y secuencias asistidas</h3><p className={styles.muted}>{q.data.webhookConfigured?'Webhook Brevo configurado localmente; revisar configuración externa.':'Eventos Brevo sin configurar: no se infiere entrega.'} Las secuencias generan tareas y borradores, sin envíos automáticos.</p>
 <details><summary>Restricciones de contacto</summary><div className={styles.panel}>{canWrite&&<><label>Persona<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Contacto original de esta oportunidad</option>{detail.data?.contacts.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Canal<select value={channel} onChange={e=>setChannel(e.target.value as any)}><option value="all">Todos</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option></select></label><label>Motivo de restricción<input value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={reason.trim().length<3||m.isPending} onClick={()=>m.mutate({action:'restrict',leadId,contactId:person||null,channel,reason})}>Bloquear contacto/canal</Button></>}
 {q.data.restrictions.map(r=><article key={r.id}><strong>{r.channel} · {r.liftedAt?'Levantada':'No contactar'}</strong><p>{r.contactId?detail.data?.contacts.find(c=>String(c.id)===String(r.contactId))?.name:'Contacto original #'+r.leadId} · {r.reason} · {r.actorEmail} · {new Date(r.createdAt).toLocaleString('es-AR')}</p>{r.liftedAt?<p>{r.liftReason} · {r.liftedBy} · {new Date(r.liftedAt).toLocaleString('es-AR')}</p>:admin&&<Button variant="outline" disabled={m.isPending} onClick={()=>{const value=window.prompt('Motivo para levantar la restricción');if(value)m.mutate({action:'lift',id:String(r.id),reason:value})}}>Levantar restricción</Button>}</article>)}</div></details>
 <details><summary>Iniciar secuencia</summary><div className={styles.panel}>{canWrite&&<><label>Persona<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Contacto original de esta oportunidad</option>{detail.data?.contacts.filter(c=>!c.deletedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Secuencia<select value={seq} onChange={e=>setSeq(e.target.value)}><option value="">Elegir</option>{q.data.sequences.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{q.data.sequences.filter(s=>String(s.id)===seq).map(s=><p key={s.id}>{s.scope} · {s.steps.map((p:any,i:number)=>`Paso ${i+1}: esperar ${p.waitDays} días, ${p.channel}`).join(' / ')}</p>)}<label className={styles.check}><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Confirmo la generación de tareas y borradores</label><Button disabled={!seq||!confirm||m.isPending} onClick={()=>m.mutate({action:'sequence_start',id:crypto.randomUUID(),sequenceId:seq,leadId,contactId:person||null,confirm:true})}>Iniciar seguimiento asistido</Button></>}
 {q.data.runs.map(r=><article key={r.id}><strong>{r.snapshot.name} · {runLabels[r.status]}</strong><p>{r.reason} · {r.ownerEmail} · {new Date(r.createdAt).toLocaleString('es-AR')}</p>{canWrite&&['active','paused'].includes(r.status)&&<div className={styles.actions}>{['paused','active','cancelled'].filter(s=>s!==r.status).map(s=><Button key={s} variant="outline" disabled={m.isPending} onClick={()=>{const value=window.prompt('Motivo');if(value)m.mutate({action:'sequence_control',id:r.id,state:s as any,reason:value})}}>{s==='paused'?'Pausar':s==='active'?'Reanudar':'Cancelar'}</Button>)}</div>}</article>)}</div></details>
 {admin&&<details><summary>Configurar secuencia</summary><div className={styles.panel}><label>Nombre de secuencia<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Alcance y uso previsto<input value={scope} onChange={e=>setScope(e.target.value)}/></label>{steps.map((s,i)=><div key={i} className={styles.grid}><label>Espera desde paso anterior (días)<input type="number" min={0} max={365} value={s.waitDays} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,waitDays:Number(e.target.value)}:p))}/></label><label>Canal<select value={s.channel} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,channel:e.target.value as any,templateId:''}:p))}><option value="email">Email</option><option value="whatsapp">WhatsApp</option></select></label><label>Template<select value={s.templateId} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,templateId:e.target.value}:p))}><option value="">Elegir</option>{templates.data?.filter((t:any)=>t.channel===s.channel).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>)}<div className={styles.actions}><Button variant="outline" disabled={steps.length>=12} onClick={()=>setSteps([...steps,{waitDays:3,channel:'email',templateId:''}])}>Agregar paso</Button><Button disabled={name.trim().length<3||scope.trim().length<3||steps.some(s=>!s.templateId)||m.isPending} onClick={()=>m.mutate({action:'sequence_save',id:editingSequence,name,scope,steps,active:true})}>Guardar secuencia</Button></div>{q.data.sequences.map(s=><p key={s.id}>{s.name} · {s.active?'Activa':'Inactiva'} <Button size="sm" variant="ghost" onClick={()=>{setEditingSequence(String(s.id));setName(s.name);setScope(s.scope);setSteps(s.steps)}}>Editar configuración</Button><Button size="sm" variant="ghost" onClick={()=>m.mutate({action:'sequence_save',id:String(s.id),name:s.name,scope:s.scope,steps:s.steps,active:!s.active})}>{s.active?'Desactivar':'Activar'}</Button></p>)}</div></details>}
 <h4>Mensajes y borradores ({q.data.messages.length})</h4>{q.data.messages.map(msg=><details key={msg.id}><summary>{messageLabels[msg.status]??msg.status} · {msg.channel} · {msg.recipient} · {new Date(msg.createdAt).toLocaleString('es-AR')}</summary>{canWrite&&(admin||msg.ownerEmail===userEmail)?<MessageComposer key={msg.id} initial={msg}/>:<p>{msg.subject} · {msg.textBody||msg.body}</p>}</details>)}{m.error&&<p role="alert">{m.error.message}</p>}
 </section>;
}
