import React,{useEffect,useState} from 'react';import {useMutation,useQuery} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from './Dialog';import {Button} from './Button';import {MessageComposer,messageLabels} from './MessageComposer';
import {getCommercialDetail} from '../endpoints/commercial.schema';import {getCommunication,postCommunication,type Message} from '../endpoints/communication.schema';
import {htmlToPlainText} from '../helpers/renderMessageTemplate';
import {Mail,MessageCircle,Search,ArrowRight} from 'lucide-react';
import styles from './ContactTemplateDialog.module.css';
type Template={id:string;channel:string;name:string;subject:string|null;body:string;vertical:string|null;commercialProfile:string|null};
export function ContactTemplateDialog({open,onOpenChange,channel,lead,templates}:{open:boolean;onOpenChange:(v:boolean)=>void;channel:'email'|'whatsapp';lead:any|null;templates:Template[]}){
 const [contactId,setContactId]=useState<string|null>(null),[message,setMessage]=useState<Message|null>(null),[search,setSearch]=useState('');
 const q=useQuery({queryKey:['commercial-detail','',String(lead?.id??'')],queryFn:()=>getCommercialDetail(undefined,String(lead.id)),enabled:open&&!!lead?.id});
 const history=useQuery({queryKey:['communication',String(lead?.id??'')],queryFn:()=>getCommunication(String(lead.id)),enabled:open&&!!lead?.id});
 useEffect(()=>{if(open){setContactId(null);setMessage(null);setSearch('')}},[open,channel,lead?.id]);
 const contacts=q.data?.contacts.filter(c=>!c.deletedAt)??[];const opp=q.data?.opportunities.find(o=>String(o.id)===String(lead?.id));const preferred=contacts.find(c=>String(c.id)===String(opp?.primaryContactId))||(contacts.length===1?contacts[0]:contacts.find(c=>c.isPrimary));const legacy=preferred?.sourceLeadId!=null&&String(preferred.sourceLeadId)===String(lead?.id)&&!opp?.opportunityName;
 const effective=contactId??(preferred&&!legacy?String(preferred.id):'');const person=contacts.find(c=>String(c.id)===effective);const recipient=effective?(channel==='email'?person?.email:person?.phone):(channel==='email'?lead?.email:lead?.telefono);
 const restriction=history.data?.restrictions.find(r=>!r.liftedAt&&['all',channel].includes(r.channel)&&((effective&&String(r.contactId)===effective)||(!r.contactId&&String(r.leadId)===String(lead?.id))));
 const blocked=q.data?.account.doNotContact||!!restriction;const recent=history.data?.recentMessages.find(m=>((effective?m.contactId===effective:!m.contactId&&m.leadId===String(lead?.id))||(m.channel===channel&&m.recipient===recipient))&&m.status!=='draft'&&m.status!=='cancelled'&&!!m.lastInteractionAt&&Date.now()-new Date(m.lastInteractionAt).getTime()<(history.data?.recentContactHours??72)*3600000);
 const applicable=templates.filter(t=>t.channel===channel&&(!t.vertical||t.vertical===lead?.tipo)&&(!lead?.commercialProfile?.trim()||!t.commercialProfile||t.commercialProfile===lead.commercialProfile)&&!(channel==='whatsapp'&&lead?.commercialProfile==='Referente'));
 const visible=applicable.filter(t=>[t.name,t.subject,t.vertical,t.commercialProfile,htmlToPlainText(t.body)].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 const prepare=useMutation({mutationFn:postCommunication,onSuccess:d=>setMessage(d)});
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className={styles.dialog}>
 <DialogHeader className={styles.header}><div className={styles.heading}><span className={styles.channelIcon}>{channel==='email'?<Mail size={20}/>:<MessageCircle size={20}/>}</span><div><DialogTitle>{channel==='email'?'Preparar email':'Preparar WhatsApp'}</DialogTitle><DialogDescription>{lead?.nombre}</DialogDescription></div></div>{message&&<p className={styles.subtitle}>Editá el contenido, revisalo y confirmá la acción.</p>}</DialogHeader>
 <div className={styles.scrollBody}>
 {!message&&<>
 <section className={styles.recipientBox}><div className={styles.sectionHeading}><span className={styles.step}>1</span><h3>Destinatario</h3></div>
 <label className={styles.recipient}>Contacto<select aria-label="Destinatario" value={effective} disabled={prepare.isPending||q.isPending} onChange={e=>setContactId(e.target.value)}><option value="">Contacto original de la oportunidad</option>{contacts.map(c=><option key={c.id} value={String(c.id)}>{c.name}{c.isPrimary?' · Principal':''}</option>)}</select></label><p className={styles.recipientChannel}>{q.isPending?'Cargando contactos…':recipient||'Sin '+(channel==='email'?'email':'teléfono')+' cargado para este contacto'}</p><p className={styles.recipientHelp}>Usamos los datos del contacto elegido. Si no tiene nombre, el saludo queda sin nombre.</p></section>
 {blocked&&<p className={styles.warning} role="alert"><strong>No contactar</strong><span>{restriction?.reason||'Restricción del negocio'}</span></p>}
 {recent&&<p className={styles.notice} role="status"><strong>Contacto reciente · {recent.recipientName||'Sin nombre informado'}</strong><span>{new Date(recent.lastInteractionAt!).toLocaleString('es-AR')} · {recent.channel} · {messageLabels[recent.status]??recent.status} · {recent.lastActorEmail}</span><span>Revisá esta interacción antes de iniciar otro contacto.</span></p>}
 <section className={styles.templates}><div className={styles.sectionHeading}><span className={styles.step}>2</span><h3>Elegí un template</h3><span className={styles.count}>{applicable.length}</span></div><p className={styles.recipientHelp}>Al elegirlo se prepara un borrador. Podés editarlo antes de usar el canal.</p>
 <label className={styles.search}><Search size={16}/><input aria-label="Buscar template" placeholder="Buscar por nombre, perfil o contenido…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <div className={styles.list} aria-busy={prepare.isPending}>{visible.map(t=><button type="button" key={t.id} disabled={blocked||!recipient||prepare.isPending||!q.data} onClick={()=>prepare.mutate({action:'prepare',id:crypto.randomUUID(),leadId:String(lead.id),contactId:effective||null,channel,templateId:String(t.id)})}><div className={styles.templateTitle}><strong>{t.name}</strong><ArrowRight size={16}/></div><div className={styles.tags}><span>{t.vertical||'Todas las verticales'}</span><span>{t.commercialProfile||'Todos los perfiles'}</span></div>{channel==='email'&&t.subject&&<p className={styles.subject}>Asunto: {t.subject}</p>}<p className={styles.excerpt}>{htmlToPlainText(t.body)}</p></button>)}</div>
 {!visible.length&&<p className={styles.empty}>{applicable.length?'No hay templates que coincidan con la búsqueda.':'No hay templates disponibles para este canal y perfil. Podés escribir un mensaje libre.'}</p>}
 <div className={styles.freeMessage}><span>¿Preferís escribir desde cero?</span><Button variant="outline" disabled={blocked||!recipient||prepare.isPending||!q.data} onClick={()=>prepare.mutate({action:'prepare',id:crypto.randomUUID(),leadId:String(lead.id),contactId:effective||null,channel,templateId:null})}>Preparar sin template</Button></div>
 {prepare.isPending&&<p className={styles.recipientHelp} role="status">Preparando borrador…</p>}</section></>}
 {message&&<MessageComposer key={message.id} initial={message} onChange={setMessage}/>}
 {(prepare.error||q.error||history.error)&&<p className={styles.warning} role="alert">{prepare.error?.message||q.error?.message||history.error?.message}</p>}
 </div>
 <DialogFooter className={styles.footer}>{message?.status==='draft'&&<Button variant="ghost" onClick={()=>setMessage(null)}>Cambiar destinatario o template</Button>}<Button variant="outline" onClick={()=>onOpenChange(false)}>Cerrar</Button></DialogFooter></DialogContent></Dialog>;
}
