import React,{useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {getQuality,qualityRequest,type QualityDetail} from '../endpoints/dataQuality.schema';
import {Button} from './Button';
import {Input} from './Input';
import {Textarea} from './Textarea';
import styles from './DataQuality.module.css';
const labels:Record<string,string>={valid:'Formato válido',invalid:'Inválido',ambiguous:'Ambiguo',missing:'Incompleto',unverified:'Sin verificar'};
export function DataQualityPanel({accountId,readOnly=false}:{accountId:string;readOnly?:boolean}){
 const qc=useQueryClient(),q=useQuery({queryKey:['data-quality',accountId],queryFn:()=>getQuality(accountId)});
 const [field,setField]=useState<QualityDetail['fields'][number]|null>(null),[source,setSource]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[obtainedAt,setObtainedAt]=useState(''),[verifiedAt,setVerifiedAt]=useState(''),[observations,setObservations]=useState(''),[validity,setValidity]=useState('unverified'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){if(!field)return;setBusy(true);setError('');try{
  await qualityRequest({action:'evidence',accountId,contactId:field.contactId,field:field.field as 'email',revision:field.revision,source,sourceUrl:sourceUrl||null,obtainedAt:obtainedAt?new Date(obtainedAt+'T00:00:00-03:00').toISOString():null,verifiedAt:verifiedAt?new Date(verifiedAt+'T00:00:00-03:00').toISOString():null,validity:validity as 'unverified',observations});
  setField(null);await qc.invalidateQueries({queryKey:['data-quality']});
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(q.isPending)return <p>Cargando calidad…</p>;if(q.error)return <p role="alert">{q.error.message}</p>;
 return <section className={styles.content}><div><h3>Calidad y procedencia</h3><p className={styles.muted}>Formato válido no significa dato verificado. Cada fuente corresponde a un campo y valor concreto; editar el dato deja la evidencia anterior como histórica.</p></div>
 <div className={styles.scroll}>{q.data.fields.map(f=><article key={(f.contactId??'account')+f.field} className={styles.row}><div className={styles.heading}><strong>{f.label}</strong><span>{labels[f.validity]}</span></div><span>{f.original||'Sin dato'}</span>{f.normalized&&<span className={styles.muted}>Comparación: {f.normalized}</span>}{f.observations&&<span className={styles.muted}>{f.observations}</span>}{f.latest&&<p className={styles.muted}>{f.stale?'Evidencia de un valor anterior':'Evidencia actual'} · {f.latest.source} · {labels[f.latest.validity]}{f.latest.obtainedAt?' · obtenido '+new Date(f.latest.obtainedAt).toLocaleDateString('es-AR'):''}{f.latest.verifiedAt?' · verificado '+new Date(f.latest.verifiedAt).toLocaleDateString('es-AR'):''}{f.latest.batchId?' · lote '+f.latest.batchId:''}{f.latest.sourceUrl&&<> · <a href={f.latest.sourceUrl} target="_blank" rel="noreferrer">Origen</a></>}{f.latest.observations?' · '+f.latest.observations:''}</p>}{!readOnly&&q.data.canEdit&&<Button size="sm" variant="outline" onClick={()=>{setField(f);setSource('');setSourceUrl('');setObtainedAt('');setVerifiedAt('');setObservations('');setValidity('unverified');setError('');}}>Registrar fuente / verificación</Button>}</article>)}</div>
 {field&&<div className={styles.row}><h4>Verificar {field.label} · {field.original||'Sin dato'}</h4><div className={styles.grid}><label>Fuente<Input value={source} onChange={e=>setSource(e.target.value)}/></label><label>URL de origen<Input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label>Fecha de obtención<Input type="date" value={obtainedAt} onChange={e=>setObtainedAt(e.target.value)}/></label><label>Fecha de verificación<Input type="date" value={verifiedAt} onChange={e=>setVerifiedAt(e.target.value)}/></label><label>Validez<select className={styles.select} value={validity} onChange={e=>setValidity(e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>Observaciones<Textarea value={observations} onChange={e=>setObservations(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className={styles.actions}><Button disabled={busy||!source.trim()} onClick={()=>void save()}>Guardar evidencia</Button><Button variant="outline" onClick={()=>setField(null)}>Cancelar</Button></div></div>}
 <details><summary>Histórico de evidencias ({q.data.evidence.length})</summary>{q.data.evidence.map(e=><p key={e.id}>{new Date(e.createdAt).toLocaleString('es-AR')} · {e.field} · {e.originalValue||'Vacío'} · {e.source} · {labels[e.validity]} · {e.actorEmail}{e.batchId?' · lote '+e.batchId:''}{e.leadId?' · oportunidad #'+e.leadId:''}{e.contactId?' · contacto #'+e.contactId:''}</p>)}</details>
 {!!q.data.merges.length&&<details><summary>Fusiones conservadas ({q.data.merges.length})</summary>{q.data.merges.map(m=><p key={m.id}>#{m.sourceId} → #{m.destinationId} · {m.reason} · {m.actorEmail} · {new Date(m.createdAt).toLocaleString('es-AR')}</p>)}</details>}
 </section>;
}
