import React,{useEffect,useState} from 'react';import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from './Button';import {RichTemplateEditor} from './RichTemplateEditor';import {postCommunication,type Message} from '../endpoints/communication.schema';import {whatsappTextToPreviewHtml} from '../helpers/templateChannelFormatting';
import styles from './Communication.module.css';
export const messageLabels:Record<string,string>={draft:'Borrador',whatsapp_opened:'WhatsApp abierto · envío no confirmado',manual_sent:'Envío confirmado manualmente',submitting:'Envío en curso · no reenviar',accepted:'Email aceptado por proveedor · entrega no confirmada',delivery_confirmed:'Entrega confirmada',failed:'Rebote/fallo',unknown:'Resultado incierto · revisar Brevo',replied:'Respuesta registrada manualmente',rejected:'Rechazo registrado manualmente',cancelled:'Cancelado'};
export function MessageComposer({initial,onChange}:{initial:Message;onChange?:(m:Message)=>void}){
 const [m,setM]=useState(initial),[subject,setSubject]=useState(initial.subject),[body,setBody]=useState(initial.body),[confirm,setConfirm]=useState(false),[notes,setNotes]=useState('');const qc=useQueryClient();
 useEffect(()=>{if(m.status!=='draft'&&new Date(initial.updatedAt)>new Date(m.updatedAt))setM(initial);},[initial,m.status,m.updatedAt]);
 const dirty=subject!==m.subject||body!==m.body;const mutation=useMutation({mutationFn:postCommunication,onSuccess:data=>{if(data.id){setM(data);setBody(data.body);setSubject(data.subject);onChange?.(data);}if(data.message){setM(data.message);onChange?.(data.message);}if(data.url)window.open(data.url,'_blank','noopener,noreferrer');void qc.invalidateQueries({queryKey:['communication']});void qc.invalidateQueries({queryKey:['work']});void qc.invalidateQueries({queryKey:['commercial-detail']});for(const key of ['leads','lead-stats','analytics','lead-journal','global-journal','pipeline'])void qc.invalidateQueries({queryKey:[key]});setConfirm(false);}});
 const mutate=(input:Parameters<typeof postCommunication>[0])=>mutation.mutate(input);
 return <section className={styles.composer}><p><strong>{messageLabels[m.status]??m.status}</strong> · {m.recipientName?m.recipientName+' · ':''}{m.recipient}</p>{m.templateSnapshot&&<p className={styles.muted}>Template: {m.templateSnapshot.name} · versión {m.templateSnapshot.version.slice(0,12)}</p>}
 {m.status==='draft'&&<><label>Asunto{m.channel==='email'?<input aria-label="Asunto final" value={subject} onChange={e=>{setSubject(e.target.value);setConfirm(false)}}/>:<span>No aplica a WhatsApp</span>}</label>
 {m.channel==='email'?<RichTemplateEditor channel="email" value={body} onChange={v=>{setBody(v);setConfirm(false)}}/>:<label>Mensaje final<textarea aria-label="Mensaje final" rows={8} value={body} onChange={e=>{setBody(e.target.value);setConfirm(false)}}/></label>}
 <Button disabled={mutation.isPending||!body.trim()} onClick={()=>mutate({action:'edit',id:m.id,revision:m.revision,subject,body})}>Guardar y ver contenido final</Button></>}
 {!dirty&&m.textBody&&<><h4>Contenido real utilizado</h4>{m.channel==='email'?<iframe sandbox="" title="Vista previa del email" srcDoc={m.htmlBody??''} className={styles.preview}/>:<div className={styles.whatsapp} dangerouslySetInnerHTML={{__html:whatsappTextToPreviewHtml(m.body)}}/>}</>}
 {m.status==='draft'&&<><label className={styles.check}><input type="checkbox" disabled={mutation.isPending||dirty||!m.textBody} checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Revisé destinatario y contenido final</label><Button disabled={dirty||!m.textBody||!confirm||mutation.isPending} onClick={()=>mutate({action:'dispatch',id:m.id,revision:m.revision,confirm:true})}>{m.channel==='email'?'Enviar email con Brevo':'Abrir WhatsApp con este mensaje'}</Button><p className={styles.muted}>Abrir WhatsApp no prueba envío. Brevo aceptar no prueba entrega.</p></>}
 {!['draft','cancelled','submitting'].includes(m.status)&&<><label>Observaciones del resultado<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={4000}/></label><div className={styles.actions}>{m.channel==='whatsapp'&&m.status==='whatsapp_opened'&&<Button disabled={mutation.isPending} onClick={()=>mutate({action:'outcome',id:m.id,event:'manual_sent',notes})}>Confirmar envío manual</Button>}<Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'replied',notes})}>Registrar respuesta</Button><Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'rejected',notes})}>Registrar rechazo</Button></div></>}
 {mutation.error&&<p role="alert">{mutation.error.message}</p>}
 </section>;
}
