import { Disclosure, DisclosureSummary } from './Disclosure';
import { Input } from './Input';
import { Checkbox } from './Checkbox';
import { Textarea } from './Textarea';
import {useUnsavedChanges} from './UnsavedChanges';
import React,{useEffect,useState,useRef} from 'react';import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from './Button';import {RichTemplateEditor} from './RichTemplateEditor';import {postCommunication,type Message} from '../endpoints/communication.schema';import {whatsappTextToPreviewHtml,htmlToWhatsApp} from '../helpers/templateChannelFormatting';
import {Mail,MessageCircle,Check,ArrowLeft,Eye} from 'lucide-react';
import styles from './Communication.module.css';
export const messageLabels:Record<string,string>={draft:'Borrador',whatsapp_opened:'WhatsApp abierto · envío no confirmado',manual_sent:'Envío confirmado manualmente',submitting:'Envío en curso · no reenviar',accepted:'Email aceptado por proveedor · entrega no confirmada',delivery_confirmed:'Entrega confirmada',failed:'Rebote/fallo',unknown:'Resultado incierto · revisar Brevo',replied:'Respuesta registrada manualmente',rejected:'Rechazo registrado manualmente',cancelled:'Cancelado'};
const editorContent=(channel:Message['channel'],body:string)=>channel==='whatsapp'?'<p>'+whatsappTextToPreviewHtml(body)+'</p>':body;
export function MessageComposer({initial,onChange,onDirtyChange,taskFlow=false,onBusyChange}:{initial:Message;onChange?:(m:Message)=>void;onDirtyChange?:(dirty:boolean)=>void;taskFlow?:boolean;onBusyChange?:(busy:boolean)=>void}){
 const [m,setM]=useState(initial),[subject,setSubject]=useState(initial.subject),[body,setBody]=useState(initial.body),[confirm,setConfirm]=useState(false),[notes,setNotes]=useState(''),[editing,setEditing]=useState(true),[editorHtml,setEditorHtml]=useState(()=>editorContent(initial.channel,initial.body));const qc=useQueryClient();
 useEffect(()=>{if(m.status!=='draft'&&new Date(initial.updatedAt)>new Date(m.updatedAt))setM(initial);},[initial,m.status,m.updatedAt]);
 const dirty=subject!==m.subject||body!==m.body;const mutation=useMutation({mutationFn:postCommunication,onSuccess:(data,input)=>{if(input.action==='edit')setEditing(false);if(data.id){setM(data);setBody(data.body);setEditorHtml(editorContent(data.channel,data.body));setSubject(data.subject);onChange?.(data);}if(data.message){setM(data.message);onChange?.(data.message);}if(data.url)window.open(data.url,'_blank','noopener,noreferrer');void qc.invalidateQueries({queryKey:['communication']});void qc.invalidateQueries({queryKey:['work']});void qc.invalidateQueries({queryKey:['commercial-detail']});for(const key of ['leads','lead-stats','analytics','lead-journal','global-journal','pipeline'])void qc.invalidateQueries({queryKey:[key]});setConfirm(false);}});
 useEffect(()=>{onBusyChange?.(mutation.isPending);return()=>onBusyChange?.(false)},[mutation.isPending,onBusyChange]);
 const processing=useRef(false);
 const mutate=async(input:Parameters<typeof postCommunication>[0])=>{if(processing.current)return;processing.current=true;try{await mutation.mutateAsync(input)}catch{}finally{processing.current=false}};
 useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange]);
 const unload=useUnsavedChanges(dirty,()=>{});
 const [cancel,setCancel]=useState(false);
 const draft=m.status==='draft';
 const preview=!dirty&&!!m.textBody;
 return <section className={styles.composer} aria-busy={mutation.isPending} data-unsaved={dirty?"true":undefined}>
 <>{mutation.isPending&&<p role="status">{mutation.variables?.action==='edit'?'Guardando mensaje…':mutation.variables?.action==='dispatch'?(m.channel==='email'?'Enviando email…':'Abriendo WhatsApp…'):mutation.variables?.action==='cancel_draft'?'Cancelando borrador…':'Registrando resultado…'}</p>}</>
 <header className={styles.messageHeader}><span className={styles.channelIcon}>{m.channel==='email'?<Mail size={18}/>:<MessageCircle size={18}/>}</span><div><span className={styles.eyebrow}>{m.channel==='email'?'Email para':'WhatsApp para'} {m.recipientName||'el contacto seleccionado'}</span><strong className={styles.destination}>{m.recipient}</strong></div><span className={styles.statusBadge}>{messageLabels[m.status]??m.status}</span></header>
 {m.templateSnapshot&&<Disclosure className={styles.templateDetails}><DisclosureSummary>Modelo: {m.templateSnapshot.name}</DisclosureSummary><p className={styles.muted}>Versión conservada: {m.templateSnapshot.version.slice(0,12)}. Este borrador conserva el modelo usado al prepararlo.</p></Disclosure>}
 {draft&&<ol className={styles.progress} aria-label="Preparación del mensaje"><li aria-current={editing?'step':undefined}><span>{editing?'1':<Check size={14}/>}</span>Editar mensaje</li><li aria-current={!editing?'step':undefined}><span>2</span>Revisar y confirmar</li></ol>}
 {draft&&editing&&<div className={styles.editSection}><div><h3>Personalizá el mensaje</h3><p className={styles.muted}>El destinatario ya está elegido. Revisá el saludo y ajustá el texto antes de continuar.</p></div>
 {m.channel==='email'&&<label>Asunto<Input aria-label="Asunto final" value={subject} disabled={mutation.isPending} onChange={e=>{setSubject(e.target.value);setConfirm(false)}}/></label>}
 <div inert={mutation.isPending}><RichTemplateEditor channel={m.channel} ariaLabel="Mensaje final" showVariables={false} value={editorHtml} onChange={v=>{setEditorHtml(v);setBody(m.channel==='whatsapp'?htmlToWhatsApp(v):v);setConfirm(false)}}/></div>
 <div className={styles.actionBar}><span className={styles.muted}>{dirty?'Cambios sin guardar':'Borrador guardado'}</span><Button disabled={mutation.isPending||!body.trim()||(m.channel==='email'&&!subject.trim())} onClick={()=>mutate({action:'edit',id:m.id,revision:m.revision,subject,body})}><Eye size={16}/>{mutation.isPending?'Guardando mensaje…':'Guardar y ver contenido final'}</Button></div></div>}
 {(!draft||!editing)&&preview&&<section className={styles.reviewSection}><div className={styles.reviewHeading}><div><h3>{draft?'Revisá el contenido final':'Contenido utilizado'}</h3><p className={styles.muted}>{draft?'Este es el contenido guardado que usará el canal.':'Se conserva el mensaje utilizado y su destinatario.'}</p></div>{draft&&<Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>{setEditing(true);setConfirm(false)}}><ArrowLeft size={14}/>Volver a editar</Button>}</div>
 {m.channel==='email'&&<p className={styles.subjectLine}><strong>Asunto</strong><span>{m.subject}</span></p>}
 {m.channel==='email'?<EmailReadingView text={m.textBody??''} html={m.htmlBody??''}/>:<div className={styles.whatsappCanvas}><div className={styles.whatsapp} dangerouslySetInnerHTML={{__html:whatsappTextToPreviewHtml(m.body)}}/></div>}
 </section>}
 {draft&&<div className={styles.confirmSection} hidden={editing}><label className={styles.check}><Checkbox  disabled={mutation.isPending||dirty||!m.textBody} checked={confirm} onChange={e=>setConfirm(e.target.checked)}/><span>Revisé destinatario y contenido final</span></label><div className={styles.actionBar}><p className={styles.muted}>{m.channel==='email'?'Brevo acepta el email; la entrega se confirma por separado.':'Se abrirá WhatsApp. Después podés registrar si efectivamente lo enviaste.'}</p><Button disabled={editing||dirty||!m.textBody||!confirm||mutation.isPending} onClick={()=>mutate({action:'dispatch',id:m.id,revision:m.revision,confirm:true})}>{mutation.isPending?(m.channel==='email'?'Enviando email…':'Abriendo WhatsApp…'):m.channel==='email'?'Enviar email con Brevo':'Abrir WhatsApp con este mensaje'}</Button></div></div>}
 {!taskFlow&&!['draft','cancelled','submitting'].includes(m.status)&&<section className={styles.outcomeSection}><h3>Registrar lo ocurrido</h3><p className={styles.muted}>{m.status==='whatsapp_opened'?'Abrir el enlace no confirma el envío. Registrá el resultado real.':'Registrá una respuesta o rechazo cuando tengas esa información.'}</p><label>Observaciones del resultado<Textarea aria-label="Observaciones del resultado" rows={3} disabled={mutation.isPending} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={4000}/></label><div className={styles.actions}>{m.channel==='whatsapp'&&m.status==='whatsapp_opened'&&<Button disabled={mutation.isPending} onClick={()=>mutate({action:'outcome',id:m.id,event:'manual_sent',notes})}>Confirmar envío manual</Button>}<Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'replied',notes})}>Registrar respuesta</Button><Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'rejected',notes})}>Registrar rechazo</Button></div></section>}
 {taskFlow&&!['draft','cancelled','submitting'].includes(m.status)&&<section className={styles.outcomeSection}><h3>Seguí con esta conversación</h3><p>Usá Registrar qué pasó para elegir el resultado real y dejar el próximo paso. El mensaje no registra el resultado de la conversación por sí solo.</p>{m.status==='whatsapp_opened'&&<Button variant="outline" disabled={mutation.isPending} onClick={()=>mutate({action:'outcome',id:m.id,event:'manual_sent',notes:''})}>Confirmar envío manual</Button>}</section>}
 {draft&&!m.runId&&<Disclosure><DisclosureSummary>Opciones del borrador</DisclosureSummary><p>El borrador guardado se conserva al cerrar. Si ya no lo necesitás, podés cancelarlo.</p><label className={styles.check}><Checkbox  disabled={mutation.isPending} checked={cancel} onChange={e=>setCancel(e.target.checked)}/>Quiero cancelar este borrador</label><Button variant="outline" disabled={!cancel||mutation.isPending||dirty} onClick={()=>mutate({action:'cancel_draft',id:m.id,revision:m.revision})}>Cancelar borrador</Button></Disclosure>}
 {mutation.error&&<p className={styles.errorBox} role="alert">{mutation.error.message}</p>}
 </section>;
}

function EmailReadingView({text,html}:{text:string;html:string}){const [styled,setStyled]=useState(false);return <><p className={styles.muted}>Leé el mensaje completo junto con el asunto. La vista de diseño muestra cómo se presenta el email.</p><Button variant="outline" aria-pressed={styled} onClick={()=>setStyled(!styled)}>{styled?'Volver al texto completo':'Ver diseño del email'}</Button>{styled?<iframe sandbox="" title="Vista previa del email" srcDoc={html} className={styles.preview}/>:<div className={styles.readableMessage}>{text}</div>}</>;}
