import React,{useEffect,useState} from 'react';import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Button} from './Button';import {RichTemplateEditor} from './RichTemplateEditor';import {postCommunication,type Message} from '../endpoints/communication.schema';import {whatsappTextToPreviewHtml,htmlToWhatsApp} from '../helpers/templateChannelFormatting';
import {Mail,MessageCircle,Check,ArrowLeft,Eye} from 'lucide-react';
import styles from './Communication.module.css';
export const messageLabels:Record<string,string>={draft:'Borrador',whatsapp_opened:'WhatsApp abierto · envío no confirmado',manual_sent:'Envío confirmado manualmente',submitting:'Envío en curso · no reenviar',accepted:'Email aceptado por proveedor · entrega no confirmada',delivery_confirmed:'Entrega confirmada',failed:'Rebote/fallo',unknown:'Resultado incierto · revisar Brevo',replied:'Respuesta registrada manualmente',rejected:'Rechazo registrado manualmente',cancelled:'Cancelado'};
const editorContent=(channel:Message['channel'],body:string)=>channel==='whatsapp'?'<p>'+whatsappTextToPreviewHtml(body)+'</p>':body;
export function MessageComposer({initial,onChange}:{initial:Message;onChange?:(m:Message)=>void}){
 const [m,setM]=useState(initial),[subject,setSubject]=useState(initial.subject),[body,setBody]=useState(initial.body),[confirm,setConfirm]=useState(false),[notes,setNotes]=useState(''),[editing,setEditing]=useState(true),[editorHtml,setEditorHtml]=useState(()=>editorContent(initial.channel,initial.body));const qc=useQueryClient();
 useEffect(()=>{if(m.status!=='draft'&&new Date(initial.updatedAt)>new Date(m.updatedAt))setM(initial);},[initial,m.status,m.updatedAt]);
 const dirty=subject!==m.subject||body!==m.body;const mutation=useMutation({mutationFn:postCommunication,onSuccess:(data,input)=>{if(input.action==='edit')setEditing(false);if(data.id){setM(data);setBody(data.body);setEditorHtml(editorContent(data.channel,data.body));setSubject(data.subject);onChange?.(data);}if(data.message){setM(data.message);onChange?.(data.message);}if(data.url)window.open(data.url,'_blank','noopener,noreferrer');void qc.invalidateQueries({queryKey:['communication']});void qc.invalidateQueries({queryKey:['work']});void qc.invalidateQueries({queryKey:['commercial-detail']});for(const key of ['leads','lead-stats','analytics','lead-journal','global-journal','pipeline'])void qc.invalidateQueries({queryKey:[key]});setConfirm(false);}});
 const mutate=(input:Parameters<typeof postCommunication>[0])=>mutation.mutate(input);
 const draft=m.status==='draft';
 const preview=!dirty&&!!m.textBody;
 return <section className={styles.composer} aria-busy={mutation.isPending}>
 <header className={styles.messageHeader}><span className={styles.channelIcon}>{m.channel==='email'?<Mail size={18}/>:<MessageCircle size={18}/>}</span><div><span className={styles.eyebrow}>{m.channel==='email'?'Email para':'WhatsApp para'} {m.recipientName||'el contacto seleccionado'}</span><strong className={styles.destination}>{m.recipient}</strong></div><span className={styles.statusBadge}>{messageLabels[m.status]??m.status}</span></header>
 {m.templateSnapshot&&<details className={styles.templateDetails}><summary>Template: {m.templateSnapshot.name}</summary><p className={styles.muted}>Versión conservada: {m.templateSnapshot.version.slice(0,12)}. Este borrador conserva el template usado al prepararlo.</p></details>}
 {draft&&<ol className={styles.progress} aria-label="Preparación del mensaje"><li aria-current={editing?'step':undefined}><span>{editing?'1':<Check size={14}/>}</span>Editar mensaje</li><li aria-current={!editing?'step':undefined}><span>2</span>Revisar y confirmar</li></ol>}
 {draft&&editing&&<div className={styles.editSection}><div><h3>Personalizá el mensaje</h3><p className={styles.muted}>El destinatario ya está elegido. Revisá el saludo y ajustá el texto antes de continuar.</p></div>
 {m.channel==='email'&&<label>Asunto<input aria-label="Asunto final" value={subject} disabled={mutation.isPending} onChange={e=>{setSubject(e.target.value);setConfirm(false)}}/></label>}
 <div inert={mutation.isPending}><RichTemplateEditor channel={m.channel} ariaLabel="Mensaje final" showVariables={false} value={editorHtml} onChange={v=>{setEditorHtml(v);setBody(m.channel==='whatsapp'?htmlToWhatsApp(v):v);setConfirm(false)}}/></div>
 <div className={styles.actionBar}><span className={styles.muted}>{dirty?'Cambios sin guardar':'Borrador guardado'}</span><Button disabled={mutation.isPending||!body.trim()||(m.channel==='email'&&!subject.trim())} onClick={()=>mutate({action:'edit',id:m.id,revision:m.revision,subject,body})}><Eye size={16}/>{mutation.isPending?'Guardando…':'Guardar y ver contenido final'}</Button></div></div>}
 {(!draft||!editing)&&preview&&<section className={styles.reviewSection}><div className={styles.reviewHeading}><div><h3>{draft?'Revisá el contenido final':'Contenido utilizado'}</h3><p className={styles.muted}>{draft?'Este es el contenido guardado que usará el canal.':'Se conserva el mensaje utilizado y su destinatario.'}</p></div>{draft&&<Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>{setEditing(true);setConfirm(false)}}><ArrowLeft size={14}/>Volver a editar</Button>}</div>
 {m.channel==='email'&&<p className={styles.subjectLine}><strong>Asunto</strong><span>{m.subject}</span></p>}
 {m.channel==='email'?<iframe sandbox="" title="Vista previa del email" srcDoc={m.htmlBody??''} className={styles.preview}/>:<div className={styles.whatsappCanvas}><div className={styles.whatsapp} dangerouslySetInnerHTML={{__html:whatsappTextToPreviewHtml(m.body)}}/></div>}
 </section>}
 {draft&&<div className={styles.confirmSection} hidden={editing}><label className={styles.check}><input type="checkbox" disabled={mutation.isPending||dirty||!m.textBody} checked={confirm} onChange={e=>setConfirm(e.target.checked)}/><span>Revisé destinatario y contenido final</span></label><div className={styles.actionBar}><p className={styles.muted}>{m.channel==='email'?'Brevo acepta el email; la entrega se confirma por separado.':'Se abrirá WhatsApp. Después podés registrar si efectivamente lo enviaste.'}</p><Button disabled={editing||dirty||!m.textBody||!confirm||mutation.isPending} onClick={()=>mutate({action:'dispatch',id:m.id,revision:m.revision,confirm:true})}>{mutation.isPending?'Procesando…':m.channel==='email'?'Enviar email con Brevo':'Abrir WhatsApp con este mensaje'}</Button></div></div>}
 {!['draft','cancelled','submitting'].includes(m.status)&&<section className={styles.outcomeSection}><h3>Registrar lo ocurrido</h3><p className={styles.muted}>{m.status==='whatsapp_opened'?'Abrir el enlace no confirma el envío. Registrá el resultado real.':'Registrá una respuesta o rechazo cuando tengas esa información.'}</p><label>Observaciones del resultado<textarea aria-label="Observaciones del resultado" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={4000}/></label><div className={styles.actions}>{m.channel==='whatsapp'&&m.status==='whatsapp_opened'&&<Button disabled={mutation.isPending} onClick={()=>mutate({action:'outcome',id:m.id,event:'manual_sent',notes})}>Confirmar envío manual</Button>}<Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'replied',notes})}>Registrar respuesta</Button><Button disabled={mutation.isPending} variant="outline" onClick={()=>mutate({action:'outcome',id:m.id,event:'rejected',notes})}>Registrar rechazo</Button></div></section>}
 {mutation.error&&<p className={styles.errorBox} role="alert">{mutation.error.message}</p>}
 </section>;
}
