import {Link} from 'react-router-dom';
import React,{useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {getPipeline,postPipeline,type PipelineStage,type PipelineCatalog,type PriorityRule} from '../endpoints/pipeline.schema';
import {classificationNames} from './Pipeline';
import {Button} from './Button';
import styles from './Commercial.module.css';
import ps from './Pipeline.module.css';
function StageForm({stage}:{stage?:PipelineStage}){
 const [name,setName]=useState(stage?.name??''),[order,setOrder]=useState(stage?.sortOrder??0),[active,setActive]=useState(stage?.active??true),[classification,setClassification]=useState<PipelineStage['classification']>(stage?.classification??'open');
 const [journeyPhase,setPhase]=useState(stage?.journeyPhase??'');
 const qc=useQueryClient();const m=useMutation({mutationFn:postPipeline,onSuccess:()=>qc.invalidateQueries()});
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();m.mutate({action:'stage_save',name,sortOrder:order,active,classification,journeyPhase:journeyPhase as PipelineStage['journeyPhase']||null});}}><label>Nombre<input required disabled={!!stage} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Orden<input type="number" required min={0} max={10000} value={order} onChange={e=>setOrder(Number(e.target.value))}/></label><label>Clasificación<select disabled={!!stage} value={classification} onChange={e=>setClassification(e.target.value as typeof classification)}>{Object.entries(classificationNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Momento del recorrido<select value={journeyPhase} onChange={e=>setPhase(e.target.value as typeof journeyPhase)}><option value="">Sin vincular</option><option value="contact">Contacto</option><option value="need">Necesidad</option><option value="proposal">Propuesta</option><option value="decision">Decisión</option></select></label><p>Vinculá esta etapa después de revisar su significado con el equipo. No cambia ventas ni clasificaciones históricas.</p><label className={styles.checkbox}><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Activa</label>{m.error&&<p role="alert">{m.error.message}</p>}<Button type="submit" disabled={m.isPending}>Guardar etapa</Button></form>;
}
function CatalogForm({catalog,item}:{catalog:'loss'|'objection';item?:PipelineCatalog}){
 const [name,setName]=useState(item?.name??''),[active,setActive]=useState(item?.active??true);const qc=useQueryClient();const m=useMutation({mutationFn:postPipeline,onSuccess:()=>qc.invalidateQueries()});
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();m.mutate({action:'catalog_save',catalog,id:item?.id,name,active});}}><label>Nombre<input disabled={!!item} required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className={styles.checkbox}><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Activo</label>{m.error&&<p role="alert">{m.error.message}</p>}<Button type="submit" disabled={m.isPending}>Guardar</Button></form>;
}
const factorNames={overdue:'Seguimiento vencido (día anterior)',missing_followup:'Sin tarea pendiente',stage:'Está en una etapa seleccionada',stale_contact:'Sin contacto durante N días',close_soon:'Cierre previsto dentro de N días'};
function RulesForm({initial,stages}:{initial:PriorityRule[];stages:PipelineStage[]}){
 const [rules,setRules]=useState(initial);const qc=useQueryClient();const m=useMutation({mutationFn:postPipeline,onSuccess:()=>qc.invalidateQueries()});
 const update=(index:number,patch:Partial<PriorityRule>)=>setRules(r=>r.map((x,i)=>i===index?{...x,...patch}:x));
 return <form className={ps.rules} onSubmit={e=>{e.preventDefault();m.mutate({action:'rules_save',rules});}}><p className={styles.muted}>Las reglas aplicables muestran sus nombres. Se sugiere la prioridad más alta entre ellas, solo para oportunidades abiertas. Fechas desconocidas no activan reglas por antigüedad. La prioridad manual permanece intacta.</p>{rules.map((r,i)=><fieldset key={i} className={ps.rule}><legend>{r.name||'Nueva regla'}</legend><label>ID estable<input required pattern="[a-z][a-z0-9_-]{0,49}" value={r.id} onChange={e=>update(i,{id:e.target.value})}/></label><label>Explicación<input required maxLength={120} value={r.name} onChange={e=>update(i,{name:e.target.value})}/></label><label>Factor<select value={r.factor} onChange={e=>update(i,{factor:e.target.value as PriorityRule['factor']})}>{Object.entries(factorNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Prioridad sugerida<select value={r.priority} onChange={e=>update(i,{priority:e.target.value as PriorityRule['priority']})}><option>alta</option><option>media</option><option>baja</option></select></label>{['stale_contact','close_soon'].includes(r.factor)&&<label>Días<input type="number" min={0} max={365} required value={r.days} onChange={e=>update(i,{days:Number(e.target.value)})}/></label>}<label>Etapas (opcional; obligatorio para factor etapa)<select multiple value={r.stages} onChange={e=>update(i,{stages:Array.from(e.target.selectedOptions,o=>o.value)})}>{stages.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label className={ps.check}><input type="checkbox" checked={r.active} onChange={e=>update(i,{active:e.target.checked})}/>Activa</label><Button variant="outline" type="button" onClick={()=>setRules(x=>x.filter((_,n)=>n!==i))}>Quitar regla</Button></fieldset>)}{m.error&&<p role="alert">{m.error.message}</p>}<div className={styles.actions}><Button variant="outline" onClick={()=>setRules(r=>[...r,{id:'rule_'+Date.now(),name:'',factor:'missing_followup',priority:'media',active:true,days:0,stages:[]}])}>Agregar regla</Button><Button type="submit" disabled={m.isPending}>Guardar reglas</Button></div></form>;
}
export function PipelineSettings(){
 const q=useQuery({queryKey:['pipeline','config'],queryFn:()=>getPipeline({mode:'config'})});const [section,setSection]=useState('stages');const [selection,setSelection]=useState('new');const d=q.data;
 if(q.error)return <p role="alert">{q.error.message}</p>;if(!d)return <p>Cargando configuración comercial…</p>;
 return <section className={styles.panel}><h2>Pipeline y reactivación</h2><p className={styles.muted}>Los nombres y clasificaciones se conservan para proteger la historia. Para reemplazarlos, desactivá el elemento y creá uno nuevo. Una etapa inactiva conserva sus referencias.</p><div className={styles.actions}>{[['stages','Etapas'],['loss','Motivos de pérdida'],['objection','Objeciones'],['rules','Prioridad sugerida']].map(([key,label])=><Button key={key} variant={section===key?'primary':'outline'} onClick={()=>{setSection(key);setSelection('new');}}>{label}</Button>)}</div>
 {section==='rules'?<RulesForm key={JSON.stringify(d.rules)} initial={d.rules} stages={d.stages}/>:<><label>Elemento<select style={{maxWidth:'100%',padding:8,background:'var(--background)',color:'var(--foreground)'}} value={selection} onChange={e=>setSelection(e.target.value)}><option value="new">Agregar nuevo</option>{section==='stages'?d.stages.map(s=><option key={s.name} value={s.name}>{s.name||'Vacío histórico'} · {classificationNames[s.classification]} · {s.active?'Activo':'Inactivo'}</option>):(section==='loss'?d.lossReasons:d.objectionTypes).map(c=><option key={c.id} value={c.id}>{c.name} · {c.active?'Activo':'Inactivo'}</option>)}</select></label>{section==='stages'?<StageForm key={section+selection+JSON.stringify(d.stages)} stage={d.stages.find(s=>s.name===selection)}/>:<CatalogForm key={section+selection+JSON.stringify(d.lossReasons)+JSON.stringify(d.objectionTypes)} catalog={section as 'loss'|'objection'} item={(section==='loss'?d.lossReasons:d.objectionTypes).find(x=>x.id===selection)}/>}</>}
 <details><summary>Revisar estados históricos antes de reorganizar las etapas</summary><p>Esta lista es una vista previa. No cambia estados ni inventa cierres o pagos. Un nombre como Rechazado puede seguir clasificado como Abierta por la configuración histórica. Abrí sus ventas, revisá cada caso y registrá el cierre real con su motivo.</p><table><thead><tr><th>Estado actual</th><th>Clasificación</th><th>Ventas a revisar</th><th>Decisión pendiente del equipo</th></tr></thead><tbody>{d.historicalReview?.map(r=><tr key={r.stage}><td>{r.stage||'Sin etapa'}</td><td>{classificationNames[d.stages.find(s=>s.name===r.stage)?.classification??'open']}</td><td><Link to={'/opportunities?filterField=estado&filterValue='+encodeURIComponent(r.stage||'__EMPTY__')}>{r.count} · Revisar</Link></td><td>{/rechaz|no interesado/i.test(r.stage)?'Revisar si es una pérdida real; necesita motivo y evidencia.':/contactar|contacto.*adelante/i.test(r.stage)?'Planificar una fecha; decidir si la propuesta sigue abierta o se cerró.':/suscript/i.test(r.stage)?'Verificar qué se aceptó; no acredita pago ni reemplaza Cliente.':'Revisar significado y próximo paso por caso.'}</td></tr>)}</tbody></table><p>No se propone una conversión masiva: un mismo estado histórico puede representar resultados diferentes. Cada cierre explícito conserva el valor anterior y su motivo en el historial.</p></details>
 <details><summary>Auditoría de configuración · últimos 100 cambios</summary>{d.configJournal.map(j=><article key={j.id}><p>{new Date(j.createdAt).toLocaleString("es-AR")} · {j.actorEmail||"Sistema"} · {j.entity}</p><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify({antes:j.beforeValue,después:j.afterValue},null,2)}</pre></article>)}</details></section>;
}
