import {useUnsavedChanges} from './UnsavedChanges';
import {ContactPolicy} from "./ContactPolicy";
import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {toast} from 'sonner';
import {getPipeline,postPipeline,type PipelineData,type PipelineMutation,type PipelineInsight,type ReactivationRow,type PipelineObjection} from '../endpoints/pipeline.schema';
import type {Opportunity} from '../endpoints/commercial.schema';
import {formatDate} from '../helpers/crmDates';
import {prettyInstant,localDay} from '../helpers/workDates';
import {useAuth} from '../helpers/useAuth';
import {Button} from './Button';
import {Dialog,DialogContent,DialogTitle} from './Dialog';
import styles from './Pipeline.module.css';
import shared from './Commercial.module.css';
export const classificationNames={open:'Abierta',won:'Ganada',lost:'Perdida'};
export function PriorityExplanation({manual,insight}:{manual:string|null;insight?:PipelineInsight}){
 return <div className={styles.suggestion}><div>Prioridad manual: <strong>{manual||'Sin definir'}</strong></div>{insight&&<><div>Sugerencia: <strong>{insight.suggestion.priority||'Sin sugerencia'}</strong></div>{!!insight.suggestion.factors.length&&<ul>{insight.suggestion.factors.map(f=><li key={f.id}>{f.name} → {f.priority}</li>)}</ul>}</>}<span className={styles.meta}>La sugerencia no modifica tu decisión.</span></div>;
}
type Target={kind:'stage';lead:Opportunity}|{kind:'objection';lead:Opportunity;item?:PipelineObjection}|{kind:'reactivate';row:ReactivationRow};
export function PipelineEditor({target,data,onClose}:{target:Target;data:PipelineData;onClose:()=>void}){
 const qc=useQueryClient();const item=target.kind==='objection'?target.item:undefined;
 const [stage,setStage]=useState(target.kind==='stage'?target.lead.estado??'':data.stages.find(s=>s.active&&s.classification==='open')?.name??'');
 const [reason,setReason]=useState('');const [comment,setComment]=useState(item?.notes??'');const [date,setDate]=useState(target.kind==='reactivate'?target.row.recontactDate:localDay());
 const [hasDate,setHasDate]=useState(false);const [typeId,setTypeId]=useState(item?.typeId??'');const [status,setStatus]=useState<PipelineObjection['status']>(item?.status??'open');const [mode,setMode]=useState<'followup'|'reopen'|'new'>('followup');const [name,setName]=useState('');const [title,setTitle]=useState('Retomar conversación');
 const m=useMutation({mutationFn:postPipeline,onSuccess:async()=>{await qc.invalidateQueries();toast.success('Cambio registrado');onClose();},onError:()=>{void qc.invalidateQueries({queryKey:['pipeline']});void qc.invalidateQueries({queryKey:['leads']});}});
 const lost=data.stages.find(s=>s.name===stage)?.classification==='lost';
 const won=data.stages.find(s=>s.name===stage)?.classification==='won';
 const [convertClient,setConvert]=useState(false),[onboard,setOnboard]=useState(false),[onboardTitle,setOnboardTitle]=useState('Acompañar el inicio y revisar lo acordado');
 const values=JSON.stringify({stage,reason,comment,date,hasDate,typeId,status,mode,name,title,convertClient,onboard,onboardTitle});const [baseline]=useState(values);const guard=useUnsavedChanges(values!==baseline,onClose);
 const insight=target.kind!=='reactivate'?data.insights.find(x=>x.id===target.lead.id):undefined;
 // Freeze the observed revision when the editor opens; Live Mode must not bless a stale form.
 const [revision]=useState(()=>target.kind==='reactivate'?target.row.pipelineRevision:insight?.pipelineRevision??target.lead.pipelineRevision);
 function submit(deleted=false){
  let body:PipelineMutation;
  if(target.kind==='stage')body={action:'transition',leadId:target.lead.id,revision,stage,convertClient:won&&convertClient,...(won&&onboard?{onboarding:{title:onboardTitle,dueDate:date}}:{}),...(lost?{reasonId:reason,recontactDate:hasDate?date:null}:{}),comment};
  else if(target.kind==='objection')body={action:'objection_save',leadId:target.lead.id,revision,id:item?.id,typeId,notes:comment,status,deleted};
  else body={action:'reactivate',leadId:target.row.id,eventId:target.row.eventId,revision,mode,stage:mode==='followup'?undefined:stage,opportunityName:mode==='new'?name:undefined,dueDate:date,title};
  m.mutate(body);
 }
 return <Dialog open onOpenChange={v=>!v&&guard.requestClose()}><DialogContent className={shared.editor}><DialogTitle>{target.kind==='stage'?'Cambiar etapa':target.kind==='objection'?'Objeción comercial':'Planificar reactivación'}</DialogTitle><form className={styles.form} onSubmit={e=>{e.preventDefault();submit();}}>
  {target.kind==='stage'&&<><p className={styles.meta}>Elegí la etapa que refleja lo que ocurrió. Una venta ganada permite marcar al negocio como cliente; el pago se verifica por separado.</p><label>Etapa<select required value={stage} onChange={e=>setStage(e.target.value)}><option value="">Elegí una etapa</option>{data.stages.filter(s=>s.active||s.name===target.lead.estado).map(s=><option key={s.name} value={s.name}>{s.name} · {classificationNames[s.classification]}{!s.active?' (inactiva)':''}</option>)}</select></label>{lost&&<><label>Motivo de pérdida<select required value={reason} onChange={e=>setReason(e.target.value)}><option value="">Elegí un motivo</option>{data.lossReasons.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={hasDate} onChange={e=>setHasDate(e.target.checked)}/>Definir fecha para retomar</label>{hasDate&&<label>Fecha de recontacto<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>}</>}{won&&<fieldset><legend>Organizar el inicio</legend><p>La venta queda ganada. Esto no verifica pagos ni activa servicios del portal.</p><label className={styles.check}><input type="checkbox" checked={convertClient} onChange={e=>setConvert(e.target.checked)}/>Marcar este negocio como cliente</label><label className={styles.check}><input type="checkbox" checked={onboard} onChange={e=>setOnboard(e.target.checked)}/>Crear una tarea de acompañamiento</label>{onboard&&<><label>Qué hacer<input required value={onboardTitle} onChange={e=>setOnboardTitle(e.target.value)}/></label><label>Fecha<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>}<p>Las otras ventas y tareas del negocio se conservan. Revisá si hay compromisos pendientes.</p></fieldset>}</>}
  {target.kind==='objection'&&<><p className={styles.meta}>Una duda pendiente no equivale a una venta perdida.</p><label>Objeción<select required disabled={!!item} value={typeId} onChange={e=>setTypeId(e.target.value)}><option value="">Elegí una objeción</option>{data.objectionTypes.filter(t=>t.active||t.id===typeId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="open">Pendiente</option><option value="resolved">Resuelta</option><option value="dismissed">Descartada</option></select></label></>}
  {target.kind==='reactivate'&&<><p className={styles.meta}>{target.row.nombre} · {target.row.opportunityName||'Gestión comercial inicial'}. El cierre anterior queda conservado.</p><label>Acción<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="followup">Crear seguimiento y conservar cerrada</option><option value="reopen">Reabrir esta oportunidad y crear seguimiento</option><option value="new">Crear otra oportunidad vinculada y seguimiento</option></select></label>{mode!=='followup'&&<label>Etapa abierta<select required value={stage} onChange={e=>setStage(e.target.value)}><option value="">Elegí una etapa</option>{data.stages.filter(s=>s.active&&s.classification==='open').map(s=><option key={s.name}>{s.name}</option>)}</select></label>}{mode==='new'&&<label>Nombre de la nueva venta<input required maxLength={300} value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Seguimiento<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Vencimiento de la tarea<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>}
  {target.kind!=='reactivate'&&<label>{target.kind==='objection'?'Notas / resolución':'Comentario'}<textarea maxLength={4000} value={comment} onChange={e=>setComment(e.target.value)}/></label>}
  {m.error&&<p className={styles.error} role="alert">{m.error.message}</p>}<div className={shared.actions}><Button type="submit" disabled={m.isPending}>Guardar</Button><Button type="button" variant="outline" onClick={guard.requestClose}>Cancelar</Button>{item&&<Button type="button" variant="destructive" disabled={m.isPending} onClick={()=>submit(true)}>Dar de baja</Button>}</div>
 </form></DialogContent>{guard.confirmation}</Dialog>;
}
export function PipelineBoard({leads,onOpen}:{leads:Opportunity[];onOpen:(lead:Opportunity)=>void}){
 const ids=leads.map(l=>l.id).join(',');const q=useQuery({queryKey:['pipeline','board',ids],queryFn:async()=>{if(!ids)return getPipeline({});const chunks=Array.from({length:Math.ceil(leads.length/100)},(_,i)=>leads.slice(i*100,i*100+100).map(l=>l.id).join(','));const results=await Promise.all(chunks.map(ids=>getPipeline({ids})));return {...results[0],insights:results.flatMap(d=>d.insights)};}});const [target,setTarget]=useState<Target|null>(null);
 const {authState}=useAuth();const user=authState.type==='authenticated'?authState.user:null;
 if(q.error)return <p role="alert">{q.error.message}</p>;if(!q.data)return <p>Cargando pipeline…</p>;const data=q.data;
 const columns=[...data.stages.filter(s=>s.active||leads.some(l=>l.estado===s.name)).map(s=>({name:s.name,key:s.name,classification:classificationNames[s.classification]})),...(leads.some(l=>l.estado===null)?[{name:'Sin etapa histórica',key:null,classification:'Sin clasificar'}]:[])];
 return <><p className={styles.meta} style={{padding:'0 12px'}}>Todas las ventas que coinciden con los filtros. Abrí una venta para ver qué hacer después.</p><div className={styles.board} aria-label="Pipeline comercial">{columns.map(s=>{const rows=leads.filter(l=>l.estado===s.key);return <section key={s.key??'__null'} className={styles.column}><h3>{s.name||'Etapa histórica vacía'}<span>{rows.length}</span></h3><span className={styles.meta}>{s.classification}</span>{rows.map(l=>{const i=data.insights.find(x=>x.id===l.id);return <article key={l.id} className={styles.card}><strong>{l.opportunityName||'Gestión comercial inicial'}</strong><p>{l.nombre}</p><div className={styles.meta}>{l.tipo||'Sin vertical'} · {l.assignedUserEmail||'Sin responsable'}</div><div className={styles.meta}>{i?.stageSince?`${Math.max(0,Math.floor((Date.now()-new Date(i.stageSince).getTime())/86400000))} días en etapa`:'Tiempo en etapa histórico desconocido'}</div>{i&&!i.pendingFollowup&&<div className={styles.warning}>Sin seguimiento pendiente</div>}<PriorityExplanation manual={l.prioridad} insight={i}/><div className={shared.actions}><Button size="sm" variant="outline" onClick={()=>onOpen(l)}>Abrir</Button>{user&&(user.role==='admin'||l.assignedUserEmail===user.email)&&<Button size="sm" onClick={()=>setTarget({kind:'stage',lead:l})}>Cambiar etapa</Button>}</div></article>})}{!rows.length&&<p className={styles.empty}>Sin ventas en esta etapa</p>}</section>})}</div>{target&&<PipelineEditor target={target} data={data} onClose={()=>setTarget(null)}/>}</>;
}
export function PipelineDetail({lead}:{lead:Opportunity}){
 const q=useQuery({queryKey:['pipeline','detail',lead.id],queryFn:()=>getPipeline({leadId:lead.id})});const [target,setTarget]=useState<Target|null>(null);const {authState}=useAuth();const user=authState.type==='authenticated'?authState.user:null;
 
 if(q.error)return <p role="alert">{q.error.message}</p>;if(!q.data)return <p>Cargando gestión comercial…</p>;const d=q.data,i=d.insights[0];
 const currentLead=i?{...lead,estado:i.estado,prioridad:i.manualPriority,assignedUserEmail:i.assignedUserEmail,pipelineRevision:i.pipelineRevision}:lead;
 const can=user&&(user.role==='admin'||currentLead.assignedUserEmail===user.email);
 const last=d.events.find(e=>e.action==='stage');
 const eligible=last?.classification==='lost'&&last.reasonId&&!last.taskId&&!last.relatedLeadId&&d.stages.find(s=>s.name===currentLead.estado)?.classification==='lost';
 return <div className={styles.detail}><ContactPolicy accountId={lead.accountId} blocked={i?.doNotContact??false}/><section className={shared.panel}><div className={shared.heading}><h3>Etapa y prioridad</h3>{can&&<Button size="sm" onClick={()=>setTarget({kind:'stage',lead:currentLead})}>Cambiar etapa</Button>}</div><p>{currentLead.estado||'Sin etapa histórica'} · {i?.stageSince?prettyInstant(i.stageSince):'Inicio de etapa histórico desconocido'}</p>{i?.doNotContact&&<p className={styles.warning}>Negocio marcado como No contactar</p>}<PriorityExplanation manual={currentLead.prioridad} insight={i}/>{eligible&&can&&<Button disabled={i?.doNotContact} variant="outline" onClick={()=>setTarget({kind:'reactivate',row:{id:lead.id,accountId:lead.accountId,nombre:lead.nombre,opportunityName:lead.opportunityName,tipo:lead.tipo,assignedUserEmail:lead.assignedUserEmail,estado:currentLead.estado!,pipelineRevision:i?.pipelineRevision??lead.pipelineRevision,eventId:last.id,reasonId:last.reasonId!,comment:last.comment,recontactDate:last.recontactDate??localDay(),taskId:null,doNotContact:i?.doNotContact??false}})}>Planificar reactivación</Button>}</section>
 <section className={shared.panel}><div className={shared.heading}><h3>Objeciones</h3>{can&&<Button size="sm" variant="outline" onClick={()=>setTarget({kind:'objection',lead:currentLead})}>Agregar objeción</Button>}</div>{!d.objections.length&&<p className={styles.empty}>No hay objeciones registradas.</p>}{d.objections.map(o=><article key={o.id} className={styles.card}><strong>{d.objectionTypes.find(t=>t.id===o.typeId)?.name}</strong><p>{{open:'Pendiente',resolved:'Resuelta',dismissed:'Descartada'}[o.status]}</p>{o.notes&&<p style={{whiteSpace:'pre-wrap'}}>{o.notes}</p>}{can&&<Button size="sm" variant="outline" onClick={()=>setTarget({kind:'objection',lead:currentLead,item:o})}>Editar / resolver</Button>}</article>)}</section>
 <details className={styles.history}><summary>Historial del pipeline · últimos 200 eventos</summary>{!d.events.length&&<p className={styles.empty}>No se inventan eventos ni fechas para estados históricos.</p>}{d.events.map(e=><article className={styles.event} key={e.id}><time>{prettyInstant(e.createdAt)}</time> · {e.actorEmail||'Sistema'}<p>{e.action==='stage'?`${e.oldStage??'Sin etapa'} → ${e.newStage??'Sin etapa'}`:e.action==='reactivation'?'Reactivación planificada':e.action==='objection'?'Objeción actualizada':e.action}</p>{e.reasonId&&<p>Motivo: {d.lossReasons.find(r=>r.id===e.reasonId)?.name}</p>}{e.comment&&<p>{e.comment}</p>}{e.recontactDate&&<p>Recontacto: {formatDate(e.recontactDate)}</p>}{e.taskId&&<Link to="/my-day">Seguimiento #{e.taskId}</Link>}{e.relatedLeadId&&<p><Link to={'/opportunities?leadId='+e.relatedLeadId}>Oportunidad vinculada #{e.relatedLeadId}</Link></p>}{e.action==='reactivation'&&<p>Seguimiento explícito; cierre anterior conservado.</p>}{e.action==='objection'&&<details><summary>Ver evidencia</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(e.metadata,null,2)}</pre></details>}</article>)}</details>{target&&<PipelineEditor target={target} data={d} onClose={()=>setTarget(null)}/>}</div>;
}
