import {ResourceLinkForm} from "./ResourceLinkForm";
import {Link} from "react-router-dom";
import { Disclosure, DisclosureSummary } from './Disclosure';
import { Input } from './Input';
import { NativeSelect } from './NativeSelect';
import {useUnsavedChanges} from './UnsavedChanges';
import {DocumentPreviewDialog,canPreviewDocument} from './DocumentPreviewDialog';
import {calendarDay} from '../helpers/workDates';
import {formatDate} from '../helpers/crmDates';
import {getCommercialDetail,getCommercialList} from '../endpoints/commercial.schema';
import {getWork} from '../endpoints/work.schema';
import React,{useState} from 'react';import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';import {getResources,postResource,type ResourceVersion} from '../endpoints/resources.schema';import {useAuth} from '../helpers/useAuth';import {Button} from './Button';import styles from './Communication.module.css';
export function ResourcesPanel({accountId,leadId,activityId,manageLibrary=false,readOnly=false}:{accountId?:string;leadId?:string;activityId?:string;manageLibrary?:boolean;readOnly?:boolean}){
 const {authState}=useAuth(),qc=useQueryClient();const admin=authState.type==='authenticated'&&authState.user.role==='admin';const email=authState.type==='authenticated'?authState.user.email:'';
 const [previewVersion,setPreviewVersion]=useState<ResourceVersion|null>(null);
 const [linkDoc,setLinkDoc]=useState(''),[targetSearch,setTargetSearch]=useState(''),[targetAccount,setTargetAccount]=useState(''),[contextLead,setContextLead]=useState(''),[contextActivity,setContextActivity]=useState('');
 const [search,setSearch]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[title,setTitle]=useState(''),[type,setType]=useState('propuesta'),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[expires,setExpires]=useState(''),[category,setCategory]=useState(''),[versionTarget,setVersionTarget]=useState<{id:string;revision:number}|null>(null),[categoryName,setCategoryName]=useState(''),[error,setError]=useState('');
 const q=useQuery({queryKey:['resources',accountId??'',search,leadId??''],queryFn:()=>getResources(accountId,search,leadId)});
 const libraryQ=useQuery({queryKey:['resources','library',''],queryFn:()=>getResources(),enabled:!!accountId&&!readOnly});
 const accountsQ=useQuery({queryKey:['commercial','resource-target',targetSearch],queryFn:()=>getCommercialList(targetSearch,'',1),enabled:!!linkDoc&&!accountId});
 const scopeAccount=accountId||targetAccount;
 const contextQ=useQuery({queryKey:['commercial-detail',scopeAccount??'',''],queryFn:()=>getCommercialDetail(scopeAccount),enabled:!!scopeAccount});
 const workQ=useQuery({queryKey:['work','resource-context',scopeAccount],queryFn:()=>getWork({accountId:scopeAccount,mode:'detail',responsible:admin?'all':undefined}),enabled:!!scopeAccount&&!readOnly&&admin});
 const draftGuard=useUnsavedChanges(!!title.trim()||!!url.trim()||!!file,()=>{});
 const m=useMutation({mutationFn:postResource,onSuccess:()=>{void qc.invalidateQueries({queryKey:['resources']});setVersionTarget(null);setTitle('');setUrl('');setFile(null);setError('');setLinkDoc('')}});
 async function submit(){try{setError('');let fileData:string|undefined;if(file){if(file.size>(q.data?.maxDocumentBytes??2097152))throw new Error('Archivo demasiado grande');fileData=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});}const version={...(file?{fileData,fileName:file.name,mimeType:file.type as any}:{url}),expiresOn:expires||null};if(versionTarget)m.mutate({action:'version',...versionTarget,version});else m.mutate({action:'create',id:crypto.randomUUID(),title,type,accountId:accountId??null,leadId:leadId||contextLead||null,activityId:activityId||contextActivity||null,library:!accountId,categoryId:category||null,version});}catch(e){setError(e instanceof Error?e.message:'Archivo inválido')}}
 const vLink=(v:ResourceVersion)=><span className={styles.documentLinks}><a href={'/_api/resources/download?versionId='+v.id} target="_blank" rel="noopener noreferrer">{v.url?'Abrir vínculo':'Descargar documento'} · v{v.version}</a>{canPreviewDocument(v)&&<Button size="sm" variant="outline" onClick={()=>setPreviewVersion(v)} aria-label={'Previsualizar '+v.fileName+' · v'+v.version}>Previsualizar</Button>}</span>;
 if(q.isPending)return <p>Cargando documentos…</p>;if(q.error)return <div role="alert"><p>{q.error.message}</p><Button variant="outline" onClick={()=>{void q.refetch()}}>Reintentar documentos</Button></div>;
 return <section className={styles.panel}>{accountId&&<><h3>{leadId?"Documentos de esta gestión":"Documentos del negocio"}</h3>{leadId&&<p><Link to={"/accounts/"+accountId+"?section=documents"}>Consultar todos los documentos del negocio</Link></p>}</>}<p className={styles.muted}>Recursos aprobados para consultar y reutilizar. La biblioteca se administra desde Configuración por un admin. Vincular un documento no lo envía al cliente. Abrilo y elegí cómo compartirlo.</p>
 <div className={styles.grid}>{!accountId&&<label>Buscar recurso<Input value={search} onChange={e=>setSearch(e.target.value)}/></label>}<label>Categoría<NativeSelect value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Todas</option>{q.data.categories.map(c=><option key={c.id} value={c.id}>{c.name}{c.active?'':' (inactiva)'}</option>)}</NativeSelect></label></div>
 {accountId&&!readOnly&&<ResourceLinkForm key={accountId+':'+(leadId??'')} accountId={accountId} leadId={leadId} documents={libraryQ.data?.documents??[]} loading={libraryQ.isPending||libraryQ.isFetching} error={libraryQ.error} onRetry={()=>{void libraryQ.refetch()}} onPreview={setPreviewVersion}/>}
 {(!readOnly&&!accountId&&linkDoc)&&<Disclosure open={!!linkDoc}><DisclosureSummary>Vincular recurso aprobado sin copiar</DisclosureSummary><div className={styles.panel}>{!accountId&&<><label>Buscar negocio destino<Input value={targetSearch} onChange={e=>setTargetSearch(e.target.value)}/></label><label>Negocio destino<NativeSelect value={targetAccount} onChange={e=>{setTargetAccount(e.target.value);setContextLead('');setContextActivity('')}}><option value="">Elegir negocio</option>{accountsQ.data?.rows.map(a=><option key={a.id} value={a.id}>{a.nombre} · {a.ciudad}</option>)}</NativeSelect></label></>}<Button disabled={!scopeAccount||!linkDoc||m.isPending} onClick={()=>m.mutate({action:'link',id:linkDoc,accountId:scopeAccount!,leadId:leadId||contextLead||null,activityId:activityId||contextActivity||null})}>Confirmar vínculo al contexto</Button></div></Disclosure>}
 {accountId&&!leadId&&!readOnly&&admin&&<label>Gestión vinculada (opcional)<NativeSelect value={contextLead} onChange={e=>{setContextLead(e.target.value);setContextActivity('')}}><option value="">Documento general del negocio</option>{contextQ.data?.opportunities.filter(o=>!o.deletedAt).map(o=><option key={o.id} value={o.id}>{o.opportunityName||'Gestión comercial inicial'}</option>)}</NativeSelect></label>}
 {accountId&&!activityId&&!readOnly&&admin&&<label>Actividad vinculada (opcional)<NativeSelect value={contextActivity} onChange={e=>setContextActivity(e.target.value)}><option value="">Sin actividad específica</option>{workQ.data?.activities.filter(a=>!(leadId||contextLead)||String(a.leadId)===(leadId||contextLead)).map(a=><option key={a.id} value={a.id}>{a.title} · {new Date(a.occurredAt).toLocaleDateString('es-AR')}</option>)}</NativeSelect></label>}
 {(!readOnly&&admin&&(!!accountId||manageLibrary))&&<Disclosure open={!!versionTarget}><DisclosureSummary>{versionTarget?'Agregar versión':'Agregar documento o recurso'}</DisclosureSummary><div className={styles.panel}>{!versionTarget&&<><div className={styles.grid}><label>Título del documento<Input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Tipo de documento<Input value={type} onChange={e=>setType(e.target.value)}/></label><label>Categoría del recurso<NativeSelect value={category} onChange={e=>setCategory(e.target.value)}><option value="">Sin categoría</option>{q.data.categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label></div></>}
 <label>Vínculo HTTP(S)<Input type="url" value={url} disabled={!!file} onChange={e=>setUrl(e.target.value)}/></label><label>O archivo<Input key={versionTarget?.id??'create'} type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" disabled={!!url} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Vencimiento opcional<Input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><div className={styles.actions}><Button disabled={m.isPending||(!file&&!url)||(!versionTarget&&title.trim().length<3)} onClick={()=>void submit()}>Guardar documento</Button>{versionTarget&&<Button variant="ghost" onClick={()=>setVersionTarget(null)}>Cancelar versión</Button>}</div><p className={styles.muted}>Una nueva versión vuelve a borrador y requiere aprobación. No elimina versiones anteriores.</p></div></Disclosure>}
 {accountId&&!q.data.documents.length&&<p className={styles.muted}>{leadId?"Esta gestión todavía no tiene documentos vinculados.":"Este negocio todavía no tiene documentos vinculados."}</p>}
 {q.data.documents.filter(d=>!categoryFilter||String(d.categoryId)===categoryFilter).map(d=>{const latest=d.versions[0];const canEdit=!readOnly&&admin&&(!d.library||manageLibrary);return <article key={d.id}><h3>{d.title} · {d.status==='approved'?'Aprobado':d.status==='draft'?'Borrador':'Archivado'}</h3>{accountId&&<p className={styles.materialScope}>{d.leadId?'Gestión: '+(contextQ.data?.opportunities.find(o=>String(o.id)===String(d.leadId))?.opportunityName||'Gestión comercial inicial'):!d.library?'Documento general del negocio':null}{d.links?.map((link,i)=><span key={i}>{link.leadId?'Gestión: '+(link.leadName||'Gestión comercial inicial'):'Documento general del negocio'}{link.activityTitle?' · Actividad: '+link.activityTitle:''}</span>)}</p>}<p>{d.type} · {q.data.categories.find(c=>String(c.id)===String(d.categoryId))?.name||'Sin categoría'}</p><p className={styles.muted}>{new Date(d.createdAt).toLocaleDateString('es-AR')}</p>{latest&&<><Disclosure><DisclosureSummary>Detalles del archivo y responsables</DisclosureSummary><p>{latest.fileName||'Vínculo externo'}{latest.byteSize!=null?' · '+Math.ceil(latest.byteSize/1024)+' KB':''}{latest.mimeType?' · '+latest.mimeType:''}</p><p>Responsable: {d.ownerEmail}</p><p>{d.approvedBy?'Aprobado por '+d.approvedBy:'Aprobación pendiente'}</p></Disclosure>{vLink(latest)}{latest.expiresOn&&<p>Vencimiento: {formatDate(calendarDay(latest.expiresOn))}</p>}</>}
 <div className={styles.actions}>{canEdit&&latest&&<><Button size="sm" variant="outline" onClick={()=>{setVersionTarget({id:d.id,revision:latest.version});setUrl('');setFile(null);setExpires('')}}>Nueva versión</Button>{admin&&d.status!=='approved'&&<Button size="sm" onClick={()=>m.mutate({action:'status',id:d.id,status:'approved',revision:latest.version})}>Aprobar versión</Button>}<Button size="sm" variant="outline" onClick={()=>m.mutate({action:'status',id:d.id,status:d.status==='archived'?'draft':'archived',revision:latest.version})}>{d.status==='archived'?'Volver a borrador':'Archivar'}</Button><Button size="sm" variant="ghost" onClick={()=>{if(window.confirm('¿Dar de baja este documento? Conserva versiones e historial.'))m.mutate({action:'delete',id:d.id,revision:latest.version})}}>Dar de baja</Button></>}
 {d.library&&d.status==='approved'&&!accountId&&<Button size="sm" variant="outline" onClick={()=>setLinkDoc(d.id)}>Vincular a negocio</Button>}</div>
 <Disclosure><DisclosureSummary>Versiones anteriores ({d.versions.length-1})</DisclosureSummary>{d.versions.slice(1).map(v=><p key={v.id}>{vLink(v)} · {v.actorEmail} · {new Date(v.createdAt).toLocaleString('es-AR')}</p>)}</Disclosure></article>})}
 {admin&&manageLibrary&&<Disclosure><DisclosureSummary>Configurar categorías</DisclosureSummary><div className={styles.panel}><label>Nombre de categoría<Input value={categoryName} onChange={e=>setCategoryName(e.target.value)}/></label><Button disabled={categoryName.trim().length<2||m.isPending} onClick={()=>m.mutate({action:'category',name:categoryName,active:true})}>Agregar categoría</Button>{q.data.categories.map(c=><p key={c.id}>{c.name} <Button size="sm" variant="ghost" onClick={()=>m.mutate({action:'category',id:c.id,name:c.name,active:!c.active})}>{c.active?'Desactivar':'Activar'}</Button></p>)}</div></Disclosure>}
 {(error||m.error)&&<p role="alert">{error||m.error?.message}</p>}
 {draftGuard.confirmation}
 {previewVersion&&<DocumentPreviewDialog key={previewVersion.id} version={previewVersion} onClose={()=>setPreviewVersion(null)}/>}
 </section>;
}
