import { Disclosure, DisclosureSummary } from './Disclosure';
import { Input } from './Input';
import { NativeSelect } from './NativeSelect';
import superjson from 'superjson';
import React,{useState} from 'react';import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {postCommunication} from '../endpoints/communication.schema';import {Button} from './Button';import styles from './Communication.module.css';
export function SequenceSettings(){
 const qc=useQueryClient();
 const q=useQuery({queryKey:['communication','config'],queryFn:async()=>{const r=await fetch('/_api/communication?mode=config');const d=superjson.parse<any>(await r.text());if(!r.ok)throw new Error(d.error);return d}});
 const [editingSequence,setEditingSequence]=useState<string|undefined>();
 const [name,setName]=useState(''),[scope,setScope]=useState(''),[steps,setSteps]=useState<{waitDays:number;channel:'email'|'whatsapp';templateId:string}[]>([{waitDays:0,channel:'email',templateId:''}]);
 const templates=useQuery({queryKey:['sequence-templates'],queryFn:async()=>{const r=await fetch('/_api/settings');const d=superjson.parse<any>(await r.text());if(!r.ok)throw new Error(d.error);return d.templates??d.messageTemplates??[]}});
 const m=useMutation({mutationFn:postCommunication,onSuccess:()=>qc.invalidateQueries({queryKey:['communication']})});
 if(q.isPending)return <p>Cargando seguimientos…</p>;if(q.error)return <p role="alert">{q.error.message}</p>;
 return <section><h2>Seguimientos asistidos</h2><p>Se configuran una vez para todo el equipo. Cada ejecución conserva la versión con la que se inició. Nunca se envían mensajes automáticamente.</p> <Disclosure><DisclosureSummary>Configurar secuencia</DisclosureSummary><div className={styles.panel}><label>Nombre de secuencia<Input value={name} onChange={e=>setName(e.target.value)}/></label><label>Alcance y uso previsto<Input value={scope} onChange={e=>setScope(e.target.value)}/></label>{steps.map((s,i)=><div key={i} className={styles.grid}><label>Espera desde paso anterior (días)<Input type="number" min={0} max={365} value={s.waitDays} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,waitDays:Number(e.target.value)}:p))}/></label><label>Canal<NativeSelect aria-label="Canal del paso" value={s.channel} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,channel:e.target.value as any,templateId:''}:p))}><option value="email">Email</option><option value="whatsapp">WhatsApp</option></NativeSelect></label><label>Template<NativeSelect aria-label="Template del paso" value={s.templateId} onChange={e=>setSteps(steps.map((p,j)=>j===i?{...p,templateId:e.target.value}:p))}><option value="">Elegir</option>{templates.data?.filter((t:any)=>t.channel===s.channel).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</NativeSelect></label></div>)}<div className={styles.actions}><Button variant="outline" disabled={steps.length>=12} onClick={()=>setSteps([...steps,{waitDays:3,channel:'email',templateId:''}])}>Agregar paso</Button><Button disabled={name.trim().length<3||scope.trim().length<3||steps.some(s=>!s.templateId)||m.isPending} onClick={()=>m.mutate({action:'sequence_save',id:editingSequence,name,scope,steps,active:true})}>Guardar secuencia</Button></div>{q.data.sequences.map((s:any)=><p key={s.id}>{s.name} · {s.active?'Activa':'Inactiva'} <Button size="sm" variant="ghost" onClick={()=>{setEditingSequence(String(s.id));setName(s.name);setScope(s.scope);setSteps(s.steps)}}>Editar configuración</Button><Button size="sm" variant="ghost" onClick={()=>m.mutate({action:'sequence_save',id:String(s.id),name:s.name,scope:s.scope,steps:s.steps,active:!s.active})}>{s.active?'Desactivar':'Activar'}</Button></p>)}</div></Disclosure>{m.error&&<p role="alert">{m.error.message}</p>}</section>;
}
