import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import superjson from 'superjson';import {sql} from 'kysely';import {db} from '../src/helpers/db';import {post,get,webhook} from '../src/endpoints/communication';import {post as resourcePost,get as resourcesGet,download} from '../src/endpoints/resources';import {handle as legacySend} from '../src/endpoints/send_template_email_POST';import {setServerSession} from '../src/helpers/getSetServerSession';import {businessFields} from '../src/helpers/dataNormalization';import {post as quality} from '../src/endpoints/dataQuality';import type {Message} from '../src/endpoints/communication.schema';
assert.equal(process.env.CRM_TEST_DATABASE,'1');const stamp=Date.now();
async function identity(role:'admin'|'user'){const u=await db.insertInto('users').values({email:`communication-${role}-${randomUUID()}@example.com`,displayName:role,role}).returningAll().executeTakeFirstOrThrow();const s={id:u.email,createdAt:Date.now(),lastAccessed:Date.now()};await db.insertInto('sessions').values({id:s.id,userId:u.id,expiresAt:new Date(Date.now()+3600000)}).execute();const r=new Response();await setServerSession(r,s);return {user:u,cookie:r.headers.get('set-cookie')!.split(';')[0]};}
const admin=await identity('admin'),user=await identity('user'),other=await identity('user');
const request=(body:unknown,cookie=admin.cookie)=>new Request('http://localhost/_api/communication',{method:'POST',headers:{cookie},body:superjson.stringify(body)});
async function call(body:unknown,status=200,cookie=admin.cookie){const r=await post(request(body,cookie));const d=superjson.parse<any>(await r.text());assert.equal(r.status,status,d.error);return d;}
async function resource(body:unknown,status=200,cookie=admin.cookie){const r=await resourcePost(request(body,cookie));const d=superjson.parse<any>(await r.text());assert.equal(r.status,status,d.error);return d;}
async function message(id:string){return (await sql<Message>`SELECT * FROM crm_messages WHERE id=${id}::uuid`.execute(db)).rows[0];}
let realFetch=globalThis.fetch;
try{
 assert.equal((await get(new Request('http://localhost/_api/communication?leadId=1'))).status,401);assert.equal((await resourcePost(request({},''))).status,401);assert.equal((await download(new Request('http://localhost/_api/resources/download?versionId='+randomUUID()))).status,401);assert.equal((await legacySend(request({}))).status,409);
 const a=await db.insertInto('crmAccounts').values({nombre:'Communication '+stamp,ciudad:'Colón',email:'generic@example.com',telefono:'5493442000001',assignedUserEmail:user.user.email}).returningAll().executeTakeFirstOrThrow();
 const l=await db.insertInto('leads').values({accountId:a.id,nombre:a.nombre,estado:'Cargado',assignedUserEmail:user.user.email}).returningAll().executeTakeFirstOrThrow();
 const c=await db.insertInto('crmContacts').values({accountId:a.id,name:'Persona real',email:'person@example.com',phone:'+5493442000002'}).returningAll().executeTakeFirstOrThrow();
 const t=await db.insertInto('messageTemplates').values({name:'Fixture email',channel:'email',subject:'Hola {{contact}}',body:'<p>{{#if contact}}Hola {{contact}}{{else}}Hola{{/if}} <strong>Hospeda</strong></p>'}).returningAll().executeTakeFirstOrThrow();const w=await db.insertInto('messageTemplates').values({name:'Fixture WhatsApp',channel:'whatsapp',body:'<p><strong>Hola {{contact}}</strong> <em>Hospeda</em></p>'}).returningAll().executeTakeFirstOrThrow();
 await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},403,other.cookie);
 const id=randomUUID();let m=await call({action:'prepare',id,leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie);assert(m.body.includes('Persona real'));assert(m.templateSnapshot.version,JSON.stringify(m.templateSnapshot));assert.equal((await call({action:'prepare',id,leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie)).id,id);
 await call({action:'dispatch',id,revision:m.revision,confirm:true},409,user.cookie);
 await db.updateTable('messageTemplates').set({body:'<p>Otro contenido</p>'}).where('id','=',t.id).execute();assert((await message(id)).body.includes('Persona real'));
 await call({action:'edit',id,revision:99,subject:'Final',body:'<p>Final</p>'},409,user.cookie);
 m=await call({action:'edit',id,revision:m.revision,subject:'Asunto final',body:'<p>Final real <strong>Texto</strong><script>alert(1)</script></p>'},200,user.cookie);assert(!m.htmlBody.includes('<script'));assert(m.htmlBody.includes('Final real'));assert.equal(m.subject,'Asunto final');
 process.env.BREVO_API_KEY='fixture-never-network';await db.insertInto('appSettings').values({key:'brevo_sender_email',value:'sender@example.com'}).onConflict(oc=>oc.column('key').doUpdateSet({value:'sender@example.com'})).execute();
 let sends=0;globalThis.fetch=async (url,init)=>{assert.equal(String(url),'https://api.brevo.com/v3/smtp/email');sends++;const payload=JSON.parse(String(init?.body));assert.equal(payload.htmlContent,m.htmlBody);assert.equal(payload.to[0].name,'Persona real');return new Response(JSON.stringify({messageId:'<fixture-'+id+'@brevo.test>'}),{status:201})};
 await Promise.all([call({action:'dispatch',id,revision:m.revision,confirm:true},200,user.cookie),call({action:'dispatch',id,revision:m.revision,confirm:true},200,user.cookie)]).catch(e=>{if(!String(e).includes('409'))throw e});assert.equal(sends,1);assert.equal((await message(id)).status,'accepted');await call({action:'dispatch',id,revision:m.revision,confirm:true},200,user.cookie);assert.equal(sends,1);
 const originalInteraction=(await message(id)).lastInteractionAt!.getTime();assert.equal((await message(id)).lastActorEmail,user.user.email);
 process.env.BREVO_WEBHOOK_TOKEN='fixture-webhook-token-at-least-32-characters';const at=Math.floor(Date.now()/1000)-20;const event=(event:string,ts_event:number)=>({event,email:'person@example.com','message-id':'fixture-'+id+'@brevo.test',ts_event,id:123});const eventRequest=(body:unknown,auth='Bearer '+process.env.BREVO_WEBHOOK_TOKEN)=>new Request('http://localhost/_api/brevo/events',{method:'POST',headers:{Authorization:auth},body:JSON.stringify(body)});
 assert.equal((await webhook(eventRequest(event('delivered',at),'bad'))).status,401);assert.equal((await webhook(eventRequest(event('delivered',at)))).status,200);assert.equal((await message(id)).status,'delivery_confirmed');assert.equal((await message(id)).lastInteractionAt!.getTime(),originalInteraction,'Delivery events do not invent a new contact date');
 await webhook(eventRequest([event('request',at-10),event('opened',at+2),event('delivered',at)]));assert.equal((await message(id)).status,'delivery_confirmed');assert.equal(Number((await sql<{n:string}>`SELECT count(*) n FROM crm_email_events WHERE message_id=${'fixture-'+id+'@brevo.test'}`.execute(db)).rows[0].n),3);
 await webhook(eventRequest(event('hard_bounce',at+3)));assert.equal((await message(id)).status,'failed');await webhook(eventRequest(event('delivered',at-1)));assert.equal((await message(id)).status,'failed');await call({action:'outcome',id,event:'replied',notes:'Respondió por teléfono'},200,user.cookie);await webhook(eventRequest(event('opened',at+4)));assert.equal((await message(id)).status,'replied');
 // A restriction added after draft creation prevents both editing and dispatch; admin cannot bypass.
 let wm=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'whatsapp',templateId:w.id},200,user.cookie);assert(wm.body.includes('*Hola Persona real*'));await call({action:'restrict',leadId:l.id,contactId:c.id,channel:'whatsapp',reason:'Pidió no recibir WhatsApp'},200,user.cookie);await call({action:'edit',id:wm.id,revision:1,subject:'',body:wm.body},403,user.cookie);const restriction=(await sql<{id:string}>`SELECT id FROM crm_contact_restrictions WHERE account_id=${a.id} AND lifted_at IS NULL`.execute(db)).rows[0];await call({action:'lift',id:restriction.id,reason:'Autorización nueva'},403,user.cookie);await call({action:'lift',id:restriction.id,reason:'Autorización nueva'});
 wm=await call({action:'edit',id:wm.id,revision:1,subject:'',body:wm.body},200,user.cookie);await call({action:'dispatch',id:wm.id,revision:wm.revision,confirm:true},200,user.cookie);assert.equal((await message(wm.id)).status,'whatsapp_opened');const act=await db.selectFrom('crmActivities').selectAll().where('id','=',(await message(wm.id)).activityId!).executeTakeFirstOrThrow();assert.equal(act.typeId,'other');await call({action:'outcome',id:wm.id,event:'manual_sent',notes:'Confirmo que presioné Enviar'},200,user.cookie);assert.equal((await message(wm.id)).status,'manual_sent');assert.equal((await call({action:'dispatch',id:wm.id,revision:1,confirm:true},200,user.cookie)).url,undefined,'A replay never opens WhatsApp again');
 const empty=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:null,channel:'email',templateId:t.id},200,user.cookie);assert.equal(empty.recipientName,'');
 // Sequence start retry is idempotent. Pause cancels only its tasks; resume restores pending steps.
 const steps=[{waitDays:0,channel:'whatsapp',templateId:w.id},{waitDays:3,channel:'email',templateId:t.id}];await call({action:'sequence_save',name:'Asistida fixture',scope:'Contactos de prueba',steps,active:true},403,user.cookie);await call({action:'sequence_save',name:'Asistida fixture',scope:'Contactos de prueba',steps,active:true});const seq=(await sql<{id:string}>`SELECT id FROM crm_sequences WHERE name='Asistida fixture' ORDER BY id DESC LIMIT 1`.execute(db)).rows[0];const rid=randomUUID();const start={action:'sequence_start',id:rid,sequenceId:seq.id,leadId:l.id,contactId:c.id,confirm:true};await call(start,200,user.cookie);await call(start,200,user.cookie);let drafts=(await sql<Message>`SELECT * FROM crm_messages WHERE run_id=${rid}::uuid ORDER BY step_index`.execute(db)).rows;assert.equal(drafts.length,2);assert.equal(sends,1);let firstStep=await call({action:'edit',id:drafts[0].id,revision:1,subject:'',body:drafts[0].body},200,user.cookie);const secondStep=await call({action:'edit',id:drafts[1].id,revision:1,subject:'Segundo paso',body:drafts[1].body},200,user.cookie);await call({action:'dispatch',id:secondStep.id,revision:secondStep.revision,confirm:true},400,user.cookie);const openedStep=await call({action:'dispatch',id:firstStep.id,revision:firstStep.revision,confirm:true},200,user.cookie);assert(openedStep.url);await call({action:'outcome',id:firstStep.id,event:'manual_sent',notes:'Paso de hoy enviado manualmente'},200,user.cookie);await call({action:'dispatch',id:secondStep.id,revision:secondStep.revision,confirm:true},400,user.cookie);assert.equal(sends,1,'The future email step is never sent');
 await call({...start,id:randomUUID()},409,user.cookie);await call({action:'sequence_control',id:rid,state:'paused',reason:'Esperando decisión'},200,user.cookie);assert.equal((await db.selectFrom('crmTasks').select('status').where('id','=',drafts[1].taskId!).executeTakeFirstOrThrow()).status,'cancelled');await call({action:'sequence_control',id:rid,state:'active',reason:'Retomar seguimiento'},200,user.cookie);assert.equal((await db.selectFrom('crmTasks').select('status').where('id','=',drafts[1].taskId!).executeTakeFirstOrThrow()).status,'pending');
 await call({action:'outcome',id:wm.id,event:'replied',notes:'Respondió'},200,user.cookie);assert.equal((await sql<{status:string}>`SELECT status FROM crm_sequence_runs WHERE id=${rid}::uuid`.execute(db)).rows[0].status,'stopped');assert.equal((await message(drafts[1].id)).status,'cancelled');
 const cancelledRun=randomUUID();await call({...start,id:cancelledRun},200,user.cookie);await call({action:'sequence_control',id:cancelledRun,state:'cancelled',reason:'Cancelar fixture'},200,user.cookie);assert.equal((await call({...start,id:cancelledRun},200,user.cookie)).status,'cancelled');await call({action:'sequence_control',id:cancelledRun,state:'active',reason:'No debe volver'},409,user.cookie);
 const blockedRun=randomUUID();await call({...start,id:blockedRun},200,user.cookie);await db.updateTable('crmAccounts').set({doNotContact:true}).where('id','=',a.id).execute();assert.equal((await sql<{status:string}>`SELECT status FROM crm_sequence_runs WHERE id=${blockedRun}::uuid`.execute(db)).rows[0].status,'stopped');await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},403);await db.updateTable('crmAccounts').set({doNotContact:false}).where('id','=',a.id).execute();
 const convertedRun=randomUUID();await call({...start,id:convertedRun},200,user.cookie);await db.updateTable('crmAccounts').set({commercialStatus:'client'}).where('id','=',a.id).execute();assert.equal((await sql<{status:string}>`SELECT status FROM crm_sequence_runs WHERE id=${convertedRun}::uuid`.execute(db)).rows[0].status,'stopped');
 // Simulate network uncertainty and a post-acceptance DB failure. Neither permits a retry.
 let uncertain=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie);uncertain=await call({action:'edit',id:uncertain.id,revision:1,subject:'Prueba',body:'<p>Solo fixture</p>'},200,user.cookie);globalThis.fetch=async()=>{sends++;throw new Error('Network ambiguous')};await call({action:'dispatch',id:uncertain.id,revision:uncertain.revision,confirm:true},409,user.cookie);await call({action:'dispatch',id:uncertain.id,revision:uncertain.revision,confirm:true},409,user.cookie);assert.equal(sends,2);
 let accepted=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie);accepted=await call({action:'edit',id:accepted.id,revision:1,subject:'Prueba',body:'<p>Solo fixture</p>'},200,user.cookie);
 await sql`CREATE FUNCTION communication_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='accepted' THEN RAISE EXCEPTION 'Injected post acceptance failure'; END IF; RETURN NEW; END $$`.execute(db);await sql`CREATE TRIGGER communication_fail BEFORE UPDATE ON email_outbox FOR EACH ROW EXECUTE FUNCTION communication_fail()`.execute(db);globalThis.fetch=async()=>{sends++;return new Response(JSON.stringify({messageId:'accepted-but-not-persisted'}),{status:201})};await call({action:'dispatch',id:accepted.id,revision:accepted.revision,confirm:true},409,user.cookie);await sql`DROP TRIGGER communication_fail ON email_outbox; DROP FUNCTION communication_fail()`.execute(db);await call({action:'dispatch',id:accepted.id,revision:accepted.revision,confirm:true},409,user.cookie);assert.equal(sends,3);
 const early={event:'delivered',email:'person@example.com','message-id':'accepted-but-not-persisted',ts_event:at,tags:['hospeda-'+accepted.id]};assert.equal((await webhook(eventRequest(early))).status,200);assert.equal((await message(accepted.id)).status,'delivery_confirmed');
 // Provider callbacks/manual outcomes may arrive before the HTTP acceptance response.
 let racing=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie);racing=await call({action:'edit',id:racing.id,revision:1,subject:'Race fixture',body:'<p>Race fixture</p>'},200,user.cookie);
 globalThis.fetch=async()=>{await call({action:'outcome',id:racing.id,event:'replied',notes:'Respuesta manual mientras Brevo responde'},200,user.cookie);return new Response(JSON.stringify({messageId:'racing-acceptance'}),{status:201})};const raced=await call({action:'dispatch',id:racing.id,revision:racing.revision,confirm:true},200,user.cookie);assert.equal(raced.message.status,'replied');const racingActivity=await db.selectFrom('crmActivities').selectAll().where('id','=',raced.message.activityId).executeTakeFirstOrThrow();assert.equal(racingActivity.result,'Respuesta registrada manualmente');assert.equal((await db.selectFrom('crmActivities').select('id').where('notes','=',racingActivity.notes).execute()).length,1);
 let earlyMessage=await call({action:'prepare',id:randomUUID(),leadId:l.id,contactId:c.id,channel:'email',templateId:t.id},200,user.cookie);earlyMessage=await call({action:'edit',id:earlyMessage.id,revision:1,subject:'Early callback',body:'<p>Early callback fixture</p>'},200,user.cookie);
 let earlyActivityId:string|null=null;globalThis.fetch=async()=>{assert.equal((await webhook(eventRequest({event:'delivered',email:'person@example.com','message-id':'early-callback',ts_event:at,tags:['hospeda-'+earlyMessage.id]}))).status,200);earlyActivityId=(await message(earlyMessage.id)).activityId;return new Response(JSON.stringify({messageId:'early-callback'}),{status:201})};const earlyResult=await call({action:'dispatch',id:earlyMessage.id,revision:earlyMessage.revision,confirm:true},200,user.cookie);assert.equal(earlyResult.message.status,'delivery_confirmed');assert.equal(earlyResult.message.activityId,earlyActivityId,'Early callback and acceptance reuse one activity');
 // Documents are persisted as immutable version bytes in the DB, access controlled and reused by reference.
 const contextualId=randomUUID();await resource({action:'create',id:contextualId,title:'Documento del negocio',type:'propuesta',accountId:a.id,leadId:l.id,activityId:null,library:false,categoryId:null,version:{url:'https://example.com/contexto.pdf'}},200,user.cookie);await resource({action:'version',id:contextualId,revision:1,version:{url:'https://example.com/contexto-v2.pdf'}},200,user.cookie);
 const did=randomUUID();const content=Buffer.from('%PDF-1.4\nfixture document\n%%EOF');const create={action:'create',id:did,title:'Documento fixture',type:'propuesta',accountId:a.id,leadId:l.id,activityId:null,library:true,categoryId:null,version:{fileData:content.toString('base64'),fileName:'fixture.pdf',mimeType:'application/pdf'}};
 await resource(create,403,user.cookie);await resource(create);await resource(create);await sql`UPDATE crm_documents SET owner_email=${user.user.email} WHERE id=${did}::uuid`.execute(db);let versions=(await sql<{id:string;version:number}>`SELECT id,version FROM crm_document_versions WHERE document_id=${did}::uuid`.execute(db)).rows;assert.equal(versions.length,1);let dr=await download(new Request('http://localhost/_api/resources/download?versionId='+versions[0].id,{headers:{cookie:other.cookie}}));assert.equal(dr.status,403);await resource({action:'status',id:did,status:'approved',revision:1},403,user.cookie);await resource({action:'status',id:did,status:'approved',revision:1});
 dr=await download(new Request('http://localhost/_api/resources/download?versionId='+versions[0].id,{headers:{cookie:other.cookie}}));assert.equal(dr.status,200);assert.deepEqual(Buffer.from(await dr.arrayBuffer()),content);assert.match(dr.headers.get('Content-Disposition')!,/^attachment/);
 await resource({action:'version',id:did,revision:1,version:{url:'https://example.com/v2.pdf'}},403,user.cookie);await resource({action:'delete',id:did,revision:1},403,user.cookie);await resource({action:'status',id:did,status:'archived',revision:1},403,user.cookie);await resource({action:'version',id:did,revision:1,version:{url:'https://example.com/v2.pdf'}});await resource({action:'version',id:did,revision:1,version:{url:'https://example.com/stale.pdf'}},409);await resource({action:'status',id:did,status:'approved',revision:2});await resource({action:'link',id:did,accountId:a.id,leadId:l.id,activityId:null},200,user.cookie);await resource({action:'link',id:did,accountId:a.id,leadId:l.id,activityId:null},200,user.cookie);assert.equal(Number((await sql<{n:string}>`SELECT count(*) n FROM crm_document_links WHERE document_id=${did}::uuid`.execute(db)).rows[0].n),1);
 await resource({...create,id:randomUUID(),version:{url:'javascript:alert(1)'}},400);await resource({...create,id:randomUUID(),version:{fileData:Buffer.from('not pdf').toString('base64'),fileName:'bad.pdf',mimeType:'application/pdf'}},400);await resource({...create,id:randomUUID(),version:{fileData:Buffer.alloc(2097153).toString('base64'),fileName:'big.pdf',mimeType:'application/pdf'}},400);
 // Merge all new relationships while preserving original attribution and snapshots.
 const dest=await db.insertInto('crmAccounts').values({nombre:'Destino '+stamp,ciudad:'Colón'}).returningAll().executeTakeFirstOrThrow();let r=await quality(request({action:'merge_preview',sourceId:a.id,destinationId:dest.id}));assert.equal(r.status,200);const p=superjson.parse<any>(await r.text());r=await quality(request({action:'merge_confirm',sourceId:a.id,destinationId:dest.id,token:p.token,selections:Object.fromEntries(businessFields.map(f=>[f,'destination'])),reason:'Revisado en fixture',confirm:true}));assert.equal(r.status,200,await r.text());assert.equal((await message(id)).accountId,dest.id);assert.equal((await sql<{originalAccountId:string}>`SELECT original_account_id FROM crm_messages WHERE id=${id}::uuid`.execute(db)).rows[0].originalAccountId,a.id);assert.equal((await sql<{accountId:string}>`SELECT account_id FROM crm_documents WHERE id=${did}::uuid`.execute(db)).rows[0].accountId,dest.id);
 await resource({action:'delete',id:did,revision:2});assert.equal((await download(new Request('http://localhost/_api/resources/download?versionId='+versions[0].id,{headers:{cookie:admin.cookie}}))).status,400);assert.equal(Number((await sql<{n:string}>`SELECT count(*) n FROM crm_document_versions WHERE document_id=${did}::uuid`.execute(db)).rows[0].n),2);
 await resource({action:'create',id:randomUUID(),title:'CI persistence fixture',type:'test',accountId:null,leadId:null,activityId:null,library:true,categoryId:null,version:{fileData:Buffer.from('%PDF-1.4\nPersistent fixture\n%%EOF').toString('base64'),fileName:'persistent.pdf',mimeType:'application/pdf'}});
 console.log('Communication/resources: permissions, snapshots, restrictions, honest statuses, duplicate dispatch, events, uncertainty, assisted sequences, immutable files, reuse, fusion and soft delete passed');
}finally{globalThis.fetch=realFetch;await db.destroy();}
