import assert from 'node:assert/strict';import superjson from 'superjson';import {db} from '../src/helpers/db';import {setServerSession} from '../src/helpers/getSetServerSession';import {post as commercial,get as commercialGet} from '../src/endpoints/commercial';import {get as workGet,post as work} from '../src/endpoints/work';import {handle as leadsGet} from '../src/endpoints/leads_GET';import {post as pipeline} from '../src/endpoints/pipeline';
assert.equal(process.env.CRM_TEST_DATABASE,'1','Use a disposable database');
const u=await db.insertInto('users').values({email:'usability-'+Date.now()+'@example.com',displayName:'Prueba de uso',role:'user'}).returningAll().executeTakeFirstOrThrow();const sid='usability-'+u.id;await db.insertInto('sessions').values({id:sid,userId:u.id,expiresAt:new Date(Date.now()+3600000)}).execute();const response=new Response();await setServerSession(response,{id:sid,createdAt:Date.now(),lastAccessed:Date.now()});const cookie=response.headers.get('set-cookie')!.split(';')[0];
const request=(endpoint:string,body?:unknown)=>new Request('http://localhost/_api/'+endpoint,{headers:{cookie},...(body?{method:'POST',body:superjson.stringify(body)}:{})});
async function call(handler:(r:Request)=>Promise<Response>,endpoint:string,body?:unknown,status=200){const r=await handler(request(endpoint,body));const data=superjson.parse<any>(await r.text());assert.equal(r.status,status,data.error);return data}
try{
 const accountId=(await call(commercial,'commercial',{action:'account_save',nombre:'Recorrido simple'})).id;let d=await call(commercialGet,'commercial?accountId='+accountId);assert.equal(d.account.assignedUserEmail,u.email);assert.equal((await call(leadsGet,'leads?entity=business&q=Recorrido%20simple')).total,1,'A new business is visible before its first sale');
 const contactId=(await call(commercial,'commercial',{action:'contact_save',accountId,name:'Ana',email:'ana@example.com',isPrimary:true})).id;
 const leadId=(await call(commercial,'commercial',{action:'opportunity_save',accountId,opportunityName:'Publicación',estado:'Cargado',primaryContactId:contactId})).id;d=await call(commercialGet,'commercial?accountId='+accountId);assert.equal(d.opportunities[0].assignedUserEmail,u.email);
 const taskId=(await call(work,'work',{action:'task_save',accountId,leadId,title:'Primera conversación',typeId:'call',dueDate:'2027-01-15'})).id;
 await call(work,'work',{action:'task_status',id:taskId,status:'completed',outcome:'interested',result:'Pidió revisar la propuesta',contactIds:[contactId],channel:'email',nextTask:{title:'Revisar propuesta',typeId:'does-not-exist',dueDate:'2027-01-16'}},400);assert.equal((await db.selectFrom('crmTasks').select('status').where('id','=',taskId).executeTakeFirstOrThrow()).status,'pending','Invalid next step rolls back the completion');
 await call(work,'work',{action:'task_status',id:taskId,status:'completed',outcome:'interested',result:'Pidió revisar la propuesta',contactIds:[contactId],channel:'email',nextTask:{title:'Revisar propuesta',typeId:'followup',dueDate:'2027-01-16'}});let w=await call(workGet,'work?accountId='+accountId+'&mode=detail');assert(w.activities.some((a:any)=>a.outcome==='interested'&&a.channel==='email'&&a.contactIds.includes(contactId)));assert(w.tasks.some((t:any)=>t.title==='Revisar propuesta'&&t.status==='pending'));
 const records=await db.insertInto('leads').values(Array.from({length:120},(_,i)=>({accountId,nombre:'Recorrido simple',opportunityName:'Venta '+i,estado:'Cargado',assignedUserEmail:u.email}))).returning('id').execute();await db.insertInto('crmTasks').values(records.map((l,i)=>({accountId,leadId:l.id,title:'Encuentro '+i,typeId:'meeting',dueDate:'2027-01-15',assignedUserEmail:u.email}))).execute();
 w=await call(workGet,'work?mode=agenda&calendar=true&from=2027-01-01&to=2027-01-31');assert(w.tasks.filter((t:any)=>t.accountId===accountId).length>=120,'Calendar covers the complete month');const list=await call(leadsGet,'leads?entity=opportunity&view=board&q='+encodeURIComponent('Recorrido simple'));assert(list.rows.length>=121,'Board is not truncated to a table page');
 const won=await db.selectFrom('crmStages').select('name').where('classification','=','won').where('active','=',true).executeTakeFirstOrThrow();await call(pipeline,'pipeline',{action:'transition',leadId,revision:(await db.selectFrom('leads').select('pipelineRevision').where('id','=',leadId).executeTakeFirstOrThrow()).pipelineRevision,stage:won.name,convertClient:true,onboarding:{title:'Acompañar al cliente',dueDate:'2027-01-17'}});d=await call(commercialGet,'commercial?accountId='+accountId);assert.equal(d.account.commercialStatus,'client');assert.equal(d.opportunities.find((o:any)=>o.id===leadId).estado,won.name);assert((await db.selectFrom('crmTasks').selectAll().where('accountId','=',accountId).where('leadId','is',null).execute()).some(t=>t.title==='Acompañar al cliente'));
 await call(commercial,'commercial',{action:'account_archive',accountId,archived:true,reason:'Pausar relación de prueba'});assert((await call(commercialGet,'commercial?accountId='+accountId)).account.archivedAt);assert.equal((await call(leadsGet,'leads?entity=business&q=Recorrido%20simple')).total,0);assert((await call(commercialGet,'commercial?archived=true&q=Recorrido%20simple')).rows.some((a:any)=>a.id===accountId));await call(commercial,'commercial',{action:'account_archive',accountId,archived:false,reason:'Retomar relación de prueba'});assert.equal((await call(leadsGet,'leads?entity=business&q=Recorrido%20simple')).total,1);
 console.log('Usability API: inherited owner, selected participant/channel, atomic result + next step rollback, 120 monthly events, complete board, won + client + care, reversible archive passed');
}finally{await db.destroy()}
